import type { ModuleSeed } from '../types'

export const GRADE_4_ELA: ModuleSeed[] = [
  {
    slug: 'grade4-ela-theme-and-summary',
    title: 'Theme and Summary',
    description: 'Determine the theme of a story, drama, or poem from details in the text and summarize the text',
    subject: 'ela',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Reading Literature',
    standardCodes: ['4.RL.2'],
    content: {
      intro: {
        title: 'Theme and Summary',
        text: 'Every story has a big idea behind it called the theme. The theme is the lesson or message the author wants you to take away. Today we will learn how to figure out the theme and how to write a summary that captures the most important parts of a story.',
        culturalHook: 'Think about a story a family member has told you. What lesson did it teach?',
      },
      segments: [
        {
          index: 0,
          title: 'What Is Theme?',
          text: 'The theme of a story is the big message or lesson the author wants readers to understand. It is not the same as the topic. The topic might be "friendship," but the theme is a complete thought like "True friends stand by you even when things are hard." To find the theme, pay attention to what the main character learns, how they change, and what problems they face. The theme is usually not stated directly — you have to figure it out by thinking about the whole story. Ask yourself: What did the character learn? What message does the author want me to remember?',
          keyVocabulary: ['theme', 'topic', 'message', 'lesson'],
          example: 'In a story where a girl helps a new student feel welcome, the theme might be "Kindness can make someone\'s whole day better."',
        },
        {
          index: 1,
          title: 'Finding Theme Using Details',
          text: 'Authors use story details to build toward the theme. Look at the character\'s actions, dialogue, and the events that happen. If a character keeps trying after failing, the theme might be about perseverance. If characters resolve a conflict by talking it out, the theme might be about communication. Pay special attention to the ending of the story — this is often where the theme becomes clearest. Also notice repeated ideas. If the author mentions honesty several times, the theme probably involves being truthful. Use evidence from the text to support the theme you identify.',
          keyVocabulary: ['details', 'dialogue', 'evidence', 'perseverance'],
        },
        {
          index: 2,
          title: 'What Is a Summary?',
          text: 'A summary is a short retelling of the most important parts of a story. It includes the main characters, the setting, the problem, key events, and the solution. A good summary does not include every tiny detail — just the big ideas. It should be much shorter than the original text. When you write a summary, use your own words instead of copying sentences from the story. Keep events in the order they happened. A strong summary helps someone who has not read the story understand what it was about.',
          keyVocabulary: ['summary', 'retelling', 'key events', 'solution'],
        },
        {
          index: 3,
          title: 'Writing a Summary Step by Step',
          text: 'Follow these steps to write a solid summary. First, identify the main character and the setting. Second, state the problem or challenge the character faces. Third, describe two or three key events — not every event, just the most important ones that move the story forward. Fourth, explain how the problem is resolved. Finally, mention the theme or lesson if it fits naturally. Use transition words like "first," "then," "next," and "finally" to keep your summary organized. Read your summary back to yourself and ask: Does this capture the heart of the story?',
          keyVocabulary: ['transition words', 'organized', 'resolved', 'key events'],
        },
      ],
      practice: [
        { index: 0, question: 'What is the difference between the topic and the theme of a story?', type: 'short-answer', correctAnswer: 'The topic is a single word or phrase like "friendship," while the theme is a complete message or lesson such as "True friends help each other through tough times."', hint: 'Think about it this way: the topic is one word, but the theme is a full sentence.', explanation: 'A topic is a broad subject (like bravery), while a theme is the specific lesson or message the author teaches about that subject.', standardCode: '4.RL.2' },
        { index: 1, question: 'In a story, a boy loses a race but congratulates the winner and practices harder for next time. What is a likely theme?', type: 'multiple-choice', options: ['Racing is the best sport.', 'Being a good sport and working hard leads to growth.', 'Winning is the most important thing.', 'Practice is boring.'], correctAnswer: 'Being a good sport and working hard leads to growth.', hint: 'Focus on what the character learned and how he responded to losing.', explanation: 'The boy showed good sportsmanship and determination. The theme is about growing through effort and grace, not just winning.', standardCode: '4.RL.2' },
        { index: 2, question: 'Which of the following belongs in a good summary?', type: 'multiple-choice', options: ['Every detail from the story', 'Only the main characters, problem, key events, and solution', 'Your personal opinion of the story', 'Dialogue copied word for word'], correctAnswer: 'Only the main characters, problem, key events, and solution', hint: 'A summary is short and focused on the big ideas.', explanation: 'A summary includes only the most important elements: main characters, setting, problem, key events, and resolution — told in your own words.', standardCode: '4.RL.2' },
        { index: 3, question: 'Where in a story is the theme often clearest?', type: 'multiple-choice', options: ['The very first sentence', 'The middle of the story', 'Near the ending when the problem is resolved', 'In the title'], correctAnswer: 'Near the ending when the problem is resolved', hint: 'Think about when the character finally learns their lesson.', explanation: 'The theme often becomes clearest at the end of the story, when the character has changed or the problem is resolved and the lesson emerges.', standardCode: '4.RL.2' },
        { index: 4, question: 'Rewrite this in your own words as a one-sentence summary: "Maria forgot to study for her test. She got a low score and felt sad. She decided to make a study plan so it would not happen again."', type: 'short-answer', correctAnswer: 'After getting a low test score because she did not study, Maria made a plan to prepare better next time.', hint: 'Combine the key ideas into one sentence using your own words.', explanation: 'A good summary captures the problem (not studying), the consequence (low score), and the resolution (making a plan) in a brief statement.', standardCode: '4.RL.2' },
      ],
      assessment: {
        questions: [
          { question: 'A story is about a squirrel who hoards all the acorns and refuses to share. When winter comes, the squirrel is lonely because no one visits. The squirrel learns to share and makes friends. What is the theme?', type: 'short-answer', correctAnswer: 'Sharing with others brings friendship and happiness.', standardCode: '4.RL.2' },
          { question: 'What should a summary NOT include?', type: 'multiple-choice', options: ['The main character', 'The problem', 'Every small detail from the story', 'The solution'], correctAnswer: 'Every small detail from the story', standardCode: '4.RL.2' },
          { question: 'Which part of a story gives the best clues about the theme?', type: 'multiple-choice', options: ['The setting description', 'What the character learns or how they change', 'The names of the characters', 'The page numbers'], correctAnswer: 'What the character learns or how they change', standardCode: '4.RL.2' },
        ],
      },
    },
  },
  {
    slug: 'grade4-ela-summarizing-text-details',
    title: 'Summarizing Text Details',
    description: 'Summarize a story by identifying and retelling the key details in a concise way',
    subject: 'ela',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Reading Literature',
    standardCodes: ['4.RL.2'],
    content: {
      intro: {
        title: 'Summarizing Text Details',
        text: 'When you read a story, there are many details — but not all of them are equally important. Learning to pick out the key details and retell them in order helps you understand and remember what you read. Let us practice being great summarizers!',
      },
      segments: [
        {
          index: 0,
          title: 'Key Details vs. Minor Details',
          text: 'A key detail is something that matters to the story. Without it, the story would not make sense. A minor detail adds extra description but is not necessary for understanding the plot. For example, in a story about a dog who finds his way home, the key detail is that the dog gets lost and finds his way back. A minor detail might be the color of the dog\'s collar. When summarizing, include the key details and leave out the minor ones. Ask yourself: If I removed this detail, would the story still make sense? If yes, it is probably a minor detail.',
          keyVocabulary: ['key detail', 'minor detail', 'plot', 'necessary'],
        },
        {
          index: 1,
          title: 'Identifying the Beginning, Middle, and End',
          text: 'Every story has a beginning, a middle, and an end. The beginning introduces the characters and setting. The middle presents the problem and the events that happen because of it. The end shows how the problem is solved. When you summarize, make sure you cover all three parts. Think of the story like a sandwich: the beginning and end are the bread, and the middle is the filling. You need all the pieces for the sandwich to hold together.',
          keyVocabulary: ['beginning', 'middle', 'end', 'setting', 'problem'],
          example: 'Beginning: A girl moves to a new school. Middle: She struggles to make friends. End: She joins a club and meets people who share her interests.',
        },
        {
          index: 2,
          title: 'Using "Somebody Wanted But So Then"',
          text: 'A helpful strategy for summarizing fiction is called "Somebody Wanted But So Then." Somebody tells who the main character is. Wanted tells what they wanted or needed. But tells the problem or conflict. So tells how they tried to solve it. Then tells how the story ended. For example: Somebody — a young farmer. Wanted — to grow enough food for the village. But — a drought dried up the river. So — he dug a well and found water underground. Then — the crops grew and the village celebrated. This framework keeps your summary focused and organized.',
          keyVocabulary: ['strategy', 'conflict', 'framework', 'organized'],
        },
        {
          index: 3,
          title: 'Practicing Concise Summaries',
          text: 'A concise summary uses as few words as possible while still covering the important information. Aim for three to five sentences. Avoid repeating ideas. Use your own words instead of copying from the text. After writing your summary, reread it and check: Did I include the main character, the problem, the key events, and the ending? Did I leave out minor details? Is it short enough that someone could read it quickly and understand the whole story? If you can answer yes to all three, you have written a strong summary.',
          keyVocabulary: ['concise', 'reread', 'check'],
        },
      ],
      practice: [
        { index: 0, question: 'What is the difference between a key detail and a minor detail?', type: 'short-answer', correctAnswer: 'A key detail is important to the plot and necessary for understanding the story, while a minor detail adds extra description but could be removed without changing the story.', hint: 'Think about which details the story cannot survive without.', explanation: 'Key details drive the plot forward. Minor details are nice extras like the color of a shirt, but they do not change what happens in the story.', standardCode: '4.RL.2' },
        { index: 1, question: 'In the "Somebody Wanted But So Then" strategy, what does "But" represent?', type: 'multiple-choice', options: ['The main character', 'The setting', 'The problem or conflict', 'The ending'], correctAnswer: 'The problem or conflict', hint: 'The word "but" signals something going wrong or getting in the way.', explanation: '"But" introduces the conflict or obstacle that keeps the character from easily getting what they want.', standardCode: '4.RL.2' },
        { index: 2, question: 'Which of these is a minor detail in a story about a boy winning a spelling bee? A) The boy studied every night. B) The boy wore a blue shirt. C) The boy won the final round. D) The boy felt nervous on stage.', type: 'multiple-choice', options: ['A) The boy studied every night.', 'B) The boy wore a blue shirt.', 'C) The boy won the final round.', 'D) The boy felt nervous on stage.'], correctAnswer: 'B) The boy wore a blue shirt.', hint: 'Which detail could be removed without changing the story?', explanation: 'The color of his shirt does not affect the plot. The other details — studying, winning, and feeling nervous — all matter to understanding the story.', standardCode: '4.RL.2' },
        { index: 3, question: 'How many sentences should a concise summary typically be?', type: 'multiple-choice', options: ['One sentence', 'Three to five sentences', 'Ten or more sentences', 'As many as the original story'], correctAnswer: 'Three to five sentences', hint: 'A summary should be short but complete.', explanation: 'A good summary is usually three to five sentences long — short enough to be quick but long enough to cover the main character, problem, events, and resolution.', standardCode: '4.RL.2' },
        { index: 4, question: 'Use "Somebody Wanted But So Then" to summarize: A fox wanted to cross a river. The bridge was broken. The fox found stepping stones and crossed safely.', type: 'short-answer', correctAnswer: 'Somebody: A fox. Wanted: to cross a river. But: the bridge was broken. So: the fox found stepping stones. Then: the fox crossed safely.', hint: 'Fill in each part: Somebody, Wanted, But, So, Then.', explanation: 'Using the framework: The fox (Somebody) wanted to cross the river (Wanted), but the bridge was broken (But), so the fox used stepping stones (So), and then crossed safely (Then).', standardCode: '4.RL.2' },
      ],
      assessment: {
        questions: [
          { question: 'Why should you leave out minor details when writing a summary?', type: 'short-answer', correctAnswer: 'Minor details make a summary too long and can distract from the main ideas of the story.', standardCode: '4.RL.2' },
          { question: 'Which part of a story does the beginning usually introduce?', type: 'multiple-choice', options: ['The solution', 'The characters and setting', 'The climax', 'The theme statement'], correctAnswer: 'The characters and setting', standardCode: '4.RL.2' },
          { question: 'In "Somebody Wanted But So Then," what does "Then" tell the reader?', type: 'multiple-choice', options: ['What the character wanted', 'How the story ended', 'The main conflict', 'The setting'], correctAnswer: 'How the story ended', standardCode: '4.RL.2' },
        ],
      },
    },
  },
  {
    slug: 'grade4-ela-compare-contrast-characters',
    title: 'Compare and Contrast Characters',
    description: 'Compare and contrast two or more characters in a story using specific details from the text',
    subject: 'ela',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Reading Literature',
    standardCodes: ['4.RL.3'],
    content: {
      intro: {
        title: 'Compare and Contrast Characters',
        text: 'Stories come alive through their characters. When we compare characters, we look at how they are alike. When we contrast them, we look at how they are different. Comparing and contrasting helps us understand characters more deeply and see why they make the choices they do.',
      },
      segments: [
        {
          index: 0,
          title: 'What Does Compare and Contrast Mean?',
          text: 'To compare means to find similarities — things that are the same between two or more characters. To contrast means to find differences — things that are not the same. For example, two characters might both be brave (a similarity), but one might be quiet while the other is loud (a difference). When you compare and contrast, you look at traits, actions, motivations, and feelings. Traits are qualities that describe someone, like kind, stubborn, or creative. Actions are what a character does. Motivations are the reasons behind their actions.',
          keyVocabulary: ['compare', 'contrast', 'similarities', 'differences', 'traits', 'motivations'],
        },
        {
          index: 1,
          title: 'Using a Venn Diagram',
          text: 'A Venn diagram is a tool with two overlapping circles that helps you organize comparisons. Write what is unique to the first character in the left circle. Write what is unique to the second character in the right circle. Write what they share in the overlapping middle section. For example, if Character A is shy and loves reading, and Character B is outgoing and loves reading, then "loves reading" goes in the middle because they share it. "Shy" goes on the left and "outgoing" goes on the right. This visual tool makes it easy to see similarities and differences at a glance.',
          keyVocabulary: ['Venn diagram', 'overlapping', 'unique', 'visual tool'],
          example: 'Left circle (Rosa): shy, artistic. Middle (both): brave, fourth graders. Right circle (James): talkative, athletic.',
        },
        {
          index: 2,
          title: 'Looking at Characters\' Actions and Responses',
          text: 'One of the best ways to compare characters is to look at how they respond to the same event. If two characters both face a bully, one might stand up and speak out while the other might walk away and tell a teacher. Neither response is wrong, but the difference reveals their personalities. When you read, ask: How does each character react to problems? Do they act quickly or think carefully first? Do they work alone or ask for help? These observations give you strong evidence for comparing and contrasting.',
          keyVocabulary: ['response', 'personality', 'evidence', 'observation'],
        },
        {
          index: 3,
          title: 'Writing a Compare and Contrast Paragraph',
          text: 'When writing about characters, use comparison signal words like "both," "similarly," "also," and "in the same way" to show similarities. Use contrast signal words like "however," "on the other hand," "unlike," and "while" to show differences. Start your paragraph by naming the two characters and the story they are from. Then discuss one or two similarities with evidence from the text. Next, discuss one or two differences with evidence. End with a sentence that wraps up your comparison. Always support your ideas with specific details from the story.',
          keyVocabulary: ['signal words', 'similarly', 'however', 'evidence'],
        },
      ],
      practice: [
        { index: 0, question: 'What does it mean to compare two characters?', type: 'multiple-choice', options: ['Find how they are different', 'Find how they are alike', 'Decide who is better', 'Count how many times they speak'], correctAnswer: 'Find how they are alike', hint: 'Compare focuses on things that are the same.', explanation: 'Comparing means finding similarities — the ways two characters are alike in their traits, actions, or feelings.', standardCode: '4.RL.3' },
        { index: 1, question: 'In a Venn diagram, where do you write traits that both characters share?', type: 'multiple-choice', options: ['In the left circle only', 'In the right circle only', 'In the overlapping middle section', 'Outside both circles'], correctAnswer: 'In the overlapping middle section', hint: 'Shared traits belong where the two circles meet.', explanation: 'The overlapping section of a Venn diagram is where you place traits, actions, or feelings that both characters have in common.', standardCode: '4.RL.3' },
        { index: 2, question: 'Character A runs away from a thunderstorm. Character B stays outside and watches it with excitement. What does this contrast reveal?', type: 'short-answer', correctAnswer: 'It reveals that Character A is fearful or cautious while Character B is brave or curious.', hint: 'Think about what each reaction tells you about the character\'s personality.', explanation: 'Their opposite reactions to the same event show different personality traits. Character A is afraid while Character B is fascinated, revealing contrasting attitudes toward the unknown.', standardCode: '4.RL.3' },
        { index: 3, question: 'Which signal word shows a contrast between two characters?', type: 'multiple-choice', options: ['Both', 'Similarly', 'However', 'Also'], correctAnswer: 'However', hint: 'Which word signals a change or difference?', explanation: '"However" is a contrast signal word that tells the reader a difference is coming. "Both," "similarly," and "also" are comparison words that show similarities.', standardCode: '4.RL.3' },
        { index: 4, question: 'Why is it important to use evidence from the text when comparing characters?', type: 'short-answer', correctAnswer: 'Evidence from the text proves your ideas and shows that your comparison is based on what actually happened in the story, not just guesses.', hint: 'Think about what makes a comparison strong and convincing.', explanation: 'Using text evidence supports your claims and shows you are basing your comparison on the author\'s words, not personal opinions alone. It makes your writing more convincing.', standardCode: '4.RL.3' },
      ],
      assessment: {
        questions: [
          { question: 'Which pair of signal words shows one similarity and one difference?', type: 'multiple-choice', options: ['Both / However', 'Both / Also', 'However / Unlike', 'Similarly / Also'], correctAnswer: 'Both / However', standardCode: '4.RL.3' },
          { question: 'Two characters both love soccer, but one is a team captain and the other is new to the sport. Name one similarity and one difference.', type: 'short-answer', correctAnswer: 'Similarity: They both love soccer. Difference: One is a team captain (experienced) while the other is new to the sport (beginner).', standardCode: '4.RL.3' },
          { question: 'What tool uses two overlapping circles to organize comparisons?', type: 'short-answer', correctAnswer: 'A Venn diagram', standardCode: '4.RL.3' },
        ],
      },
    },
  },
  {
    slug: 'grade4-ela-main-idea-and-details',
    title: 'Main Idea and Details',
    description: 'Determine the main idea of an informational text and explain how it is supported by key details',
    subject: 'ela',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Reading Informational',
    standardCodes: ['4.RI.2'],
    content: {
      intro: {
        title: 'Main Idea and Details',
        text: 'Informational texts are full of facts and ideas. But every passage has one big idea that ties everything together — that is the main idea. The key details are the facts and examples that support the main idea. Learning to find both will make you a stronger reader of nonfiction.',
      },
      segments: [
        {
          index: 0,
          title: 'What Is the Main Idea?',
          text: 'The main idea is the most important point the author makes in a passage or section. It is what the text is mostly about. The main idea is different from the topic. The topic might be "honeybees," but the main idea could be "Honeybees play a critical role in pollinating the plants we depend on for food." To find the main idea, read the whole passage first. Then ask yourself: What is the one big point the author is trying to make? Sometimes the main idea is stated directly in the first or last sentence. Other times you need to figure it out by looking at all the details together.',
          keyVocabulary: ['main idea', 'topic', 'nonfiction', 'passage'],
        },
        {
          index: 1,
          title: 'Identifying Key Details',
          text: 'Key details are the facts, examples, and explanations that support the main idea. They answer questions like who, what, where, when, why, and how. Not every sentence is a key detail — some sentences are extra information. A key detail directly connects to and strengthens the main idea. For example, if the main idea is that honeybees are important pollinators, key details might include the number of crops they pollinate, how pollination works, and what would happen without bees. Practice asking: Does this detail help prove or explain the main idea?',
          keyVocabulary: ['key details', 'support', 'facts', 'examples'],
          example: 'Main idea: Exercise keeps your body healthy. Key details: It strengthens your heart, builds strong bones, and helps you sleep better.',
        },
        {
          index: 2,
          title: 'How Details Support the Main Idea',
          text: 'Think of the main idea as the roof of a house and the key details as the pillars holding it up. Without those pillars, the roof would fall. Each key detail adds strength to the main idea by giving readers evidence and reasons to believe it. When you explain how details support the main idea, you might say: "The detail about bees pollinating over 100 crops supports the main idea that bees are important because it shows just how many foods depend on them." Always connect the detail back to the main idea to show the relationship.',
          keyVocabulary: ['evidence', 'relationship', 'support', 'connect'],
        },
        {
          index: 3,
          title: 'Summarizing Informational Text',
          text: 'To summarize an informational text, state the main idea first. Then include two or three key details that support it. Leave out minor or extra details. Use your own words. For example: "This article explains that recycling helps protect the environment. Recycling reduces waste in landfills, saves natural resources like trees and water, and lowers pollution from making new products." Notice how the summary leads with the main idea and follows with key details that directly support it. Keep your summary to three or four sentences at most.',
          keyVocabulary: ['summarize', 'informational text', 'landfill', 'natural resources'],
        },
      ],
      practice: [
        { index: 0, question: 'What is the main idea of a passage?', type: 'multiple-choice', options: ['The first sentence of the passage', 'The most important point the author makes', 'A fun fact from the text', 'The title of the article'], correctAnswer: 'The most important point the author makes', hint: 'The main idea is the big picture — what the whole passage is mostly about.', explanation: 'The main idea is the central point or most important message of the passage. It is not always the first sentence or the title, though those can give clues.', standardCode: '4.RI.2' },
        { index: 1, question: 'Read this passage: "Dolphins are very smart animals. They can learn tricks, communicate with each other using clicks and whistles, and solve problems to find food." What is the main idea?', type: 'short-answer', correctAnswer: 'Dolphins are very smart animals.', hint: 'Look for the sentence that all the other details support.', explanation: 'The first sentence states the main idea. The other sentences provide key details (learning tricks, communicating, solving problems) that support the claim that dolphins are smart.', standardCode: '4.RI.2' },
        { index: 2, question: 'Which of the following is a key detail that supports the main idea "Water is essential for human survival"?', type: 'multiple-choice', options: ['Water parks are fun in the summer.', 'The human body is made up of about 60 percent water.', 'Some water bottles are blue.', 'Rivers flow toward the ocean.'], correctAnswer: 'The human body is made up of about 60 percent water.', hint: 'Which detail explains why water is essential for humans?', explanation: 'The fact that the human body is 60 percent water directly supports the idea that water is essential for survival. The other options are about water but do not connect to human survival.', standardCode: '4.RI.2' },
        { index: 3, question: 'How is the main idea different from the topic?', type: 'short-answer', correctAnswer: 'The topic is the general subject in one or two words (like "volcanoes"), while the main idea is a complete statement about the topic (like "Volcanoes are powerful natural forces that shape the earth\'s surface").', hint: 'A topic is short — usually one or two words. A main idea is a full thought.', explanation: 'The topic names the subject broadly. The main idea makes a specific point or claim about that topic, usually expressed as a complete sentence.', standardCode: '4.RI.2' },
        { index: 4, question: 'A passage about rainforests says: "Rainforests are home to more than half the world\'s plant and animal species. They also produce much of the oxygen we breathe and absorb carbon dioxide." How do these details support the main idea that rainforests are important?', type: 'short-answer', correctAnswer: 'They show that rainforests are important because they support a huge number of species and help produce oxygen and reduce carbon dioxide, which humans and animals need to survive.', hint: 'Explain how each detail connects to the idea that rainforests matter.', explanation: 'Each detail gives a specific reason why rainforests are important: biodiversity (half the world\'s species) and air quality (oxygen production and carbon absorption). Together they build a strong case.', standardCode: '4.RI.2' },
      ],
      assessment: {
        questions: [
          { question: '"Eating a balanced breakfast gives students energy, helps them focus in class, and improves test scores." What is the main idea?', type: 'short-answer', correctAnswer: 'Eating a balanced breakfast is good for students.', standardCode: '4.RI.2' },
          { question: 'Which question helps you identify key details?', type: 'multiple-choice', options: ['What color is the book cover?', 'Does this detail help prove or explain the main idea?', 'How long is the passage?', 'Who is the publisher?'], correctAnswer: 'Does this detail help prove or explain the main idea?', standardCode: '4.RI.2' },
          { question: 'When summarizing informational text, what should you state first?', type: 'multiple-choice', options: ['A minor detail', 'Your personal opinion', 'The main idea', 'The author\'s name'], correctAnswer: 'The main idea', standardCode: '4.RI.2' },
        ],
      },
    },
  },
  {
    slug: 'grade4-ela-text-structure-and-purpose',
    title: 'Text Structure and Author\'s Purpose',
    description: 'Describe the overall structure of events, ideas, concepts, or information in a text and identify the author\'s purpose',
    subject: 'ela',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Reading Informational',
    standardCodes: ['4.RI.5'],
    content: {
      intro: {
        title: 'Text Structure and Author\'s Purpose',
        text: 'Authors organize their writing in different ways depending on what they want to say. The way a text is organized is called its text structure. Understanding text structure helps you follow the author\'s ideas and figure out why they wrote the text in the first place.',
      },
      segments: [
        {
          index: 0,
          title: 'Common Text Structures',
          text: 'There are five common text structures. Chronological order presents events in the order they happened, using words like "first," "next," and "finally." Cause and effect explains why something happens and what results from it, with signal words like "because," "so," and "as a result." Compare and contrast shows how two things are alike and different, using words like "both," "however," and "unlike." Problem and solution presents a problem and explains how it can be solved. Description gives details about a topic to paint a picture in the reader\'s mind. Recognizing these structures helps you predict what information is coming next.',
          keyVocabulary: ['chronological', 'cause and effect', 'compare and contrast', 'problem and solution', 'description'],
        },
        {
          index: 1,
          title: 'Signal Words and Clues',
          text: 'Signal words are clues that tell you which text structure the author is using. If you see "first," "then," "after," and "finally," the structure is probably chronological order. Words like "because," "since," and "therefore" point to cause and effect. "Similarly," "on the other hand," and "in contrast" signal compare and contrast. "The problem is" and "one solution" indicate problem and solution. When you spot these signal words, circle or underline them. They act like a map that guides you through the text and helps you organize the information in your mind.',
          keyVocabulary: ['signal words', 'clues', 'therefore', 'in contrast'],
          example: '"Because the river flooded, many families had to leave their homes." Signal word "because" shows cause and effect.',
        },
        {
          index: 2,
          title: 'Author\'s Purpose',
          text: 'The author\'s purpose is the reason the author wrote the text. There are three main purposes: to inform, to persuade, and to entertain. When the author wants to inform, they give facts and explanations. When the author wants to persuade, they try to convince you to think or do something. When the author wants to entertain, they tell stories or use humor to keep you interested. Sometimes a text has more than one purpose. A funny article about saving water might entertain you while also persuading you to use less water. Ask yourself: Why did the author write this?',
          keyVocabulary: ['author\'s purpose', 'inform', 'persuade', 'entertain'],
        },
        {
          index: 3,
          title: 'Connecting Structure to Purpose',
          text: 'Text structure and author\'s purpose are closely connected. An author who wants to inform you about a historical event might use chronological order. An author who wants to persuade you that recycling matters might use problem and solution, first describing pollution as a problem and then offering recycling as the solution. An author writing a science article might use cause and effect to explain how global warming works. When you identify both the structure and the purpose, you gain a deeper understanding of the text. Try asking: How did the author organize this, and why did they choose that organization?',
          keyVocabulary: ['connected', 'organization', 'deeper understanding'],
        },
      ],
      practice: [
        { index: 0, question: 'What text structure uses words like "first," "next," and "finally"?', type: 'multiple-choice', options: ['Cause and effect', 'Compare and contrast', 'Chronological order', 'Problem and solution'], correctAnswer: 'Chronological order', hint: 'These words describe the order events happen in.', explanation: 'Words like "first," "next," and "finally" show the order of events over time, which is the chronological text structure.', standardCode: '4.RI.5' },
        { index: 1, question: '"Many students were struggling with math. The school started an after-school tutoring program, and test scores improved." What text structure is this?', type: 'multiple-choice', options: ['Description', 'Chronological order', 'Compare and contrast', 'Problem and solution'], correctAnswer: 'Problem and solution', hint: 'First a problem is described, then a solution is given.', explanation: 'The passage presents a problem (students struggling) and a solution (tutoring program). The result (improved scores) shows the solution worked.', standardCode: '4.RI.5' },
        { index: 2, question: 'An author writes an article full of facts about how volcanoes erupt. What is the author\'s purpose?', type: 'multiple-choice', options: ['To persuade', 'To entertain', 'To inform', 'To confuse'], correctAnswer: 'To inform', hint: 'The author is giving factual information and explanations.', explanation: 'When an author provides facts and explanations about a topic, their purpose is to inform — to teach the reader something new.', standardCode: '4.RI.5' },
        { index: 3, question: 'What signal words would you expect in a cause and effect passage?', type: 'short-answer', correctAnswer: 'Words like "because," "since," "so," "therefore," "as a result," and "due to."', hint: 'These words explain why something happened or what happened next.', explanation: 'Cause and effect signal words include "because," "since," "so," "therefore," "as a result," and "due to." They connect a cause (reason) to its effect (result).', standardCode: '4.RI.5' },
        { index: 4, question: 'Why might an author who wants to persuade readers to recycle choose a problem and solution text structure?', type: 'short-answer', correctAnswer: 'The author can describe pollution and overflowing landfills as the problem, then present recycling as the solution, making readers see why they should recycle.', hint: 'Think about how showing a problem first makes the solution more convincing.', explanation: 'Problem and solution structure works well for persuasion because showing the problem first makes the reader care, and then the solution (recycling) feels necessary and convincing.', standardCode: '4.RI.5' },
      ],
      assessment: {
        questions: [
          { question: '"Dogs and cats are both popular pets. However, dogs need more outdoor exercise while cats are usually happy indoors." What text structure is used?', type: 'multiple-choice', options: ['Chronological order', 'Compare and contrast', 'Problem and solution', 'Cause and effect'], correctAnswer: 'Compare and contrast', standardCode: '4.RI.5' },
          { question: 'What are the three main purposes an author may have for writing?', type: 'short-answer', correctAnswer: 'To inform, to persuade, and to entertain.', standardCode: '4.RI.5' },
          { question: 'Which signal word indicates a cause and effect relationship?', type: 'multiple-choice', options: ['However', 'First', 'Because', 'Similarly'], correctAnswer: 'Because', standardCode: '4.RI.5' },
        ],
      },
    },
  },
  {
    slug: 'grade4-ela-writing-drafting-revising',
    title: 'Writing: Drafting and Revising',
    description: 'Write narratives, informational texts, and opinion pieces, and strengthen writing through drafting and revising',
    subject: 'ela',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Writing',
    standardCodes: ['4.W.1', '4.W.2', '4.W.3'],
    content: {
      intro: {
        title: 'Writing: Drafting and Revising',
        text: 'Good writing does not happen in one try. Real writers plan, draft, and revise their work to make it better. In fourth grade, you will write three types of pieces: narratives that tell a story, informational texts that teach about a topic, and opinion pieces that share what you think. Let us learn how to draft and revise each one!',
        culturalHook: 'Think about a time you told a friend about something important. You probably tried different ways to explain it until it made sense — that is what revising is like!',
      },
      segments: [
        {
          index: 0,
          title: 'Narrative Writing',
          text: 'A narrative tells a story, real or imagined. Good narratives have a clear beginning that introduces characters and the setting. The middle includes a problem or challenge and events that build toward a solution. The ending wraps up the story and often shows what the character learned. Use descriptive details to bring your story to life — describe what characters see, hear, feel, and think. Include dialogue to let characters speak in their own voices. Transition words like "later that day," "suddenly," and "after a while" help the events flow smoothly from one to the next.',
          keyVocabulary: ['narrative', 'dialogue', 'descriptive details', 'transition words'],
          example: '"The wind howled as Mia stepped outside. She pulled her jacket tighter and whispered, I can do this." — This uses descriptive details and dialogue.',
        },
        {
          index: 1,
          title: 'Informational Writing',
          text: 'Informational writing teaches the reader about a topic. Start with an introduction that names your topic and hooks the reader with an interesting fact or question. Organize the body into paragraphs, each covering one subtopic. Use facts, definitions, and examples to explain your ideas clearly. End with a conclusion that restates the main point. Linking words like "for example," "also," "in addition," and "in fact" help connect your ideas. Use precise vocabulary — the specific words related to your topic. If writing about weather, use words like "precipitation," "humidity," and "atmosphere" instead of vague terms.',
          keyVocabulary: ['informational', 'subtopic', 'precise vocabulary', 'linking words'],
        },
        {
          index: 2,
          title: 'Opinion Writing',
          text: 'Opinion writing shares your point of view and tries to convince the reader to agree. Begin by clearly stating your opinion. Then provide reasons that support it, organized from least to most important or in another logical order. Back up each reason with evidence — facts, examples, or experiences. Use persuasive words like "I believe," "clearly," "most importantly," and "for this reason." End with a strong conclusion that restates your opinion and leaves the reader thinking. Remember, a strong opinion piece respects other viewpoints even while disagreeing.',
          keyVocabulary: ['opinion', 'reasons', 'persuasive', 'point of view', 'evidence'],
        },
        {
          index: 3,
          title: 'Drafting and Revising',
          text: 'Drafting means writing your first version. Do not worry about making it perfect — just get your ideas on paper. Revising means going back to improve your writing. When you revise, check for these things: Are my ideas clear and in a logical order? Did I include enough details and evidence? Do my sentences flow smoothly with transition words? Is my opening interesting and my ending strong? Can I replace weak words with stronger ones? Read your writing out loud — your ear will catch problems your eyes might miss. You can also ask a classmate to read your work and give feedback. Revising is what turns a good draft into a great final piece.',
          keyVocabulary: ['drafting', 'revising', 'feedback', 'logical order'],
        },
      ],
      practice: [
        { index: 0, question: 'What are the three types of writing fourth graders should practice?', type: 'multiple-choice', options: ['Poetry, drama, and comics', 'Narrative, informational, and opinion', 'Fiction, mystery, and fantasy', 'Spelling, grammar, and punctuation'], correctAnswer: 'Narrative, informational, and opinion', hint: 'These three types cover storytelling, teaching, and persuading.', explanation: 'Fourth graders focus on three core writing types: narratives (stories), informational texts (teaching about a topic), and opinion pieces (sharing and supporting a point of view).', standardCode: '4.W.3' },
        { index: 1, question: 'Which of these is an example of a strong opinion statement?', type: 'multiple-choice', options: ['Cats exist in many countries.', 'I believe recess should be longer because students need more time to exercise and recharge.', 'Some people like pizza.', 'The weather is nice today.'], correctAnswer: 'I believe recess should be longer because students need more time to exercise and recharge.', hint: 'A strong opinion statement clearly states a belief and gives a reason.', explanation: 'This statement clearly shares an opinion ("recess should be longer") and provides a supporting reason ("students need more time to exercise and recharge"). The other choices are facts or vague statements.', standardCode: '4.W.1' },
        { index: 2, question: 'What is the difference between drafting and revising?', type: 'short-answer', correctAnswer: 'Drafting is writing your first version to get ideas on paper, while revising is going back to improve the writing by making ideas clearer, adding details, and fixing organization.', hint: 'One is about getting started; the other is about making it better.', explanation: 'Drafting focuses on getting your ideas down without worrying about perfection. Revising focuses on improving what you wrote — clarifying ideas, adding evidence, improving word choice, and reorganizing if needed.', standardCode: '4.W.3' },
        { index: 3, question: 'In informational writing, why should you use precise vocabulary?', type: 'multiple-choice', options: ['To confuse the reader', 'To make your writing longer', 'To clearly and accurately explain your topic', 'To show off big words'], correctAnswer: 'To clearly and accurately explain your topic', hint: 'Precise words help the reader understand exactly what you mean.', explanation: 'Precise vocabulary uses the correct terms for your topic, making your explanations clearer and more accurate. It helps the reader learn and understand the subject better.', standardCode: '4.W.2' },
        { index: 4, question: 'What is one helpful strategy for finding problems in your writing during revision?', type: 'short-answer', correctAnswer: 'Read your writing out loud. Your ear will catch awkward sentences, missing words, and unclear ideas that your eyes might miss.', hint: 'It involves using more than just your eyes to check your work.', explanation: 'Reading aloud is a powerful revision strategy because hearing your words helps you notice places where the writing sounds choppy, confusing, or incomplete. You can also have a peer read your work and give feedback.', standardCode: '4.W.3' },
      ],
      assessment: {
        questions: [
          { question: 'What should a narrative include in its beginning?', type: 'multiple-choice', options: ['The solution to the problem', 'The characters and setting', 'A list of facts', 'The author\'s opinion'], correctAnswer: 'The characters and setting', standardCode: '4.W.3' },
          { question: 'In opinion writing, what should you provide to support each reason?', type: 'short-answer', correctAnswer: 'Evidence such as facts, examples, or personal experiences.', standardCode: '4.W.1' },
          { question: 'What does revising your writing involve?', type: 'multiple-choice', options: ['Writing a brand new piece from scratch', 'Only fixing spelling errors', 'Improving ideas, details, organization, and word choice', 'Making the paper shorter'], correctAnswer: 'Improving ideas, details, organization, and word choice', standardCode: '4.W.3' },
        ],
      },
    },
  },
  {
    slug: 'grade4-ela-using-evidence-from-text',
    title: 'Using Evidence from Text',
    description: 'Refer to details and examples in a text when explaining what the text says explicitly and when drawing inferences',
    subject: 'ela',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Reading Informational',
    standardCodes: ['4.RI.1'],
    content: {
      intro: {
        title: 'Using Evidence from Text',
        text: 'When you answer questions about what you read, you need to show where your answer came from. That means pointing to specific details and examples in the text. This skill is called using text evidence, and it makes your answers stronger and more convincing.',
        culturalHook: 'Imagine a friend tells you something surprising. You would probably ask, "How do you know?" Text evidence is how readers prove what they know.',
      },
      segments: [
        {
          index: 0,
          title: 'What Is Text Evidence?',
          text: 'Text evidence is information you find directly in the reading that supports your answer or idea. It can be a specific detail, a fact, a quote, or an example the author included. When someone asks you a question about a passage, you should be able to point to the exact sentence or detail that backs up your answer. Think of it like a detective gathering clues — every answer needs proof, and the proof is right there in the text. Without evidence, your answer is just a guess.',
          keyVocabulary: ['text evidence', 'detail', 'fact', 'quote', 'support'],
        },
        {
          index: 1,
          title: 'Explicit vs. Inferential Questions',
          text: 'Some questions are explicit — the answer is stated directly in the text and you can point right to it. For example, "What color was the barn?" might be answered by a sentence that says, "The red barn stood on the hill." Other questions require an inference — you combine clues from the text with your own thinking to figure out something the author did not say directly. Even when you make an inference, you still need text evidence to support it. The difference is that explicit answers are right there on the page, while inferences require you to read between the lines.',
          keyVocabulary: ['explicit', 'inference', 'clues', 'read between the lines'],
          example: 'Explicit: "The article states that dolphins live in pods." Inference: "The author mentions the dolphin called to others and they came quickly, which suggests dolphins communicate well."',
        },
        {
          index: 2,
          title: 'How to Cite Evidence in Your Answer',
          text: 'When you use evidence in a written answer, introduce it with phrases like "According to the text," "The author states," "In paragraph two," or "For example, the text says." Then include the detail or quote that supports your point. After giving the evidence, explain how it connects to your answer. A strong response follows this pattern: state your answer, provide the evidence, and then explain how the evidence proves your point. This is sometimes called the ACE strategy — Answer, Cite, Explain.',
          keyVocabulary: ['cite', 'according to', 'ACE strategy', 'explain'],
        },
      ],
      practice: [
        { index: 0, question: 'What is text evidence?', type: 'multiple-choice', options: ['Your personal opinion about the text', 'Information found directly in the reading that supports your answer', 'A guess about what the author meant', 'The title of the passage'], correctAnswer: 'Information found directly in the reading that supports your answer', hint: 'Evidence is proof — it comes from the text itself.', explanation: 'Text evidence is specific information (facts, details, quotes) from the passage that you use to support or prove your answer.', standardCode: '4.RI.1' },
        { index: 1, question: 'What is the difference between an explicit question and an inferential question?', type: 'short-answer', correctAnswer: 'An explicit question has the answer stated directly in the text, while an inferential question requires you to use clues from the text along with your own thinking to figure out the answer.', hint: 'One answer is right there on the page; the other requires you to think deeper.', explanation: 'Explicit answers can be found word-for-word in the text. Inferential answers require combining text clues with reasoning to reach a conclusion not directly stated.', standardCode: '4.RI.1' },
        { index: 2, question: 'Which phrase is a good way to introduce text evidence in your answer?', type: 'multiple-choice', options: ['I think maybe...', 'According to the text...', 'I feel like...', 'Everybody knows that...'], correctAnswer: 'According to the text...', hint: 'Look for the phrase that signals you are referring to what you read.', explanation: '"According to the text" tells the reader you are about to share evidence directly from the passage, which makes your answer stronger and more credible.', standardCode: '4.RI.1' },
        { index: 3, question: 'What does the ACE strategy stand for?', type: 'short-answer', correctAnswer: 'ACE stands for Answer, Cite, Explain. You state your answer, cite evidence from the text, and explain how the evidence supports your answer.', hint: 'Each letter represents a step in writing a strong response.', explanation: 'The ACE strategy is a framework for writing text-based responses: Answer the question, Cite evidence from the text, and Explain how the evidence connects to your answer.', standardCode: '4.RI.1' },
        { index: 4, question: 'A passage says: "Sea turtles travel thousands of miles to return to the same beach where they were born to lay their eggs." A student writes: "Sea turtles have amazing navigation skills." Is this an explicit statement or an inference?', type: 'multiple-choice', options: ['Explicit — it is stated directly in the text', 'Inference — the student figured it out from clues in the text'], correctAnswer: 'Inference — the student figured it out from clues in the text', hint: 'Does the passage use the words "amazing navigation skills"?', explanation: 'The passage does not say "navigation skills" directly. The student inferred that traveling thousands of miles back to the same beach requires amazing navigation, using the text detail as a clue.', standardCode: '4.RI.1' },
      ],
      assessment: {
        questions: [
          { question: 'Why is it important to use text evidence when answering questions about a passage?', type: 'short-answer', correctAnswer: 'Text evidence proves that your answer is based on what the author actually wrote, not just a guess. It makes your answer stronger and more convincing.', standardCode: '4.RI.1' },
          { question: 'Which step comes last in the ACE strategy?', type: 'multiple-choice', options: ['Answer', 'Cite', 'Explain', 'Predict'], correctAnswer: 'Explain', standardCode: '4.RI.1' },
          { question: 'If a question asks "What can you conclude about the character based on her actions?" is it an explicit or inferential question?', type: 'multiple-choice', options: ['Explicit', 'Inferential'], correctAnswer: 'Inferential', standardCode: '4.RI.1' },
        ],
      },
    },
  },
  {
    slug: 'grade4-ela-comparing-points-of-view',
    title: 'Comparing Points of View',
    description: 'Compare and contrast the point of view from which different stories are narrated, including first-person and third-person narrations',
    subject: 'ela',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Reading Literature',
    standardCodes: ['4.RL.6'],
    content: {
      intro: {
        title: 'Comparing Points of View',
        text: 'Every story is told by someone — a narrator. The narrator\'s point of view shapes how you experience the story. Some stories use "I" and "me" because the narrator is a character in the story. Other stories use "he," "she," or "they" because the narrator is outside the story looking in. Understanding these differences helps you think about why the author chose a particular point of view.',
      },
      segments: [
        {
          index: 0,
          title: 'First-Person Point of View',
          text: 'In first-person narration, a character in the story is telling it. You will see words like "I," "me," "my," and "we." The narrator shares their own thoughts, feelings, and experiences. Because the narrator is inside the story, you only know what that character knows. You see everything through their eyes. This can make the story feel very personal and close. However, the narrator might not know everything that is happening — they can only share their own perspective. If another character is upset, the first-person narrator can only guess why unless that character tells them.',
          keyVocabulary: ['first-person', 'narrator', 'perspective', 'personal'],
          example: '"I walked into the classroom and felt my stomach flip. Everyone was staring at me." — The narrator tells you directly how they feel.',
        },
        {
          index: 1,
          title: 'Third-Person Point of View',
          text: 'In third-person narration, the narrator is not a character in the story. They refer to characters by name or use "he," "she," "it," or "they." A third-person narrator can describe what different characters do and sometimes what they think or feel. This is called third-person omniscient — the narrator knows everything. Sometimes the third-person narrator only follows one character closely, which is called third-person limited. Third-person narration lets you see the bigger picture of the story because you are not locked inside one character\'s head.',
          keyVocabulary: ['third-person', 'omniscient', 'limited', 'narrator'],
          example: '"Jada walked into the classroom. Her stomach flipped. She didn\'t know that her classmates were planning a surprise party." — The narrator knows what Jada feels and what others are doing.',
        },
        {
          index: 2,
          title: 'Comparing First-Person and Third-Person',
          text: 'When you compare first-person and third-person narrations, think about what each point of view lets you know and what it hides. First-person gives you deep access to one character\'s thoughts but limits what you know about other characters. Third-person can show you multiple characters\' thoughts and actions. The same event can feel very different depending on who is telling the story. A first-person narrator might say, "I was terrified," while a third-person narrator might describe the scene more broadly: "The room fell silent as everyone watched." Consider how the choice of narrator affects the mood, the information you receive, and how close you feel to the characters.',
          keyVocabulary: ['compare', 'mood', 'information', 'closeness'],
        },
        {
          index: 3,
          title: 'Why Authors Choose a Point of View',
          text: 'Authors pick a point of view for a reason. If they want the reader to connect deeply with one character\'s emotions, they might choose first person. If they want the reader to understand a situation from many angles, they might choose third person. When you read, ask yourself: Why did the author choose this narrator? How would the story be different if it were told from another point of view? Thinking about these questions makes you a more thoughtful reader. You can even try rewriting a short scene from a different point of view to see how it changes the story.',
          keyVocabulary: ['author\'s choice', 'connect', 'angles', 'thoughtful reader'],
        },
      ],
      practice: [
        { index: 0, question: 'Which words tell you a story is written in first-person point of view?', type: 'multiple-choice', options: ['He, she, they', 'I, me, my', 'It, the character, one', 'You, your, yours'], correctAnswer: 'I, me, my', hint: 'First-person means the narrator is talking about themselves.', explanation: 'First-person narration uses pronouns like "I," "me," "my," and "we" because the narrator is a character inside the story sharing their own experience.', standardCode: '4.RL.6' },
        { index: 1, question: '"Marcus looked out the window and sighed. He wished the rain would stop so he could play outside." What point of view is this?', type: 'multiple-choice', options: ['First person', 'Second person', 'Third person', 'No point of view'], correctAnswer: 'Third person', hint: 'Look at the pronouns used. Is the narrator a character in the story?', explanation: 'The passage uses "he" and "Marcus" rather than "I" or "me," which means the narrator is outside the story. This is third-person point of view.', standardCode: '4.RL.6' },
        { index: 2, question: 'What is one advantage of first-person narration?', type: 'short-answer', correctAnswer: 'It lets the reader closely experience one character\'s thoughts and feelings, making the story feel personal and immediate.', hint: 'Think about what you gain by being inside a character\'s head.', explanation: 'First-person narration creates a strong personal connection because you experience everything through the narrator\'s eyes, hearing their inner thoughts and emotions directly.', standardCode: '4.RL.6' },
        { index: 3, question: 'What is one limitation of first-person narration?', type: 'multiple-choice', options: ['It is always boring', 'The narrator can only share their own perspective and does not know everything', 'It cannot include dialogue', 'It has to be nonfiction'], correctAnswer: 'The narrator can only share their own perspective and does not know everything', hint: 'What can a first-person narrator NOT do?', explanation: 'A first-person narrator is limited to their own knowledge and perspective. They cannot tell you what other characters are thinking or what is happening in places they are not present.', standardCode: '4.RL.6' },
        { index: 4, question: 'How might the same event feel different when told in first person vs. third person?', type: 'short-answer', correctAnswer: 'In first person, you feel the character\'s emotions directly and experience the event through their eyes. In third person, you see the event from the outside, which can give a broader picture but may feel less personal.', hint: 'Think about the difference between watching something happen and living through it.', explanation: 'First person immerses the reader in one character\'s experience. Third person offers a wider view. The same event — like winning a race — feels personal and thrilling in first person ("I crossed the finish line!") but more observed in third person ("She crossed the finish line as the crowd cheered.").', standardCode: '4.RL.6' },
      ],
      assessment: {
        questions: [
          { question: '"I never expected to find a treasure map in my grandmother\'s attic." What point of view is this?', type: 'multiple-choice', options: ['First person', 'Third person limited', 'Third person omniscient', 'Second person'], correctAnswer: 'First person', standardCode: '4.RL.6' },
          { question: 'Why might an author choose third-person narration for a story with many important characters?', type: 'short-answer', correctAnswer: 'Third-person narration allows the author to show what different characters think, feel, and do, giving the reader a fuller understanding of the story from multiple perspectives.', standardCode: '4.RL.6' },
          { question: 'What does "third-person omniscient" mean?', type: 'multiple-choice', options: ['The narrator is a character in the story', 'The narrator knows only one character\'s thoughts', 'The narrator knows the thoughts and feelings of all characters', 'The narrator speaks directly to the reader'], correctAnswer: 'The narrator knows the thoughts and feelings of all characters', standardCode: '4.RL.6' },
        ],
      },
    },
  },
  {
    slug: 'grade4-ela-integrating-information-two-texts',
    title: 'Integrating Information from Two Texts',
    description: 'Integrate information from two texts on the same topic in order to write or speak about the subject knowledgeably',
    subject: 'ela',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Reading Informational',
    standardCodes: ['4.RI.9'],
    content: {
      intro: {
        title: 'Integrating Information from Two Texts',
        text: 'Sometimes you need to read more than one source to really understand a topic. Different texts might share some of the same information, but each one can also teach you something new. Learning to combine information from two texts makes you a stronger researcher and a more knowledgeable writer and speaker.',
      },
      segments: [
        {
          index: 0,
          title: 'Why Read Two Texts on the Same Topic?',
          text: 'No single text tells you everything about a topic. One article about sharks might focus on what they eat, while another might explain where they live and how they are endangered. By reading both, you get a more complete picture. Reading two sources also helps you check facts. If both texts say the same thing, you can be more confident that information is accurate. If they disagree, you can investigate further. Good researchers always look at more than one source before drawing conclusions.',
          keyVocabulary: ['source', 'complete picture', 'accurate', 'researcher'],
        },
        {
          index: 1,
          title: 'Finding What Is the Same and What Is Different',
          text: 'After reading two texts on the same topic, identify what information they share and what is unique to each one. You might make a simple chart with three columns: "Text 1 Only," "Both Texts," and "Text 2 Only." Shared information goes in the middle. Facts or details found in only one text go in the appropriate column. This helps you see the full range of information available and notice where the texts overlap and where they add new ideas. Pay attention to whether the texts agree on key facts or present different perspectives on the same issue.',
          keyVocabulary: ['overlap', 'unique', 'chart', 'perspectives'],
          example: 'Text 1 says pandas eat bamboo. Text 2 says pandas eat bamboo and occasionally small animals. Both agree on bamboo, but Text 2 adds new information.',
        },
        {
          index: 2,
          title: 'Combining Information in Your Own Words',
          text: 'Once you have gathered information from both texts, combine it into your own writing or presentation. Do not simply copy sentences from each text. Instead, blend the facts together in your own words. For example, instead of pasting two separate facts, you might write: "According to both sources, pandas mainly eat bamboo, but one source explains that they sometimes eat small animals as well." Use phrases like "both texts explain," "one source adds," and "while one article focuses on... the other describes..." to show that you are synthesizing information from multiple places. This skill is called integrating information.',
          keyVocabulary: ['combine', 'synthesize', 'integrate', 'blend'],
        },
      ],
      practice: [
        { index: 0, question: 'Why is it helpful to read two texts on the same topic instead of just one?', type: 'short-answer', correctAnswer: 'Reading two texts gives you a more complete understanding of the topic because each text may include different facts, details, or perspectives that the other one does not.', hint: 'Think about what you might miss if you only read one source.', explanation: 'A single text cannot cover everything. Two texts together provide more facts, different angles, and allow you to verify information by seeing if both sources agree.', standardCode: '4.RI.9' },
        { index: 1, question: 'What should you do if two texts on the same topic present different facts?', type: 'multiple-choice', options: ['Ignore both texts', 'Only believe the longer text', 'Investigate further to find out which information is accurate', 'Assume both are wrong'], correctAnswer: 'Investigate further to find out which information is accurate', hint: 'Good researchers check their sources carefully.', explanation: 'When texts disagree, a good reader investigates further — perhaps by reading a third source — to determine which information is accurate rather than blindly trusting one over the other.', standardCode: '4.RI.9' },
        { index: 2, question: 'What is a useful tool for organizing information from two texts?', type: 'multiple-choice', options: ['A timeline', 'A chart with columns for Text 1 Only, Both Texts, and Text 2 Only', 'A dictionary', 'An index'], correctAnswer: 'A chart with columns for Text 1 Only, Both Texts, and Text 2 Only', hint: 'You need a tool that shows shared and unique information.', explanation: 'A three-column chart helps you visually organize which information is shared by both texts and which is unique to each one, making it easier to integrate the information.', standardCode: '4.RI.9' },
        { index: 3, question: 'What does it mean to "integrate" information from two texts?', type: 'short-answer', correctAnswer: 'It means to combine information from both texts together in your own words to create a more complete understanding of the topic.', hint: 'Think about bringing two sets of information together.', explanation: 'Integrating information means blending facts and ideas from multiple sources into a unified understanding, expressed in your own words rather than copying from either text.', standardCode: '4.RI.9' },
        { index: 4, question: 'Which phrase helps show that you are using information from more than one source?', type: 'multiple-choice', options: ['I think...', 'In my opinion...', 'Both texts explain...', 'Once upon a time...'], correctAnswer: 'Both texts explain...', hint: 'Look for the phrase that references multiple sources.', explanation: '"Both texts explain" signals to the reader that you gathered your information from two sources, which is a key part of integrating information from multiple texts.', standardCode: '4.RI.9' },
      ],
      assessment: {
        questions: [
          { question: 'Text A says bald eagles build nests near rivers. Text B says bald eagles build nests near rivers and lakes. How would you integrate this information?', type: 'short-answer', correctAnswer: 'Both sources agree that bald eagles build nests near rivers, and one source adds that they also build nests near lakes. Together, the texts show that bald eagles prefer nesting near bodies of water.', standardCode: '4.RI.9' },
          { question: 'What goes in the middle column of a comparison chart for two texts?', type: 'multiple-choice', options: ['Information found only in Text 1', 'Information found only in Text 2', 'Information found in both texts', 'Your personal opinions'], correctAnswer: 'Information found in both texts', standardCode: '4.RI.9' },
          { question: 'When combining information from two texts, should you copy sentences directly?', type: 'multiple-choice', options: ['Yes, always copy word for word', 'No, you should blend the facts in your own words', 'Only copy from the shorter text', 'Only copy from the first text'], correctAnswer: 'No, you should blend the facts in your own words', standardCode: '4.RI.9' },
        ],
      },
    },
  },
  {
    slug: 'grade4-ela-greek-and-latin-word-parts',
    title: 'Greek and Latin Word Parts',
    description: 'Use common Greek and Latin affixes and roots as clues to the meaning of words',
    subject: 'ela',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Language',
    standardCodes: ['4.L.4b'],
    content: {
      intro: {
        title: 'Greek and Latin Word Parts',
        text: 'Many English words are built from parts that come from ancient Greek and Latin. If you learn these word parts, you can figure out the meaning of new words — even words you have never seen before. It is like having a secret code for unlocking vocabulary!',
        culturalHook: 'Languages borrow from each other all the time. English has borrowed thousands of words from Greek and Latin, just like it borrows words from Spanish, Arabic, and many other languages.',
      },
      segments: [
        {
          index: 0,
          title: 'Prefixes, Roots, and Suffixes',
          text: 'Words can be broken into parts. A root is the core part of a word that carries the main meaning. A prefix is a word part added to the beginning that changes the meaning. A suffix is a word part added to the end that changes the meaning or the part of speech. For example, in the word "unhelpful," "help" is the root, "un-" is the prefix meaning "not," and "-ful" is the suffix meaning "full of." When you see an unfamiliar word, try breaking it into parts. If you know what the parts mean, you can figure out the whole word.',
          keyVocabulary: ['prefix', 'root', 'suffix', 'core meaning'],
        },
        {
          index: 1,
          title: 'Common Latin Roots and Prefixes',
          text: 'Many everyday English words have Latin roots. The root "aud" means "to hear," which appears in "audience" and "audio." The root "vis" or "vid" means "to see," found in "visible" and "video." The root "scrib" or "script" means "to write," as in "describe" and "manuscript." Common Latin prefixes include "pre-" meaning "before" (preview, predict), "re-" meaning "again" (rewrite, return), "dis-" meaning "not" or "apart" (disagree, disconnect), and "sub-" meaning "under" (submarine, subway). Knowing these parts helps you decode words you encounter in reading.',
          keyVocabulary: ['aud', 'vis', 'scrib', 'pre-', 're-', 'dis-', 'sub-'],
          example: '"Predict" = "pre-" (before) + "dict" (say) = to say before it happens, or to guess what will happen.',
        },
        {
          index: 2,
          title: 'Common Greek Roots and Prefixes',
          text: 'Greek roots appear in many science and academic words. The root "bio" means "life," as in "biology" and "biography." The root "graph" means "to write" or "writing," found in "paragraph" and "autograph." The root "tele" means "far," as in "telephone" and "television." The root "auto" means "self," giving us "automobile" and "autobiography." Greek prefixes include "micro-" meaning "small" (microscope, microphone) and "photo-" meaning "light" (photograph, photosynthesis). When you encounter a long word in science class, look for Greek roots — they are often the key to understanding it.',
          keyVocabulary: ['bio', 'graph', 'tele', 'auto', 'micro-', 'photo-'],
        },
        {
          index: 3,
          title: 'Using Word Parts to Figure Out New Words',
          text: 'When you come across an unknown word, follow these steps. First, look for any familiar word parts — a prefix, root, or suffix you recognize. Second, think about what each part means. Third, combine the meanings to make a guess about the whole word. Fourth, check if your guess makes sense in the sentence. For example, if you see the word "inaudible," you might recognize "in-" (not) and "aud" (hear) and "-ible" (able to be). Put them together: "not able to be heard." Check the sentence: "The whisper was inaudible from across the room." That makes sense! This strategy works for hundreds of words.',
          keyVocabulary: ['unknown word', 'combine', 'strategy', 'context'],
        },
      ],
      practice: [
        { index: 0, question: 'What is a root word?', type: 'multiple-choice', options: ['A word part added to the beginning', 'The core part of a word that carries the main meaning', 'A word part added to the end', 'The whole word itself'], correctAnswer: 'The core part of a word that carries the main meaning', hint: 'Think of it as the foundation that other parts are built around.', explanation: 'The root is the central part of a word that holds the main meaning. Prefixes and suffixes are added to roots to create new words.', standardCode: '4.L.4b' },
        { index: 1, question: 'The prefix "re-" means "again." What does "rewrite" mean?', type: 'multiple-choice', options: ['Write for the first time', 'Write again', 'Stop writing', 'Write quickly'], correctAnswer: 'Write again', hint: 'Combine the prefix meaning with the root word.', explanation: '"Re-" means "again" and "write" means to put words on paper. Together, "rewrite" means to write something again.', standardCode: '4.L.4b' },
        { index: 2, question: 'The root "bio" means "life." What do you think "biography" means?', type: 'short-answer', correctAnswer: 'A biography is the written story of someone\'s life. "Bio" means life and "graph" means writing, so a biography is a writing about a life.', hint: '"Graph" means writing or something written. Combine it with "bio."', explanation: '"Bio" (life) + "graph" (writing) = a written account of someone\'s life. Knowing both roots helps you figure out the meaning.', standardCode: '4.L.4b' },
        { index: 3, question: 'If "sub-" means "under" and "marine" relates to the sea, what is a submarine?', type: 'multiple-choice', options: ['A boat that floats on top of the water', 'A vehicle that goes under the sea', 'A type of fish', 'A beach on a hill'], correctAnswer: 'A vehicle that goes under the sea', hint: 'Put the two meanings together: under + sea.', explanation: '"Sub-" (under) + "marine" (sea) = something that goes under the sea. A submarine is a vessel designed to travel underwater.', standardCode: '4.L.4b' },
        { index: 4, question: 'You see the word "microscope" for the first time. "Micro-" means "small" and "scope" means "to look at." What do you think a microscope does?', type: 'short-answer', correctAnswer: 'A microscope lets you look at very small things. "Micro" means small and "scope" means to look at, so it is a tool for looking at small objects.', hint: 'Combine both word parts: small + look at.', explanation: '"Micro-" (small) + "scope" (to look at) = a tool for looking at small things. Microscopes magnify tiny objects so we can see them clearly.', standardCode: '4.L.4b' },
      ],
      assessment: {
        questions: [
          { question: 'The prefix "dis-" means "not" or "apart." What does "disagree" mean?', type: 'multiple-choice', options: ['To agree strongly', 'To not agree', 'To agree again', 'To agree later'], correctAnswer: 'To not agree', standardCode: '4.L.4b' },
          { question: 'If "tele" means "far" and "phone" means "sound," explain what "telephone" means using the word parts.', type: 'short-answer', correctAnswer: 'A telephone is a device for sending sound far away. "Tele" means far and "phone" means sound, so it is a far-sound device that lets people talk over long distances.', standardCode: '4.L.4b' },
          { question: 'Which word most likely means "to write before"?', type: 'multiple-choice', options: ['Prescribe', 'Describe', 'Subscribe', 'Manuscript'], correctAnswer: 'Prescribe', standardCode: '4.L.4b' },
        ],
      },
    },
  },
  {
    slug: 'grade4-ela-writing-informational-texts',
    title: 'Writing Informational Texts with Structure',
    description: 'Write informative and explanatory texts to examine a topic and convey ideas and information clearly with organization',
    subject: 'ela',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Writing',
    standardCodes: ['4.W.2'],
    content: {
      intro: {
        title: 'Writing Informational Texts with Structure',
        text: 'Informational writing teaches your reader about a topic you know well. The best informational writing is organized clearly so the reader can follow your ideas from beginning to end. Today we will learn how to structure an informational text with a strong introduction, organized body paragraphs, and a solid conclusion.',
      },
      segments: [
        {
          index: 0,
          title: 'Writing a Strong Introduction',
          text: 'The introduction is the first part of your informational text. It should do two things: name your topic and grab the reader\'s attention. You can hook the reader with a surprising fact, an interesting question, or a vivid description. After the hook, clearly state what your text will be about. This is sometimes called a focus statement or thesis. For example, if your topic is honeybees, you might write: "Did you know that a single honeybee visits about 2,000 flowers every day? Honeybees are some of the hardest-working and most important insects on the planet." The reader now knows the topic and is interested to learn more.',
          keyVocabulary: ['introduction', 'hook', 'focus statement', 'thesis'],
          example: 'Hook: "Imagine a world without chocolate, apples, or almonds." Focus statement: "Without bees to pollinate crops, many of our favorite foods would disappear."',
        },
        {
          index: 1,
          title: 'Organizing Body Paragraphs',
          text: 'The body of your informational text is where you share your facts, details, and explanations. Each body paragraph should focus on one subtopic or one big idea. Start each paragraph with a topic sentence that tells the reader what that paragraph is about. Then add supporting details — facts, definitions, examples, or explanations. Use linking words to connect your ideas: "for example," "in addition," "also," "another reason," and "as a result." End each paragraph with a closing sentence that wraps up that subtopic. If you are writing about honeybees, one paragraph might cover what bees eat, another might explain how pollination works, and a third might discuss threats to bee populations.',
          keyVocabulary: ['body paragraph', 'subtopic', 'topic sentence', 'supporting details', 'linking words'],
        },
        {
          index: 2,
          title: 'Using Facts and Precise Language',
          text: 'Strong informational writing uses facts, not opinions. Instead of writing "bees are cool," write "bees pollinate approximately 80 percent of all flowering plants." Use precise, specific vocabulary related to your topic. If writing about weather, use words like "precipitation," "atmosphere," and "evaporation" rather than vague language. When you include a fact or statistic, make sure it is accurate. You can get information from books, articles, and reliable websites. Avoid guessing. Using precise language and verified facts makes your writing credible and helps your reader learn real information.',
          keyVocabulary: ['facts', 'precise language', 'credible', 'specific vocabulary', 'statistic'],
        },
        {
          index: 3,
          title: 'Writing a Conclusion',
          text: 'The conclusion is the last part of your informational text. It wraps up your writing and leaves the reader with something to remember. A strong conclusion restates the main idea in a fresh way — do not just copy your introduction. Summarize the most important points briefly. You can end with a thought-provoking question, a call to action, or an interesting final fact. For example: "Honeybees may be small, but their impact on our food supply is enormous. The next time you bite into an apple, thank a bee." A good conclusion gives the reader a sense of completion and reinforces the key information.',
          keyVocabulary: ['conclusion', 'restate', 'summarize', 'call to action', 'thought-provoking'],
        },
      ],
      practice: [
        { index: 0, question: 'What two things should an introduction do?', type: 'short-answer', correctAnswer: 'An introduction should name the topic and grab the reader\'s attention with a hook such as a surprising fact, a question, or a vivid description.', hint: 'Think about what makes a reader want to keep reading.', explanation: 'The introduction serves two purposes: it tells the reader what the text will be about (names the topic) and draws them in with an engaging opening (the hook).', standardCode: '4.W.2' },
        { index: 1, question: 'What should each body paragraph begin with?', type: 'multiple-choice', options: ['A question for the reader', 'A topic sentence that tells what the paragraph is about', 'The conclusion of the essay', 'A definition from the dictionary'], correctAnswer: 'A topic sentence that tells what the paragraph is about', hint: 'The first sentence of a body paragraph sets up what comes next.', explanation: 'A topic sentence introduces the main idea of that paragraph, helping the reader know what information to expect in the sentences that follow.', standardCode: '4.W.2' },
        { index: 2, question: 'Why is it important to use facts instead of opinions in informational writing?', type: 'short-answer', correctAnswer: 'Facts provide accurate, verifiable information that helps the reader learn. Opinions are personal beliefs that do not teach the reader new information and are not appropriate for informational texts.', hint: 'Think about the purpose of informational writing — to teach.', explanation: 'Informational writing aims to educate. Facts are reliable and can be verified, making the writing trustworthy. Opinions belong in opinion writing, not informational texts.', standardCode: '4.W.2' },
        { index: 3, question: 'Which linking word helps add another detail to a paragraph?', type: 'multiple-choice', options: ['However', 'In conclusion', 'In addition', 'On the other hand'], correctAnswer: 'In addition', hint: 'Look for the phrase that signals more information is coming.', explanation: '"In addition" tells the reader you are adding another fact or detail to support the same idea. "However" and "on the other hand" signal a contrast, and "in conclusion" signals the ending.', standardCode: '4.W.2' },
        { index: 4, question: 'What is the purpose of a conclusion in informational writing?', type: 'multiple-choice', options: ['To introduce a brand new topic', 'To restate the main idea, summarize key points, and leave the reader with something to remember', 'To list every fact from the body paragraphs again', 'To share your personal opinion about the topic'], correctAnswer: 'To restate the main idea, summarize key points, and leave the reader with something to remember', hint: 'The conclusion wraps everything up.', explanation: 'A conclusion restates the main idea in a fresh way, briefly summarizes the key points, and ends with a memorable statement, question, or call to action.', standardCode: '4.W.2' },
      ],
      assessment: {
        questions: [
          { question: 'Which of these is the best hook for an informational text about recycling?', type: 'multiple-choice', options: ['Recycling is a topic.', 'Every year, Americans throw away enough plastic bottles to circle the earth four times.', 'This essay is about recycling.', 'Some people recycle and some do not.'], correctAnswer: 'Every year, Americans throw away enough plastic bottles to circle the earth four times.', standardCode: '4.W.2' },
          { question: 'How should the body of an informational text be organized?', type: 'short-answer', correctAnswer: 'Each body paragraph should focus on one subtopic, start with a topic sentence, include supporting details and facts, use linking words, and end with a closing sentence.', standardCode: '4.W.2' },
          { question: 'What should a conclusion NOT do?', type: 'multiple-choice', options: ['Restate the main idea', 'Summarize key points', 'Introduce a completely new topic', 'Leave the reader with something to remember'], correctAnswer: 'Introduce a completely new topic', standardCode: '4.W.2' },
        ],
      },
    },
  },
  {
    slug: 'grade4-ela-revising-and-editing',
    title: 'Revising and Editing',
    description: 'Develop and strengthen writing by planning, revising, and editing with guidance and support',
    subject: 'ela',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Writing',
    standardCodes: ['4.W.5'],
    content: {
      intro: {
        title: 'Revising and Editing',
        text: 'Writing is a process, not a one-time event. The best writers plan before they write, revise to make their ideas stronger, and edit to fix mistakes. These steps turn a rough draft into a polished final piece. Let us learn how each step works so you can become a more confident writer.',
        culturalHook: 'Even famous authors revise their work many times. The author Roald Dahl once said he rewrote his stories over and over until they were just right!',
      },
      segments: [
        {
          index: 0,
          title: 'Planning Before You Write',
          text: 'Good writing starts with a plan. Before you begin drafting, think about your purpose (why you are writing), your audience (who will read it), and your topic (what you are writing about). Then organize your ideas. You can use a graphic organizer like a web, an outline, or a simple list. For a narrative, plan your characters, setting, problem, and solution. For an informational text, plan your subtopics and the facts you want to include. For an opinion piece, plan your reasons and evidence. Planning does not have to take a long time, but it saves you time later because you know where your writing is going before you start.',
          keyVocabulary: ['planning', 'purpose', 'audience', 'graphic organizer', 'outline'],
        },
        {
          index: 1,
          title: 'Revising for Ideas and Organization',
          text: 'Revising means making your writing better by improving the content and organization. When you revise, ask yourself these questions: Are my ideas clear? Does each paragraph focus on one main point? Are my ideas in a logical order? Did I include enough details, facts, or examples? Is my opening interesting? Does my ending wrap things up? Revising is about the big picture — making sure your writing makes sense and says what you want it to say. You might add new sentences, remove parts that do not fit, move paragraphs around, or replace weak words with stronger ones. Revising is not about fixing spelling — that comes later.',
          keyVocabulary: ['revising', 'content', 'organization', 'logical order', 'big picture'],
        },
        {
          index: 2,
          title: 'Editing for Grammar, Spelling, and Punctuation',
          text: 'Editing is the step where you fix errors in grammar, spelling, capitalization, and punctuation. After you have revised your ideas and organization, read through your writing carefully looking for mistakes. Check that every sentence starts with a capital letter and ends with the correct punctuation mark. Look for misspelled words — if you are unsure about a spelling, look it up. Make sure subjects and verbs agree (for example, "she runs" not "she run"). Check that you used commas correctly, especially in lists and after introductory words. Edit one type of error at a time: first read for spelling, then for punctuation, then for grammar. This focused approach catches more mistakes.',
          keyVocabulary: ['editing', 'grammar', 'spelling', 'punctuation', 'capitalization'],
        },
        {
          index: 3,
          title: 'Peer Feedback and Final Drafts',
          text: 'One of the best ways to improve your writing is to get feedback from a peer — a classmate or friend. When a peer reads your work, they can catch confusing parts that you might not notice because you already know what you meant. When giving feedback, be specific and kind. Instead of saying "this is bad," say "I was confused by the second paragraph — could you add more details?" When receiving feedback, listen openly and decide which suggestions will make your writing stronger. After revising and editing, write or type your final draft. Read it one last time to make sure everything looks right. Be proud of your work — you earned it through the writing process!',
          keyVocabulary: ['peer feedback', 'specific', 'final draft', 'writing process'],
        },
      ],
      practice: [
        { index: 0, question: 'What is the difference between revising and editing?', type: 'short-answer', correctAnswer: 'Revising focuses on improving ideas, organization, and content — the big picture of the writing. Editing focuses on fixing small errors like grammar, spelling, punctuation, and capitalization.', hint: 'One is about making ideas better; the other is about fixing mistakes.', explanation: 'Revising addresses content-level improvements (ideas, structure, details). Editing addresses surface-level corrections (spelling, grammar, punctuation). Both are important but happen at different stages.', standardCode: '4.W.5' },
        { index: 1, question: 'Which of these is a revising task, NOT an editing task?', type: 'multiple-choice', options: ['Fixing a misspelled word', 'Adding a comma after an introductory phrase', 'Reorganizing paragraphs so they are in a better order', 'Capitalizing the first word of a sentence'], correctAnswer: 'Reorganizing paragraphs so they are in a better order', hint: 'Revising deals with big changes to ideas and structure.', explanation: 'Reorganizing paragraphs is a revising task because it changes the structure and flow of the writing. Fixing spelling, adding commas, and capitalizing are all editing tasks.', standardCode: '4.W.5' },
        { index: 2, question: 'Why is planning before writing important?', type: 'multiple-choice', options: ['It wastes time', 'It helps you organize your ideas so your writing is clearer and more focused', 'It is only for long essays', 'It replaces the need to revise'], correctAnswer: 'It helps you organize your ideas so your writing is clearer and more focused', hint: 'Think about what happens when you start building without a blueprint.', explanation: 'Planning helps you know where your writing is going before you start. It organizes your thoughts, saves time during drafting, and leads to clearer, more focused writing.', standardCode: '4.W.5' },
        { index: 3, question: 'What should you do when a peer gives you feedback on your writing?', type: 'multiple-choice', options: ['Ignore it completely', 'Get angry and refuse to change anything', 'Listen openly and decide which suggestions make your writing stronger', 'Change everything they suggest without thinking about it'], correctAnswer: 'Listen openly and decide which suggestions make your writing stronger', hint: 'Good writers consider feedback thoughtfully.', explanation: 'The best approach is to listen with an open mind and then decide which suggestions actually improve your writing. You do not have to accept every suggestion, but you should consider each one carefully.', standardCode: '4.W.5' },
        { index: 4, question: 'When editing, why is it helpful to focus on one type of error at a time?', type: 'short-answer', correctAnswer: 'Focusing on one type of error at a time, like first checking spelling, then punctuation, then grammar, helps you catch more mistakes because your brain is only looking for one thing.', hint: 'Think about trying to do three tasks at once versus one at a time.', explanation: 'When you look for everything at once, your brain can get overwhelmed and miss errors. Focusing on one category (spelling, then punctuation, then grammar) allows more thorough and accurate editing.', standardCode: '4.W.5' },
      ],
      assessment: {
        questions: [
          { question: 'Put these writing steps in the correct order: Edit, Draft, Plan, Revise.', type: 'short-answer', correctAnswer: 'The correct order is: Plan, Draft, Revise, Edit.', standardCode: '4.W.5' },
          { question: 'Which revision question focuses on organization?', type: 'multiple-choice', options: ['Did I spell every word correctly?', 'Are my paragraphs in a logical order?', 'Did I use commas in the right places?', 'Did I capitalize proper nouns?'], correctAnswer: 'Are my paragraphs in a logical order?', standardCode: '4.W.5' },
          { question: 'What makes peer feedback most helpful?', type: 'multiple-choice', options: ['Being vague so feelings are not hurt', 'Being specific and kind about what could improve', 'Only saying positive things', 'Rewriting the entire piece for them'], correctAnswer: 'Being specific and kind about what could improve', standardCode: '4.W.5' },
        ],
      },
    },
  },
]
