import type { ModuleSeed } from '../types'

export const GRADE_1_MATH: ModuleSeed[] = [
  {
    slug: 'grade1-math-place-value-tens-ones',
    title: 'Place Value: Tens and Ones',
    description: 'Understand that the two digits of a two-digit number represent amounts of tens and ones',
    subject: 'math',
    grade: 1,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations in Base Ten',
    standardCodes: ['1.NBT.2'],
    content: {
      intro: {
        title: 'Place Value: Tens and Ones',
        text: 'Have you ever wondered why we write numbers the way we do? Every digit in a number has a special job called its place value. Today we will learn about tens and ones, and how they work together to build two-digit numbers like 34 or 57.',
      },
      segments: [
        {
          index: 0,
          title: 'What Are Ones?',
          text: 'The ones place is the digit on the right side of a number. It tells us how many single items we have. When you count 1, 2, 3, 4, 5, 6, 7, 8, 9, each of those is in the ones place. The number 5 means five ones. Think of ones as loose blocks sitting by themselves. If you have 7 loose blocks, you have 7 ones. The ones place can hold any digit from 0 to 9.',
          keyVocabulary: ['ones', 'digit', 'place value', 'single'],
          example: 'The number 8 has 8 ones and 0 tens.',
        },
        {
          index: 1,
          title: 'What Are Tens?',
          text: 'When we get to 10, something special happens. Ten ones make one group of ten! We call this a ten. The tens place is the digit on the left side of a two-digit number. It tells us how many groups of ten we have. In the number 30, the 3 means three groups of ten and the 0 means zero extra ones. Imagine bundling 10 sticks together with a rubber band. Each bundle is one ten. If you have 4 bundles, you have 4 tens, which is 40.',
          keyVocabulary: ['tens', 'group of ten', 'bundle', 'two-digit number'],
        },
        {
          index: 2,
          title: 'Tens and Ones Together',
          text: 'Two-digit numbers are made of tens and ones working together. The number 24 has 2 tens and 4 ones. That means two bundles of ten plus four loose ones. We can write it as 20 + 4 = 24. The number 56 has 5 tens and 6 ones, which is 50 + 6 = 56. Breaking numbers into tens and ones is called decomposing. It helps us understand how big a number really is.',
          keyVocabulary: ['decompose', 'two-digit', 'expanded form'],
          example: '37 = 3 tens + 7 ones = 30 + 7',
        },
        {
          index: 3,
          title: 'Building Numbers with Tens and Ones',
          text: 'Now let us practice building numbers! If you have 6 tens and 2 ones, what number did you make? Six tens is 60, and 2 ones is 2, so the number is 62. What about 1 ten and 9 ones? That is 10 + 9 = 19. You can use base-ten blocks, drawings, or your fingers to show tens and ones. Remember, the tens digit is always on the left and the ones digit is always on the right.',
          keyVocabulary: ['base-ten blocks', 'build', 'tens digit', 'ones digit'],
        },
      ],
      practice: [
        { index: 0, question: 'How many tens are in the number 45?', type: 'short-answer', correctAnswer: '4', hint: 'The tens digit is on the left side of the number.', explanation: 'The number 45 has 4 tens and 5 ones. The digit 4 is in the tens place.', standardCode: '1.NBT.2' },
        { index: 1, question: 'How many ones are in the number 38?', type: 'short-answer', correctAnswer: '8', hint: 'The ones digit is on the right side of the number.', explanation: 'The number 38 has 3 tens and 8 ones. The digit 8 is in the ones place.', standardCode: '1.NBT.2' },
        { index: 2, question: 'What number has 7 tens and 3 ones?', type: 'short-answer', correctAnswer: '73', hint: 'Put the tens digit on the left and the ones digit on the right.', explanation: '7 tens = 70 and 3 ones = 3. Put them together: 70 + 3 = 73.', standardCode: '1.NBT.2' },
        { index: 3, question: 'Which shows 52 broken into tens and ones?', type: 'multiple-choice', options: ['5 tens and 2 ones', '2 tens and 5 ones', '50 tens and 2 ones', '5 ones and 2 tens'], correctAnswer: '5 tens and 2 ones', hint: 'The first digit tells the tens and the second digit tells the ones.', explanation: '52 = 5 tens + 2 ones. The 5 is in the tens place and the 2 is in the ones place.', standardCode: '1.NBT.2' },
        { index: 4, question: '3 tens + 0 ones = ___', type: 'fill-blank', correctAnswer: '30', hint: 'Three groups of ten with no extra ones.', explanation: '3 tens is 30. When there are 0 ones, the number is just the tens value: 30.', standardCode: '1.NBT.2' },
      ],
      assessment: {
        questions: [
          { question: 'What number has 9 tens and 1 one?', type: 'short-answer', correctAnswer: '91', standardCode: '1.NBT.2' },
          { question: 'How many tens and ones are in 64?', type: 'multiple-choice', options: ['6 tens and 4 ones', '4 tens and 6 ones', '64 tens and 0 ones', '0 tens and 64 ones'], correctAnswer: '6 tens and 4 ones', standardCode: '1.NBT.2' },
          { question: 'Write the number: 8 tens and 5 ones.', type: 'short-answer', correctAnswer: '85', standardCode: '1.NBT.2' },
        ],
      },
    },
  },
  {
    slug: 'grade1-math-two-digit-addition',
    title: 'Two-Digit Addition',
    description: 'Add within 100 using concrete models, drawings, and strategies based on place value',
    subject: 'math',
    grade: 1,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations in Base Ten',
    standardCodes: ['1.NBT.4'],
    content: {
      intro: {
        title: 'Two-Digit Addition',
        text: 'You already know how to add small numbers. Now it is time to add bigger numbers, up to 100! We will use what we know about tens and ones to help us add two-digit numbers. Get ready to become an addition superstar!',
      },
      segments: [
        {
          index: 0,
          title: 'Adding Tens to a Two-Digit Number',
          text: 'Adding a multiple of ten is easy when you understand place value. To add 10 to any number, just increase the tens digit by 1. For example, 34 + 10 = 44. The ones digit stays the same! To add 20, increase the tens digit by 2. So 25 + 20 = 45. Think of it like adding more bundles of ten to your pile. The loose ones do not change at all.',
          keyVocabulary: ['multiple of ten', 'increase', 'tens digit'],
          example: '53 + 30 = 83 (the tens go from 5 to 8, the ones stay at 3)',
        },
        {
          index: 1,
          title: 'Adding a One-Digit Number Without Regrouping',
          text: 'When you add a small number to a two-digit number and the ones do not go past 9, it is simple. Just add the ones together. For example, 42 + 5 = 47. The tens stay at 4 and the ones change from 2 to 7. Try 61 + 8 = 69. The tens stay at 6 and the ones go from 1 to 9. As long as the ones total is 9 or less, you do not need to regroup.',
          keyVocabulary: ['regroup', 'ones total', 'add ones'],
        },
        {
          index: 2,
          title: 'Adding with Regrouping',
          text: 'Sometimes when you add the ones, you get 10 or more. That means you need to regroup! Regrouping means trading 10 ones for 1 new ten. For example, 27 + 5: add the ones first, 7 + 5 = 12. That is 1 ten and 2 ones. Now add the new ten to the tens you already have: 2 tens + 1 ten = 3 tens. The answer is 32. Think of it as bundling up 10 loose ones into a new group of ten.',
          keyVocabulary: ['regroup', 'trade', 'carry', 'bundle'],
          example: '38 + 4: ones are 8 + 4 = 12, regroup to get 1 new ten and 2 ones. 3 tens + 1 ten = 4 tens. Answer: 42.',
        },
        {
          index: 3,
          title: 'Adding Two Two-Digit Numbers',
          text: 'To add two two-digit numbers, add the ones first, then the tens. For 23 + 14: ones are 3 + 4 = 7, tens are 2 + 1 = 3, so the answer is 37. If the ones total 10 or more, remember to regroup. For 35 + 27: ones are 5 + 7 = 12, write down 2 ones and regroup 1 ten. Tens are 3 + 2 + 1 = 6. The answer is 62.',
          keyVocabulary: ['add ones first', 'add tens', 'two-digit addition'],
        },
      ],
      practice: [
        { index: 0, question: '43 + 20 = ?', type: 'short-answer', correctAnswer: '63', hint: 'Only the tens digit changes when you add a multiple of ten.', explanation: '43 + 20 = 63. The tens go from 4 to 6, and the ones stay at 3.', standardCode: '1.NBT.4' },
        { index: 1, question: '51 + 7 = ?', type: 'short-answer', correctAnswer: '58', hint: 'Add the ones: 1 + 7. The tens stay the same.', explanation: '51 + 7 = 58. The ones are 1 + 7 = 8, and the tens stay at 5.', standardCode: '1.NBT.4' },
        { index: 2, question: '28 + 5 = ?', type: 'short-answer', correctAnswer: '33', hint: 'Add the ones: 8 + 5 = 13. You need to regroup!', explanation: '28 + 5 = 33. The ones are 8 + 5 = 13. Regroup: 1 ten and 3 ones. 2 tens + 1 ten = 3 tens. Answer: 33.', standardCode: '1.NBT.4' },
        { index: 3, question: '34 + 25 = ?', type: 'fill-blank', correctAnswer: '59', hint: 'Add ones first (4 + 5), then add tens (3 + 2).', explanation: '34 + 25 = 59. Ones: 4 + 5 = 9. Tens: 3 + 2 = 5. Answer: 59.', standardCode: '1.NBT.4' },
        { index: 4, question: 'Which is the correct answer for 46 + 37?', type: 'multiple-choice', options: ['73', '83', '813', '713'], correctAnswer: '83', hint: 'Add the ones: 6 + 7 = 13. Regroup and then add the tens.', explanation: '46 + 37 = 83. Ones: 6 + 7 = 13, write 3 ones, carry 1 ten. Tens: 4 + 3 + 1 = 8. Answer: 83.', standardCode: '1.NBT.4' },
      ],
      assessment: {
        questions: [
          { question: '55 + 30 = ?', type: 'short-answer', correctAnswer: '85', standardCode: '1.NBT.4' },
          { question: '47 + 6 = ?', type: 'short-answer', correctAnswer: '53', standardCode: '1.NBT.4' },
          { question: '36 + 48 = ?', type: 'multiple-choice', options: ['74', '84', '714', '82'], correctAnswer: '84', standardCode: '1.NBT.4' },
        ],
      },
    },
  },
  {
    slug: 'grade1-math-two-digit-subtraction',
    title: 'Two-Digit Subtraction',
    description: 'Subtract multiples of 10 from two-digit numbers using place value strategies',
    subject: 'math',
    grade: 1,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations in Base Ten',
    standardCodes: ['1.NBT.6'],
    content: {
      intro: {
        title: 'Two-Digit Subtraction',
        text: 'You already know how to take away small numbers. Now let us learn to subtract bigger numbers using tens! When we subtract multiples of 10 from two-digit numbers, we use our place value skills to make it easy.',
      },
      segments: [
        {
          index: 0,
          title: 'Subtracting Ten',
          text: 'Subtracting 10 from a number is the opposite of adding 10. When you subtract 10, the tens digit goes down by 1 and the ones digit stays the same. For example, 47 - 10 = 37. The tens went from 4 to 3, but the ones stayed at 7. Think of it as removing one bundle of ten from your pile. You still have the same loose ones.',
          keyVocabulary: ['subtract', 'remove', 'tens digit', 'ones stay the same'],
          example: '65 - 10 = 55 (the tens go from 6 to 5, the ones stay at 5)',
        },
        {
          index: 1,
          title: 'Subtracting Multiples of Ten',
          text: 'A multiple of ten is a number like 10, 20, 30, 40, 50, 60, 70, 80, or 90. When you subtract a multiple of ten, just subtract the tens digits. For example, 73 - 30 = 43. Think about it: 7 tens minus 3 tens equals 4 tens, and the 3 ones stay put. It is like taking away bundles of ten from a shelf. The loose ones on the shelf do not move.',
          keyVocabulary: ['multiple of ten', 'subtract tens', 'bundles'],
        },
        {
          index: 2,
          title: 'Using a Number Line to Subtract Tens',
          text: 'A number line can help you see subtraction. To subtract 20 from 58, start at 58 on the number line. Jump back 10 to reach 48. Jump back 10 more to reach 38. So 58 - 20 = 38. Each jump of 10 takes you to a number that is 10 less. You can also jump back by 10 in your head: just think of the number that has one fewer ten.',
          keyVocabulary: ['number line', 'jump back', '10 less'],
          example: '82 - 40: start at 82, jump back 10 four times: 72, 62, 52, 42. Answer: 42.',
        },
        {
          index: 3,
          title: 'Solving Story Problems',
          text: 'Let us use what we learned to solve real problems. Rosa has 56 stickers. She gives away 20 stickers to her friends. How many does she have left? We subtract: 56 - 20 = 36 stickers. Jamal has 84 pennies. He spends 50 pennies at the school store. How many pennies does he have left? We subtract: 84 - 50 = 34 pennies. Look for clue words like "gives away," "left," or "spends" to know when to subtract.',
          keyVocabulary: ['story problem', 'clue words', 'gives away', 'left'],
        },
      ],
      practice: [
        { index: 0, question: '67 - 10 = ?', type: 'short-answer', correctAnswer: '57', hint: 'Subtract 1 from the tens digit. The ones stay the same.', explanation: '67 - 10 = 57. The tens go from 6 to 5, and the ones stay at 7.', standardCode: '1.NBT.6' },
        { index: 1, question: '85 - 40 = ?', type: 'short-answer', correctAnswer: '45', hint: 'Subtract the tens: 8 tens - 4 tens = 4 tens.', explanation: '85 - 40 = 45. Subtract the tens: 8 - 4 = 4 tens. The 5 ones stay.', standardCode: '1.NBT.6' },
        { index: 2, question: '93 - 60 = ?', type: 'fill-blank', correctAnswer: '33', hint: '9 tens minus 6 tens equals how many tens?', explanation: '93 - 60 = 33. Tens: 9 - 6 = 3. Ones stay at 3.', standardCode: '1.NBT.6' },
        { index: 3, question: 'Mia has 72 crayons. She puts 30 back in the box. How many does she still have?', type: 'short-answer', correctAnswer: '42', hint: 'Subtract: 72 - 30. Only the tens change.', explanation: '72 - 30 = 42. Tens: 7 - 3 = 4. Ones stay at 2. Mia has 42 crayons left.', standardCode: '1.NBT.6' },
        { index: 4, question: 'Which is the correct answer for 51 - 20?', type: 'multiple-choice', options: ['71', '31', '41', '21'], correctAnswer: '31', hint: 'Start at 51 and subtract 2 tens.', explanation: '51 - 20 = 31. Tens: 5 - 2 = 3. Ones stay at 1.', standardCode: '1.NBT.6' },
      ],
      assessment: {
        questions: [
          { question: '78 - 30 = ?', type: 'short-answer', correctAnswer: '48', standardCode: '1.NBT.6' },
          { question: '60 - 40 = ?', type: 'short-answer', correctAnswer: '20', standardCode: '1.NBT.6' },
          { question: 'Sam had 94 marbles. He lost 50. How many are left?', type: 'multiple-choice', options: ['44', '54', '34', '144'], correctAnswer: '44', standardCode: '1.NBT.6' },
        ],
      },
    },
  },
  {
    slug: 'grade1-math-measuring-lengths',
    title: 'Measuring Lengths',
    description: 'Order objects by length and measure lengths using non-standard units',
    subject: 'math',
    grade: 1,
    gradeBand: 'k5',
    topicCluster: 'Measurement & Data',
    standardCodes: ['1.MD.1', '1.MD.2'],
    content: {
      intro: {
        title: 'Measuring Lengths',
        text: 'How tall is your pencil? How long is your desk? Measuring helps us find out! Today we will learn to compare the lengths of objects and measure using everyday items like paper clips and cubes. You do not always need a ruler to measure!',
      },
      segments: [
        {
          index: 0,
          title: 'Comparing Lengths',
          text: 'To compare the lengths of two objects, line them up so one end is even. Then look at the other end to see which one sticks out farther. The one that is longer sticks out past the shorter one. We use the words longer, shorter, and the same length. For example, your pencil might be longer than your eraser. A crayon might be shorter than a marker. Always start from the same edge when comparing!',
          keyVocabulary: ['longer', 'shorter', 'same length', 'compare', 'line up'],
          example: 'Line up a crayon and a pencil at one end. The pencil sticks out farther, so the pencil is longer.',
        },
        {
          index: 1,
          title: 'Ordering by Length',
          text: 'When you have three or more objects, you can put them in order from shortest to longest or from longest to shortest. First, compare two objects. Then figure out where the third one fits. A paper clip is short, a pencil is medium, and a ruler is long. In order from shortest to longest: paper clip, pencil, ruler. Ordering helps us see which object is the longest and which is the shortest in a group.',
          keyVocabulary: ['order', 'shortest to longest', 'longest to shortest'],
        },
        {
          index: 2,
          title: 'Measuring with Non-Standard Units',
          text: 'You can measure how long something is by laying small objects end to end along it. These small objects are called non-standard units. Paper clips, cubes, and even your thumb can be units! To measure a book with paper clips, lay the clips in a line from one end of the book to the other. Count the clips. If you used 8 paper clips, the book is 8 paper clips long. Make sure there are no gaps or overlaps between the units.',
          keyVocabulary: ['non-standard unit', 'end to end', 'gaps', 'overlaps'],
          example: 'A marker is about 5 cubes long when you line up 5 cubes from one end to the other.',
        },
        {
          index: 3,
          title: 'Why Measurements Can Be Different',
          text: 'If you measure a book with big cubes and your friend measures the same book with small paper clips, you will get different numbers. That is because the units are different sizes! The book did not change, but the unit size changed. A book might be 3 big cubes long but 9 small paper clips long. Smaller units give bigger numbers. This is why it is important to tell people which unit you used when you share a measurement.',
          keyVocabulary: ['unit size', 'smaller units', 'bigger numbers', 'measurement'],
        },
      ],
      practice: [
        { index: 0, question: 'A ribbon is 6 paper clips long. A string is 9 paper clips long. Which is longer?', type: 'multiple-choice', options: ['The ribbon', 'The string', 'They are the same'], correctAnswer: 'The string', hint: 'Which number is greater: 6 or 9?', explanation: 'The string is longer because 9 paper clips is more than 6 paper clips.', standardCode: '1.MD.1' },
        { index: 1, question: 'Put these in order from shortest to longest: a shoe (4 cubes), a pencil (7 cubes), a crayon (3 cubes).', type: 'short-answer', correctAnswer: 'crayon, shoe, pencil', hint: 'Order the numbers from least to greatest: 3, 4, 7.', explanation: 'Crayon (3 cubes) is shortest, then shoe (4 cubes), then pencil (7 cubes) is longest.', standardCode: '1.MD.1' },
        { index: 2, question: 'You measure a book and it is 5 cubes long. What did you use as your unit?', type: 'multiple-choice', options: ['Cubes', 'Paper clips', 'Inches', 'Hands'], correctAnswer: 'Cubes', hint: 'Read the problem carefully. What objects were placed end to end?', explanation: 'The problem says the book is 5 cubes long, so cubes are the unit.', standardCode: '1.MD.2' },
        { index: 3, question: 'A desk is 12 paper clips long. Your friend says it is 6 big blocks long. Can both be correct?', type: 'multiple-choice', options: ['Yes, because the units are different sizes', 'No, a desk can only have one length'], correctAnswer: 'Yes, because the units are different sizes', hint: 'Think about what happens when you use bigger or smaller units.', explanation: 'Both can be correct. Bigger units give smaller numbers. The desk is the same length, but measured with different-sized units.', standardCode: '1.MD.2' },
        { index: 4, question: 'When measuring with paper clips, why is it important to leave no gaps?', type: 'multiple-choice', options: ['It looks neater', 'Gaps make the measurement too small', 'Paper clips might fall off', 'The teacher said so'], correctAnswer: 'Gaps make the measurement too small', hint: 'If you skip space, you might miss part of the length.', explanation: 'Gaps between units mean you are not measuring the full length, so your count will be too small and the measurement will be wrong.', standardCode: '1.MD.2' },
      ],
      assessment: {
        questions: [
          { question: 'A marker is 4 cubes long. A paintbrush is 7 cubes long. Which is shorter?', type: 'multiple-choice', options: ['The marker', 'The paintbrush', 'They are the same'], correctAnswer: 'The marker', standardCode: '1.MD.1' },
          { question: 'You place 10 paper clips end to end along your notebook. How long is your notebook?', type: 'short-answer', correctAnswer: '10 paper clips', standardCode: '1.MD.2' },
          { question: 'A pencil is 6 small cubes long. Would it take more or fewer big cubes to measure the same pencil?', type: 'short-answer', correctAnswer: 'fewer', standardCode: '1.MD.2' },
        ],
      },
    },
  },
  {
    slug: 'grade1-math-telling-time',
    title: 'Telling Time',
    description: 'Tell and write time in hours and half-hours using analog and digital clocks',
    subject: 'math',
    grade: 1,
    gradeBand: 'k5',
    topicCluster: 'Measurement & Data',
    standardCodes: ['1.MD.3'],
    content: {
      intro: {
        title: 'Telling Time',
        text: 'Clocks help us know what time it is so we can get to school, eat lunch, and know when to play. Today we will learn to read clocks and tell time to the hour and half-hour. Let us become time experts!',
      },
      segments: [
        {
          index: 0,
          title: 'Parts of a Clock',
          text: 'A clock has numbers from 1 to 12 arranged in a circle. It also has two hands that point to numbers. The short hand is the hour hand. It moves slowly and tells us the hour. The long hand is the minute hand. It moves faster and tells us the minutes. When the minute hand points straight up to the 12, it means the time is exactly on the hour. A digital clock shows time with numbers and a colon, like 3:00.',
          keyVocabulary: ['hour hand', 'minute hand', 'clock', 'digital', 'colon'],
          example: 'When the short hand points to 5 and the long hand points to 12, the time is 5 o\'clock, or 5:00.',
        },
        {
          index: 1,
          title: 'Telling Time to the Hour',
          text: 'When the long minute hand points to 12, we read the number the short hour hand is pointing to. That is the hour. If the hour hand points to 8 and the minute hand points to 12, it is 8 o\'clock. We write it as 8:00. The two zeros after the colon mean zero extra minutes. Practice looking at the short hand first to find the hour, then check that the long hand is on the 12.',
          keyVocabulary: ['o\'clock', 'hour', 'on the hour'],
        },
        {
          index: 2,
          title: 'Telling Time to the Half-Hour',
          text: 'When the long minute hand points straight down to the 6, it is the half-hour. Half an hour is 30 minutes. If the hour hand is between 2 and 3 and the minute hand points to 6, it is 2:30, or half past two. Notice that the hour hand moves a little between hours. At 2:30, the hour hand is halfway between 2 and 3 because half the hour has passed. We write the half-hour as :30 after the hour number.',
          keyVocabulary: ['half-hour', 'half past', '30 minutes', 'halfway'],
          example: 'Hour hand between 9 and 10, minute hand on 6 means it is 9:30, or half past nine.',
        },
        {
          index: 3,
          title: 'Clocks in Our Day',
          text: 'We use time all through the day. You might wake up at 7:00 in the morning, eat lunch at 12:00, and go to bed at 8:30 at night. Knowing the time helps you follow a schedule and be on time for fun activities. Practice reading clocks around your home and school. Look at the clock on the wall, on the microwave, or on a phone. Can you tell if it is showing a time on the hour or half-hour?',
          keyVocabulary: ['schedule', 'morning', 'afternoon', 'night'],
        },
      ],
      practice: [
        { index: 0, question: 'The short hand points to 3 and the long hand points to 12. What time is it?', type: 'short-answer', correctAnswer: '3:00', hint: 'When the long hand is on 12, it is exactly on the hour.', explanation: 'The hour hand on 3 and the minute hand on 12 means it is 3:00, or 3 o\'clock.', standardCode: '1.MD.3' },
        { index: 1, question: 'The minute hand points to 6 and the hour hand is between 7 and 8. What time is it?', type: 'short-answer', correctAnswer: '7:30', hint: 'Minute hand on 6 means half past. Read the hour from the short hand.', explanation: 'The minute hand on 6 means it is the half-hour. The hour hand between 7 and 8 means it is 7:30, or half past seven.', standardCode: '1.MD.3' },
        { index: 2, question: 'Which clock shows 10 o\'clock?', type: 'multiple-choice', options: ['Short hand on 10, long hand on 12', 'Short hand on 12, long hand on 10', 'Short hand on 10, long hand on 6', 'Both hands on 10'], correctAnswer: 'Short hand on 10, long hand on 12', hint: 'O\'clock means the minute hand is on 12.', explanation: 'At 10 o\'clock, the hour hand (short) points to 10 and the minute hand (long) points to 12.', standardCode: '1.MD.3' },
        { index: 3, question: 'What does :30 mean on a digital clock?', type: 'multiple-choice', options: ['30 minutes past the hour', 'The hour is 30', '30 seconds', '30 o\'clock'], correctAnswer: '30 minutes past the hour', hint: 'The number after the colon shows the minutes.', explanation: ':30 means 30 minutes past the hour, which is the half-hour.', standardCode: '1.MD.3' },
        { index: 4, question: 'Write the time: the short hand is on 1 and the long hand is on 12.', type: 'fill-blank', correctAnswer: '1:00', hint: 'The long hand on 12 means it is exactly on the hour.', explanation: 'Hour hand on 1, minute hand on 12 means 1:00, or one o\'clock.', standardCode: '1.MD.3' },
      ],
      assessment: {
        questions: [
          { question: 'The hour hand points to 6 and the minute hand points to 12. What time is it?', type: 'short-answer', correctAnswer: '6:00', standardCode: '1.MD.3' },
          { question: 'What time does a clock show when the minute hand is on 6 and the hour hand is between 11 and 12?', type: 'short-answer', correctAnswer: '11:30', standardCode: '1.MD.3' },
          { question: 'Which shows half past 4?', type: 'multiple-choice', options: ['4:00', '4:30', '4:06', '6:04'], correctAnswer: '4:30', standardCode: '1.MD.3' },
        ],
      },
    },
  },
  {
    slug: 'grade1-math-organizing-data',
    title: 'Organizing Data',
    description: 'Organize, represent, and interpret data with up to three categories',
    subject: 'math',
    grade: 1,
    gradeBand: 'k5',
    topicCluster: 'Measurement & Data',
    standardCodes: ['1.MD.4'],
    content: {
      intro: {
        title: 'Organizing Data',
        text: 'Data is information we collect about the world around us. When we ask our friends their favorite color or count how many sunny days we had, we are collecting data! Today we will learn how to sort data into groups, show it in charts, and answer questions about what we find.',
      },
      segments: [
        {
          index: 0,
          title: 'Sorting into Categories',
          text: 'A category is a group of things that are alike. If you ask your classmates about their favorite fruit, the categories might be apples, bananas, and grapes. Each answer goes into one category. Sorting means putting each answer in the right group. You can use tally marks to keep count. A tally mark looks like a small line. Every fifth mark crosses the other four to make a bundle. Tally marks help you count quickly.',
          keyVocabulary: ['data', 'category', 'sort', 'tally marks'],
          example: 'Favorite fruit: Apples |||, Bananas ||||, Grapes || means 3 like apples, 4 like bananas, 2 like grapes.',
        },
        {
          index: 1,
          title: 'Making a Picture Graph',
          text: 'A picture graph uses small pictures or symbols to show data. Each picture stands for one thing. To make a picture graph, write the categories along the bottom or side. Then draw one picture for each count in that category. For example, if 5 kids chose red, draw 5 small red circles in the red row. Picture graphs make it easy to see which category has the most or the least just by looking at which row is longest or shortest.',
          keyVocabulary: ['picture graph', 'symbol', 'row', 'most', 'least'],
        },
        {
          index: 2,
          title: 'Reading Charts and Graphs',
          text: 'Once data is organized in a chart or graph, we can answer questions about it. We can find out which category has the most by looking for the tallest column or longest row. We can find which has the least by looking for the shortest. We can also find how many in each group by counting the pictures or reading the numbers. We can even compare groups: how many more kids chose cats than fish? Subtract to find out!',
          keyVocabulary: ['chart', 'graph', 'most', 'least', 'how many more'],
          example: 'If cats = 6 and fish = 2, then 6 - 2 = 4 more kids chose cats than fish.',
        },
      ],
      practice: [
        { index: 0, question: 'In a class survey, 5 kids like soccer, 3 like basketball, and 7 like baseball. Which sport is the most popular?', type: 'multiple-choice', options: ['Soccer', 'Basketball', 'Baseball'], correctAnswer: 'Baseball', hint: 'Which number is the greatest: 5, 3, or 7?', explanation: 'Baseball is the most popular because 7 is greater than 5 and 3.', standardCode: '1.MD.4' },
        { index: 1, question: 'A picture graph shows: Red = 4 pictures, Blue = 6 pictures, Green = 2 pictures. How many kids chose Blue?', type: 'short-answer', correctAnswer: '6', hint: 'Count the pictures in the Blue row.', explanation: 'There are 6 pictures in the Blue row, so 6 kids chose blue.', standardCode: '1.MD.4' },
        { index: 2, question: 'Using the same graph: Red = 4, Blue = 6, Green = 2. How many more kids chose Blue than Green?', type: 'short-answer', correctAnswer: '4', hint: 'Subtract: 6 - 2.', explanation: '6 - 2 = 4. Four more kids chose blue than green.', standardCode: '1.MD.4' },
        { index: 3, question: 'You are sorting shapes. You have 3 circles, 5 squares, and 3 triangles. Which category has the fewest?', type: 'multiple-choice', options: ['Circles only', 'Squares', 'Circles and triangles are tied for fewest'], correctAnswer: 'Circles and triangles are tied for fewest', hint: 'Compare all three numbers: 3, 5, and 3.', explanation: 'Circles and triangles both have 3, which is less than 5 squares. They are tied for the fewest.', standardCode: '1.MD.4' },
        { index: 4, question: 'A tally chart shows: Dogs |||| , Cats |||, Birds ||. How many pets were counted in all?', type: 'fill-blank', correctAnswer: '9', hint: 'Add up all the tally marks: 4 + 3 + 2.', explanation: 'Dogs = 4, Cats = 3, Birds = 2. Total: 4 + 3 + 2 = 9 pets counted in all.', standardCode: '1.MD.4' },
      ],
      assessment: {
        questions: [
          { question: 'A chart shows: Apples = 8, Oranges = 5, Bananas = 8. Which fruits are tied?', type: 'multiple-choice', options: ['Apples and Oranges', 'Apples and Bananas', 'Oranges and Bananas'], correctAnswer: 'Apples and Bananas', standardCode: '1.MD.4' },
          { question: 'In a graph, Cats = 7 and Dogs = 4. How many more chose cats?', type: 'short-answer', correctAnswer: '3', standardCode: '1.MD.4' },
          { question: 'A class collected data on favorite seasons. Spring = 6, Summer = 9, Fall = 3, Winter = 2. Which season is least popular?', type: 'short-answer', correctAnswer: 'Winter', standardCode: '1.MD.4' },
        ],
      },
    },
  },
  {
    slug: 'grade1-math-addition-within-20',
    title: 'Addition Within 20',
    description: 'Solve add-to word problems within 20 using objects, drawings, and equations',
    subject: 'math',
    grade: 1,
    gradeBand: 'k5',
    topicCluster: 'Operations & Algebraic Thinking',
    standardCodes: ['1.OA.1'],
    content: {
      intro: {
        title: 'Addition Within 20',
        text: 'Adding is putting groups together to find how many in all. You already know how to add small numbers. Now we will practice adding numbers that go all the way up to 20! We will use stories, pictures, and number sentences to help us.',
      },
      segments: [
        {
          index: 0,
          title: 'Add-To Problems',
          text: 'An add-to problem starts with a number, and then more are added. For example: Tina has 8 apples. Her mom gives her 5 more apples. How many apples does Tina have now? We start at 8 and add 5 more. You can count on from 8: nine, ten, eleven, twelve, thirteen. So 8 + 5 = 13. The word "more" is a clue that you need to add. Look for words like "more," "in all," and "altogether" in story problems. Drawing pictures of the objects can help you see both groups before you put them together.',
          keyVocabulary: ['add-to', 'count on', 'more', 'altogether', 'in all'],
          example: 'Leo had 6 stickers. He got 7 more. 6 + 7 = 13 stickers in all.',
        },
        {
          index: 1,
          title: 'Using Ten Frames',
          text: 'A ten frame is a rectangle with ten boxes arranged in two rows of five. It helps you see numbers up to ten easily. To add 9 + 4, fill the ten frame with 9 counters. You need 1 more counter to fill the frame to 10. Take 1 from the 4, so now you have 10 and 3 left over. 10 + 3 = 13! This strategy is called making a ten. It works great for adding numbers that are close to 10. Making a ten turns a hard problem into an easy one because adding to 10 is simple.',
          keyVocabulary: ['ten frame', 'making a ten', 'counters', 'strategy'],
          example: '8 + 6: put 8 in the frame, take 2 from 6 to fill to 10, then 10 + 4 = 14.',
        },
        {
          index: 2,
          title: 'Doubles and Near Doubles',
          text: 'Doubles are addition facts where both numbers are the same: 5 + 5 = 10, 7 + 7 = 14, 9 + 9 = 18. Doubles are easy to memorize! Near doubles are problems where one number is just one more than the other. For 6 + 7, think of 6 + 6 = 12, then add 1 more to get 13. Or for 8 + 7, think 7 + 7 = 14, then add 1 more to get 15. Using doubles you already know as a shortcut helps you solve near-double problems quickly without counting on your fingers.',
          keyVocabulary: ['doubles', 'near doubles', 'shortcut', 'memorize'],
        },
        {
          index: 3,
          title: 'Writing Addition Equations',
          text: 'An equation uses numbers and symbols to show a math fact. The plus sign + means add. The equal sign = means the same as. When you write 9 + 6 = 15, you are saying that nine plus six is the same as fifteen. In a story problem, find the two parts being put together and write them with a plus sign. Then solve and write the total after the equal sign. You can also write the unknown with a question mark: 9 + 6 = ? Practice writing equations for every addition problem you solve so you get comfortable with number sentences.',
          keyVocabulary: ['equation', 'plus sign', 'equal sign', 'number sentence'],
          example: 'Kai has 11 grapes. Nia gives him 5 more. Equation: 11 + 5 = 16.',
        },
      ],
      practice: [
        { index: 0, question: 'Maya has 7 crayons. She finds 6 more. How many crayons does she have now?', type: 'short-answer', correctAnswer: '13', hint: 'Start at 7 and add 6 more.', explanation: '7 + 6 = 13. Maya now has 13 crayons.', standardCode: '1.OA.1' },
        { index: 1, question: '9 + 8 = ?', type: 'short-answer', correctAnswer: '17', hint: 'Try making a ten: 9 + 1 = 10, then add the remaining 7.', explanation: '9 + 8 = 17. Make a ten: 9 + 1 = 10, and 10 + 7 = 17.', standardCode: '1.OA.1' },
        { index: 2, question: 'Which strategy uses 6 + 6 to solve 6 + 7?', type: 'multiple-choice', options: ['Making a ten', 'Doubles plus one', 'Counting backwards', 'Subtracting'], correctAnswer: 'Doubles plus one', hint: '6 + 7 is close to 6 + 6.', explanation: '6 + 6 = 12, then add 1 more to get 13. This is the doubles plus one strategy.', standardCode: '1.OA.1' },
        { index: 3, question: 'There are 5 birds in a tree. Then 9 more birds land in the tree. How many birds are in the tree now?', type: 'fill-blank', correctAnswer: '14', hint: 'Add the two groups: 5 + 9.', explanation: '5 + 9 = 14 birds in the tree.', standardCode: '1.OA.1' },
        { index: 4, question: '8 + 8 = ?', type: 'short-answer', correctAnswer: '16', hint: 'This is a doubles fact.', explanation: '8 + 8 = 16. Doubles: two groups of eight make sixteen.', standardCode: '1.OA.1' },
      ],
      assessment: {
        questions: [
          { question: 'Sam has 12 stickers. He gets 7 more. How many stickers does he have?', type: 'short-answer', correctAnswer: '19', standardCode: '1.OA.1' },
          { question: '7 + 9 = ?', type: 'multiple-choice', options: ['15', '16', '17', '18'], correctAnswer: '16', standardCode: '1.OA.1' },
          { question: 'Write the equation: There are 6 red balls and 8 blue balls. How many balls in all?', type: 'short-answer', correctAnswer: '14', standardCode: '1.OA.1' },
        ],
      },
    },
  },
  {
    slug: 'grade1-math-subtraction-within-20',
    title: 'Subtraction Within 20',
    description: 'Solve take-from and comparison problems within 20 using objects, drawings, and equations',
    subject: 'math',
    grade: 1,
    gradeBand: 'k5',
    topicCluster: 'Operations & Algebraic Thinking',
    standardCodes: ['1.OA.1'],
    content: {
      intro: {
        title: 'Subtraction Within 20',
        text: 'Subtraction means taking away or finding the difference between two groups. When someone eats some of your grapes or you give away some toys, you are subtracting! Today we will learn to solve take-from and comparison problems with numbers up to 20.',
      },
      segments: [
        {
          index: 0,
          title: 'Take-From Problems',
          text: 'A take-from problem starts with a total, and then some are removed. For example: There are 14 birds on a fence. Then 6 birds fly away. How many birds are left? We start with 14 and take away 6. You can count back from 14: thirteen, twelve, eleven, ten, nine, eight. So 14 - 6 = 8 birds are left. Look for clue words like "left," "fly away," "ate," "lost," or "gave away." These words tell you that objects are being removed from the starting group.',
          keyVocabulary: ['take-from', 'count back', 'left', 'remove', 'take away'],
          example: 'Mia had 15 grapes. She ate 7. 15 - 7 = 8 grapes left.',
        },
        {
          index: 1,
          title: 'Comparison Problems',
          text: 'A comparison problem asks you to find the difference between two groups. For example: Zoe has 13 blocks and Kai has 9 blocks. How many more blocks does Zoe have than Kai? Line up both groups and match them one to one. Zoe has extra blocks that do not have a match. Count the extras: 13 - 9 = 4 more blocks. Comparison clue words include "how many more," "how many fewer," and "how much longer." You are not really taking anything away; you are finding the gap between the two amounts.',
          keyVocabulary: ['comparison', 'difference', 'how many more', 'how many fewer', 'match'],
          example: 'Team A scored 11 points. Team B scored 7 points. 11 - 7 = 4. Team A scored 4 more points.',
        },
        {
          index: 2,
          title: 'Using Addition to Subtract',
          text: 'Addition and subtraction are related! You can use addition to help you subtract. For 15 - 8, think: what number plus 8 equals 15? You know 8 + 7 = 15, so 15 - 8 = 7. This is called thinking addition. It works because addition and subtraction are opposite operations. If you know your addition facts well, you can flip them around to solve subtraction problems. This makes subtraction much faster than counting back one by one every time.',
          keyVocabulary: ['thinking addition', 'related facts', 'opposite operations', 'fact family'],
        },
        {
          index: 3,
          title: 'Writing Subtraction Equations',
          text: 'A subtraction equation uses a minus sign to show taking away. The minus sign - means subtract. In the equation 17 - 9 = 8, we start with 17, take away 9, and are left with 8. The first number is always the bigger number or the starting amount. When you read a story problem, find the total you start with and the amount being removed. Write them with a minus sign. Then solve and write your answer after the equal sign. Always check your work by adding your answer to the number you subtracted.',
          keyVocabulary: ['minus sign', 'subtraction equation', 'starting amount', 'check your work'],
          example: '20 fish in a tank. 11 are moved. Equation: 20 - 11 = 9 fish left.',
        },
      ],
      practice: [
        { index: 0, question: 'There are 16 cookies. Tom eats 9. How many cookies are left?', type: 'short-answer', correctAnswer: '7', hint: 'Start at 16 and subtract 9.', explanation: '16 - 9 = 7. There are 7 cookies left.', standardCode: '1.OA.1' },
        { index: 1, question: 'Ella has 12 stickers. Jake has 5 stickers. How many more stickers does Ella have?', type: 'short-answer', correctAnswer: '7', hint: 'Subtract to compare: 12 - 5.', explanation: '12 - 5 = 7. Ella has 7 more stickers than Jake.', standardCode: '1.OA.1' },
        { index: 2, question: '18 - 9 = ?', type: 'short-answer', correctAnswer: '9', hint: 'Think: 9 + ? = 18.', explanation: '18 - 9 = 9. This is a doubles fact: 9 + 9 = 18.', standardCode: '1.OA.1' },
        { index: 3, question: 'Which clue word tells you to subtract?', type: 'multiple-choice', options: ['Altogether', 'Left', 'In all', 'Total'], correctAnswer: 'Left', hint: 'Which word means some were removed?', explanation: '"Left" means some items were taken away and you need to find what remains, so you subtract.', standardCode: '1.OA.1' },
        { index: 4, question: 'There are 14 ducks on a pond. 8 swim away. How many ducks are still on the pond?', type: 'fill-blank', correctAnswer: '6', hint: 'Start at 14, take away 8.', explanation: '14 - 8 = 6 ducks still on the pond.', standardCode: '1.OA.1' },
      ],
      assessment: {
        questions: [
          { question: '17 - 8 = ?', type: 'short-answer', correctAnswer: '9', standardCode: '1.OA.1' },
          { question: 'Ava has 15 beads. Lily has 6 beads. How many fewer beads does Lily have?', type: 'multiple-choice', options: ['7', '8', '9', '10'], correctAnswer: '9', standardCode: '1.OA.1' },
          { question: '20 - 13 = ?', type: 'short-answer', correctAnswer: '7', standardCode: '1.OA.1' },
        ],
      },
    },
  },
  {
    slug: 'grade1-math-properties-of-addition',
    title: 'Properties of Addition',
    description: 'Understand and apply the commutative and associative properties of addition',
    subject: 'math',
    grade: 1,
    gradeBand: 'k5',
    topicCluster: 'Operations & Algebraic Thinking',
    standardCodes: ['1.OA.3'],
    content: {
      intro: {
        title: 'Properties of Addition',
        text: 'Did you know that addition has special rules that always work? These rules are called properties. They make adding easier and faster. Today we will learn two amazing properties that will help you solve problems like a math whiz!',
      },
      segments: [
        {
          index: 0,
          title: 'The Commutative Property (Turn-Around Facts)',
          text: 'The commutative property says you can add two numbers in any order and get the same answer. 3 + 5 = 8 and 5 + 3 = 8. The answer is the same! We call these turn-around facts because you can turn the numbers around. Imagine you have 3 red blocks and 5 blue blocks. Whether you put the red ones first or the blue ones first, you still have 8 blocks total. This property is very helpful because if you know 2 + 9 = 11, you automatically know 9 + 2 = 11 without having to figure it out again.',
          keyVocabulary: ['commutative property', 'turn-around facts', 'order', 'same answer'],
          example: '4 + 7 = 11 and 7 + 4 = 11. The order changed but the sum did not!',
        },
        {
          index: 1,
          title: 'The Associative Property (Grouping)',
          text: 'The associative property says that when you add three or more numbers, you can group them in any way and the sum stays the same. For 2 + 3 + 7, you can add 2 + 3 first to get 5, then add 7 to get 12. Or you can add 3 + 7 first to get 10, then add 2 to get 12. Either way, the answer is 12! Smart mathematicians look for pairs that make a ten. In 4 + 8 + 6, adding 4 + 6 first gives 10, and then 10 + 8 = 18. Grouping to make a ten is a useful mental math shortcut.',
          keyVocabulary: ['associative property', 'grouping', 'parentheses', 'mental math'],
          example: '(1 + 9) + 5 = 10 + 5 = 15 and 1 + (9 + 5) = 1 + 14 = 15. Same answer!',
        },
        {
          index: 2,
          title: 'Using Properties to Solve Problems',
          text: 'Now let us use these properties together to make addition easier. Suppose you need to add 6 + 5 + 4. You could add left to right: 6 + 5 = 11, then 11 + 4 = 15. Or, use the commutative property to rearrange: 6 + 4 + 5. Now group 6 + 4 = 10, then 10 + 5 = 15. Making a ten first was quicker! When you see an addition problem, look for friendly numbers that combine easily. Pairs that make 10, like 3 and 7, or 8 and 2, are the best friends to look for.',
          keyVocabulary: ['friendly numbers', 'rearrange', 'make a ten', 'efficient'],
        },
        {
          index: 3,
          title: 'Why Properties Matter',
          text: 'Properties of addition are not just math tricks. They are rules that always work with every number. They help you check your work too. If you add 8 + 5 and get 13, you can turn it around: 5 + 8 should also be 13. If it is not, you know to try again. Properties also make mental math faster. When you shop at a store or count points in a game, you can rearrange and group numbers in your head to find totals quickly. The more you practice using properties, the more confident you will become.',
          keyVocabulary: ['check your work', 'mental math', 'confident', 'rules'],
        },
      ],
      practice: [
        { index: 0, question: 'If 4 + 9 = 13, what does 9 + 4 equal?', type: 'short-answer', correctAnswer: '13', hint: 'You can add in any order and get the same answer.', explanation: '9 + 4 = 13. The commutative property tells us the order does not change the sum.', standardCode: '1.OA.3' },
        { index: 1, question: 'What is the best way to group 7 + 3 + 6 to make a ten?', type: 'multiple-choice', options: ['(7 + 3) + 6', '7 + (3 + 6)', 'It does not matter'], correctAnswer: '(7 + 3) + 6', hint: 'Look for two numbers that add up to 10.', explanation: '7 + 3 = 10, then 10 + 6 = 16. Grouping 7 and 3 first makes a ten.', standardCode: '1.OA.3' },
        { index: 2, question: '5 + 8 + 5 = ? (Hint: look for friendly numbers)', type: 'short-answer', correctAnswer: '18', hint: '5 + 5 = 10, then add 8.', explanation: 'Rearrange: 5 + 5 + 8 = 10 + 8 = 18. Making a ten first makes it easy.', standardCode: '1.OA.3' },
        { index: 3, question: 'True or false: 6 + 2 = 2 + 6', type: 'multiple-choice', options: ['True', 'False'], correctAnswer: 'True', hint: 'Think about the commutative property.', explanation: 'True. The commutative property says you can switch the order and the sum stays the same.', standardCode: '1.OA.3' },
        { index: 4, question: 'Add: 3 + 4 + 7 = ?', type: 'fill-blank', correctAnswer: '14', hint: 'Try grouping 3 + 7 first to make 10.', explanation: '3 + 7 = 10, then 10 + 4 = 14. Grouping to make a ten is a handy strategy.', standardCode: '1.OA.3' },
      ],
      assessment: {
        questions: [
          { question: 'If 7 + 6 = 13, what is 6 + 7?', type: 'short-answer', correctAnswer: '13', standardCode: '1.OA.3' },
          { question: 'What is 8 + 2 + 9?', type: 'multiple-choice', options: ['17', '18', '19', '20'], correctAnswer: '19', standardCode: '1.OA.3' },
          { question: 'Which property says 5 + 3 = 3 + 5?', type: 'multiple-choice', options: ['Commutative property', 'Associative property', 'Subtraction property'], correctAnswer: 'Commutative property', standardCode: '1.OA.3' },
        ],
      },
    },
  },
  {
    slug: 'grade1-math-counting-fives-tens',
    title: 'Counting by Fives and Tens',
    description: 'Count to 120 starting from any number, counting by fives and tens',
    subject: 'math',
    grade: 1,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations in Base Ten',
    standardCodes: ['1.NBT.1'],
    content: {
      intro: {
        title: 'Counting by Fives and Tens',
        text: 'You already know how to count by ones. But what if you need to count a big pile of things really fast? Counting by fives and tens is like taking shortcuts on the number line! Today we will practice skip counting and learn to count all the way to 120.',
      },
      segments: [
        {
          index: 0,
          title: 'Counting by Tens',
          text: 'When you count by tens, you skip nine numbers each time. Start at 10 and keep adding 10: 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120. Notice the pattern: the ones digit is always 0 and the tens digit goes up by 1 each time. Counting by tens is great for counting groups that have ten items in each group, like egg cartons or bundles of sticks. If you have 8 bundles of ten sticks, you count 10, 20, 30, 40, 50, 60, 70, 80. That is 80 sticks!',
          keyVocabulary: ['skip counting', 'by tens', 'pattern', 'groups of ten'],
          example: 'Count 5 dimes (each worth 10 cents): 10, 20, 30, 40, 50 cents.',
        },
        {
          index: 1,
          title: 'Counting by Fives',
          text: 'When you count by fives, you skip four numbers each time. Start at 5 and add 5: 5, 10, 15, 20, 25, 30, 35, 40, 45, 50. Notice the pattern: the ones digit alternates between 5 and 0. Counting by fives is useful for counting nickels, fingers, and tally marks. Every time you count by fives, you are adding another group of five. If you keep going past 50, the pattern continues: 55, 60, 65, 70, 75, 80, and so on all the way up to 120.',
          keyVocabulary: ['by fives', 'alternates', 'nickels', 'tally marks'],
        },
        {
          index: 2,
          title: 'Starting from Any Number',
          text: 'You do not always have to start counting from 1 or from 0. You can start from any number! If you start at 37 and count by tens, you get: 37, 47, 57, 67, 77, 87, 97, 107, 117. See how the tens digit goes up by 1 but the ones digit stays at 7? If you start at 23 and count by fives, you get 23, 28, 33, 38, 43, 48. Starting from different numbers helps when you are adding on to a count you already started or figuring out patterns on a hundred chart.',
          keyVocabulary: ['start from any number', 'hundred chart', 'count on', 'pattern'],
          example: 'Start at 52 and count by tens: 52, 62, 72, 82, 92, 102, 112.',
        },
        {
          index: 3,
          title: 'Numbers Beyond 100',
          text: 'The numbers keep going past 100! After 100 comes 101, 102, 103, all the way to 120 and beyond. When you count by tens past 100, you get 100, 110, 120. When you count by fives past 100: 100, 105, 110, 115, 120. Three-digit numbers have a hundreds place, a tens place, and a ones place. The number 115 has 1 hundred, 1 ten, and 5 ones. Counting to 120 prepares you for working with bigger numbers in second grade. Practice counting forward from any number you choose!',
          keyVocabulary: ['beyond 100', 'three-digit number', 'hundreds place', '120'],
        },
      ],
      practice: [
        { index: 0, question: 'Count by tens. What comes after 60?', type: 'short-answer', correctAnswer: '70', hint: 'Add 10 to 60.', explanation: 'When counting by tens: 60, 70. The next number is 70.', standardCode: '1.NBT.1' },
        { index: 1, question: 'Count by fives: 5, 10, 15, 20, ___, 30.', type: 'fill-blank', correctAnswer: '25', hint: 'Add 5 to 20.', explanation: 'Counting by fives: 20 + 5 = 25. The missing number is 25.', standardCode: '1.NBT.1' },
        { index: 2, question: 'Start at 43. Count by tens. What are the next three numbers?', type: 'short-answer', correctAnswer: '53, 63, 73', hint: 'Add 10 each time. The ones digit stays the same.', explanation: '43, 53, 63, 73. Each time the tens digit increases by 1 and the ones stay at 3.', standardCode: '1.NBT.1' },
        { index: 3, question: 'What number comes after 100 when counting by tens?', type: 'multiple-choice', options: ['101', '110', '200', '105'], correctAnswer: '110', hint: 'Add 10 to 100.', explanation: '100 + 10 = 110. When counting by tens, the next number after 100 is 110.', standardCode: '1.NBT.1' },
        { index: 4, question: 'Count by fives starting at 75: 75, 80, 85, ___, 95.', type: 'fill-blank', correctAnswer: '90', hint: 'Add 5 to 85.', explanation: '85 + 5 = 90. Counting by fives: 75, 80, 85, 90, 95.', standardCode: '1.NBT.1' },
      ],
      assessment: {
        questions: [
          { question: 'Count by tens starting at 28. What is the third number you say?', type: 'short-answer', correctAnswer: '58', standardCode: '1.NBT.1' },
          { question: 'Which list shows counting by fives?', type: 'multiple-choice', options: ['5, 10, 15, 20, 25', '5, 10, 20, 25, 30', '5, 15, 20, 30, 35', '5, 10, 14, 19, 24'], correctAnswer: '5, 10, 15, 20, 25', standardCode: '1.NBT.1' },
          { question: 'What is the next number when counting by tens: 90, 100, ___?', type: 'short-answer', correctAnswer: '110', standardCode: '1.NBT.1' },
        ],
      },
    },
  },
  {
    slug: 'grade1-math-comparing-two-digit-numbers',
    title: 'Comparing Two-Digit Numbers',
    description: 'Compare two two-digit numbers using the symbols >, <, and =',
    subject: 'math',
    grade: 1,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations in Base Ten',
    standardCodes: ['1.NBT.3'],
    content: {
      intro: {
        title: 'Comparing Two-Digit Numbers',
        text: 'Is 47 bigger than 39? Is 52 the same as 52? Comparing numbers helps us figure out which is greater, which is less, or if two numbers are equal. Today we will learn to use special symbols to show how numbers compare to each other.',
      },
      segments: [
        {
          index: 0,
          title: 'Greater Than, Less Than, and Equal To',
          text: 'We use three special symbols to compare numbers. The greater-than symbol > points to the smaller number. The less-than symbol < also points to the smaller number. The equal sign = means the two numbers are the same. Think of the > and < symbols as a hungry alligator mouth that always wants to eat the bigger number. The open side faces the bigger number and the pointy side faces the smaller number. So 8 > 3 means eight is greater than three, and 3 < 8 means three is less than eight.',
          keyVocabulary: ['greater than', 'less than', 'equal to', 'symbol', 'compare'],
          example: '15 > 12 means fifteen is greater than twelve. 12 < 15 means twelve is less than fifteen.',
        },
        {
          index: 1,
          title: 'Comparing the Tens First',
          text: 'When comparing two-digit numbers, always look at the tens digit first. The number with more tens is greater. For example, compare 63 and 48. The tens digits are 6 and 4. Since 6 is greater than 4, we know 63 > 48 without even looking at the ones. If one number has 7 tens and another has 5 tens, the one with 7 tens is definitely bigger. The tens place tells you about groups of ten, which are worth much more than single ones. Always start your comparison at the tens digit!',
          keyVocabulary: ['tens digit', 'compare tens first', 'greater', 'bigger'],
        },
        {
          index: 2,
          title: 'When the Tens Are the Same',
          text: 'Sometimes two numbers have the same tens digit. When that happens, you compare the ones digit to decide which number is greater. Compare 54 and 57. Both have 5 tens, so look at the ones: 4 and 7. Since 7 is greater than 4, we know 57 > 54 and 54 < 57. Compare 31 and 38. Both have 3 tens. The ones are 1 and 8. Since 8 > 1, the number 38 is greater. If both the tens and the ones are the same, like 45 and 45, the numbers are equal: 45 = 45.',
          keyVocabulary: ['same tens', 'compare ones', 'equal', 'decide'],
          example: '72 and 76: same tens (7), compare ones: 2 < 6, so 72 < 76.',
        },
        {
          index: 3,
          title: 'Writing Comparison Sentences',
          text: 'A comparison sentence uses one of the three symbols to show the relationship between two numbers. To write one, put the first number on the left, the symbol in the middle, and the second number on the right. Ask yourself: is the first number bigger, smaller, or the same? Then pick the right symbol. For 89 and 91: 89 is less than 91, so write 89 < 91. For 55 and 55: they are the same, so write 55 = 55. Practice writing comparison sentences with numbers you see every day!',
          keyVocabulary: ['comparison sentence', 'relationship', 'pick the symbol'],
        },
      ],
      practice: [
        { index: 0, question: 'Compare: 34 ___ 56. Use >, <, or =.', type: 'short-answer', correctAnswer: '<', hint: 'Compare the tens digits first: 3 and 5.', explanation: '34 < 56. The tens digit 3 is less than 5, so 34 is less than 56.', standardCode: '1.NBT.3' },
        { index: 1, question: 'Compare: 78 ___ 72. Use >, <, or =.', type: 'short-answer', correctAnswer: '>', hint: 'The tens are the same. Compare the ones: 8 and 2.', explanation: '78 > 72. Same tens (7), but 8 ones is more than 2 ones.', standardCode: '1.NBT.3' },
        { index: 2, question: 'Which symbol makes this true: 45 ___ 45?', type: 'multiple-choice', options: ['>', '<', '='], correctAnswer: '=', hint: 'Are the numbers the same or different?', explanation: '45 = 45. Both the tens and ones are the same, so the numbers are equal.', standardCode: '1.NBT.3' },
        { index: 3, question: 'Which number is greater: 67 or 61?', type: 'short-answer', correctAnswer: '67', hint: 'The tens are the same. Compare the ones digits.', explanation: 'Both have 6 tens. 7 ones > 1 one, so 67 is greater than 61.', standardCode: '1.NBT.3' },
        { index: 4, question: 'Write a comparison: 29 ___ 83.', type: 'fill-blank', correctAnswer: '<', hint: 'Compare tens: 2 tens and 8 tens.', explanation: '29 < 83. Two tens is less than eight tens, so 29 is the smaller number.', standardCode: '1.NBT.3' },
      ],
      assessment: {
        questions: [
          { question: 'Compare: 91 ___ 89. Use >, <, or =.', type: 'short-answer', correctAnswer: '>', standardCode: '1.NBT.3' },
          { question: 'Which is less: 53 or 35?', type: 'multiple-choice', options: ['53', '35', 'They are equal'], correctAnswer: '35', standardCode: '1.NBT.3' },
          { question: 'Compare: 44 ___ 44. Use >, <, or =.', type: 'short-answer', correctAnswer: '=', standardCode: '1.NBT.3' },
        ],
      },
    },
  },
  {
    slug: 'grade1-math-shapes-attributes',
    title: 'Shapes and Their Attributes',
    description: 'Distinguish between defining and non-defining attributes of shapes',
    subject: 'math',
    grade: 1,
    gradeBand: 'k5',
    topicCluster: 'Geometry',
    standardCodes: ['1.G.1'],
    content: {
      intro: {
        title: 'Shapes and Their Attributes',
        text: 'Shapes are everywhere! Windows are rectangles, clocks are circles, and stop signs are octagons. But what makes a triangle a triangle? Today we will discover the special features of shapes and learn which features really matter when naming them.',
      },
      segments: [
        {
          index: 0,
          title: 'What Are Attributes?',
          text: 'Attributes are features that describe a shape. Some attributes are about the shape itself: how many sides it has, how many corners (vertices) it has, and whether the sides are straight or curved. Other attributes are about how the shape looks: its color, its size, or which way it is turned. The word attribute just means a quality or characteristic of the shape. Learning to notice different attributes helps us sort and name shapes correctly every time.',
          keyVocabulary: ['attributes', 'sides', 'corners', 'vertices', 'features'],
          example: 'A red square has attributes: 4 sides, 4 corners, red color, and a certain size.',
        },
        {
          index: 1,
          title: 'Defining Attributes',
          text: 'Defining attributes are the features a shape MUST have to be that shape. A triangle must have exactly 3 straight sides and 3 corners. If it does not have 3 sides, it is not a triangle, no matter what it looks like. A rectangle must have 4 sides and 4 square corners. A circle must be a closed curve with no corners and no straight sides. These rules never change. A triangle that is tiny and a triangle that is huge are both triangles because they both have 3 sides and 3 corners.',
          keyVocabulary: ['defining attributes', 'must have', 'triangle', 'rectangle', 'circle'],
          example: 'A shape with 4 equal sides and 4 square corners is always a square, no matter its color or size.',
        },
        {
          index: 2,
          title: 'Non-Defining Attributes',
          text: 'Non-defining attributes do NOT determine the name of a shape. Color is a non-defining attribute because a triangle can be red, blue, green, or any color and it is still a triangle. Size does not matter either: a small circle and a large circle are both circles. Orientation is also non-defining. A triangle pointing up and a triangle pointing down are both triangles. You can change non-defining attributes without changing the name of the shape. Only the defining attributes, like the number of sides and corners, determine what the shape is called.',
          keyVocabulary: ['non-defining attributes', 'color', 'size', 'orientation', 'does not matter'],
        },
        {
          index: 3,
          title: 'Sorting Shapes by Attributes',
          text: 'You can sort a group of shapes in many ways. Sort by the number of sides: put all triangles in one group and all rectangles in another. Sort by whether sides are straight or curved: circles in one group, polygons in another. You can also sort by non-defining attributes like color or size, but those groups will mix up different shape names. When you want to identify a shape, always focus on the defining attributes. Count the sides, count the corners, check if the sides are straight, and you will know exactly what shape it is.',
          keyVocabulary: ['sort', 'identify', 'polygon', 'straight sides', 'curved'],
          example: 'Sort by sides: 3 sides = triangles, 4 sides = quadrilaterals, 0 straight sides = circles.',
        },
      ],
      practice: [
        { index: 0, question: 'How many sides does a triangle have?', type: 'short-answer', correctAnswer: '3', hint: 'The word "tri" means three.', explanation: 'A triangle always has exactly 3 straight sides. This is a defining attribute.', standardCode: '1.G.1' },
        { index: 1, question: 'Which is a defining attribute of a rectangle?', type: 'multiple-choice', options: ['It is blue', 'It has 4 sides and 4 square corners', 'It is big', 'It is turned sideways'], correctAnswer: 'It has 4 sides and 4 square corners', hint: 'Which feature must a rectangle always have?', explanation: 'A rectangle must have 4 sides and 4 square corners. Color, size, and orientation are non-defining.', standardCode: '1.G.1' },
        { index: 2, question: 'A large red triangle and a small green triangle are both triangles. True or false?', type: 'multiple-choice', options: ['True', 'False'], correctAnswer: 'True', hint: 'Think about whether color and size are defining attributes.', explanation: 'True. Color and size are non-defining attributes. Both shapes have 3 sides and 3 corners, so both are triangles.', standardCode: '1.G.1' },
        { index: 3, question: 'Which is a non-defining attribute of a circle?', type: 'multiple-choice', options: ['It is round', 'It has no corners', 'It is purple', 'It has no straight sides'], correctAnswer: 'It is purple', hint: 'Which feature can change without changing the shape name?', explanation: 'Color is a non-defining attribute. A circle can be any color and still be a circle.', standardCode: '1.G.1' },
        { index: 4, question: 'A shape has 4 sides and 4 corners. Two sides are long and two sides are short. What shape is it?', type: 'fill-blank', correctAnswer: 'rectangle', hint: 'Count the sides and corners. Think about shapes with 4 sides.', explanation: 'A shape with 4 sides, 4 square corners, and sides of two different lengths is a rectangle.', standardCode: '1.G.1' },
      ],
      assessment: {
        questions: [
          { question: 'How many corners does a rectangle have?', type: 'short-answer', correctAnswer: '4', standardCode: '1.G.1' },
          { question: 'Which is NOT a defining attribute of a triangle?', type: 'multiple-choice', options: ['3 sides', '3 corners', 'Straight sides', 'Yellow color'], correctAnswer: 'Yellow color', standardCode: '1.G.1' },
          { question: 'A shape is round, has no straight sides, and no corners. What shape is it?', type: 'short-answer', correctAnswer: 'circle', standardCode: '1.G.1' },
        ],
      },
    },
  },
]
