import type { ModuleSeed } from '../types'

export const GRADE_2_MATH: ModuleSeed[] = [
  {
    slug: 'grade2-math-three-digit-place-value',
    title: 'Three-Digit Numbers: Hundreds, Tens, Ones',
    description: 'Understand that the three digits of a three-digit number represent amounts of hundreds, tens, and ones',
    subject: 'math',
    grade: 2,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations in Base Ten',
    standardCodes: ['2.NBT.1'],
    content: {
      intro: {
        title: 'Three-Digit Numbers: Hundreds, Tens, Ones',
        text: 'You already know about ones and tens. Now it is time to learn about hundreds! When we put hundreds, tens, and ones together, we can make three-digit numbers all the way up to 999. Understanding place value helps us read, write, and compare big numbers.',
      },
      segments: [
        {
          index: 0,
          title: 'What Is a Hundred?',
          text: 'A hundred is a bundle of ten tens. If you have 10 groups of 10 blocks, you have 100 blocks in all. We write 100 with a 1 in the hundreds place, a 0 in the tens place, and a 0 in the ones place. Think of a flat square made of 100 tiny unit cubes — that is one hundred. Two of those flats give you 200, three give you 300, and so on up to 900. Hundreds are the biggest part of a three-digit number, so the hundreds digit is on the left.',
          keyVocabulary: ['hundred', 'place value', 'digit', 'bundle'],
          example: '10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 = 100',
        },
        {
          index: 1,
          title: 'Hundreds, Tens, and Ones Together',
          text: 'Every three-digit number has three places. The number 352 has 3 hundreds, 5 tens, and 2 ones. That means 300 + 50 + 2 = 352. We call this expanded form. The digit on the left tells us how many hundreds, the middle digit tells us how many tens, and the digit on the right tells us how many ones. When you read a three-digit number, start with the hundreds, then the tens, then the ones.',
          keyVocabulary: ['expanded form', 'hundreds place', 'tens place', 'ones place'],
          example: '476 = 400 + 70 + 6 → 4 hundreds, 7 tens, 6 ones',
        },
        {
          index: 2,
          title: 'Reading and Writing Three-Digit Numbers',
          text: 'To read a three-digit number, say the hundreds part first, then the rest. For 815, say "eight hundred fifteen." To write a number from words, think about each place. "Five hundred thirty-nine" means 5 hundreds, 3 tens, and 9 ones, so we write 539. Practice by picking any three-digit number and breaking it into hundreds, tens, and ones.',
          keyVocabulary: ['three-digit number', 'read', 'write', 'word form'],
        },
        {
          index: 3,
          title: 'Comparing Three-Digit Numbers',
          text: 'To compare two three-digit numbers, start with the hundreds place. The number with more hundreds is greater. If the hundreds are the same, compare the tens. If the tens are also the same, compare the ones. We use the symbols > (greater than), < (less than), and = (equal to). For example, 482 > 479 because both have 4 hundreds and 8 tens vs 7 tens, so 482 is greater.',
          keyVocabulary: ['compare', 'greater than', 'less than', 'equal to'],
          example: '365 < 372 because 6 tens < 7 tens (hundreds are the same)',
        },
      ],
      practice: [
        { index: 0, question: 'How many hundreds are in the number 738?', type: 'short-answer', correctAnswer: '7', hint: 'The hundreds digit is the one on the far left.', explanation: 'In 738, the digit 7 is in the hundreds place, so there are 7 hundreds.', standardCode: '2.NBT.1' },
        { index: 1, question: 'What is the expanded form of 254?', type: 'multiple-choice', options: ['200 + 50 + 4', '200 + 54', '2 + 5 + 4', '25 + 4'], correctAnswer: '200 + 50 + 4', hint: 'Break each digit into hundreds, tens, and ones.', explanation: '254 = 200 + 50 + 4 because there are 2 hundreds, 5 tens, and 4 ones.', standardCode: '2.NBT.1' },
        { index: 2, question: 'What number has 6 hundreds, 0 tens, and 3 ones?', type: 'short-answer', correctAnswer: '603', hint: 'Put a 6 in the hundreds place, a 0 in the tens place, and a 3 in the ones place.', explanation: '6 hundreds = 600, 0 tens = 0, 3 ones = 3. So the number is 603.', standardCode: '2.NBT.1' },
        { index: 3, question: 'Which number is greater: 519 or 521?', type: 'multiple-choice', options: ['519', '521', 'They are equal'], correctAnswer: '521', hint: 'Both have 5 hundreds. Compare the tens digits.', explanation: 'Both numbers have 5 hundreds. 519 has 1 ten and 521 has 2 tens. Since 2 tens > 1 ten, 521 is greater.', standardCode: '2.NBT.1' },
        { index: 4, question: 'Write the number for "nine hundred forty-six" using digits.', type: 'fill-blank', correctAnswer: '946', hint: 'Nine hundred means 9 in the hundreds place. Forty means 4 in the tens place.', explanation: 'Nine hundred forty-six = 900 + 40 + 6 = 946.', standardCode: '2.NBT.1' },
      ],
      assessment: {
        questions: [
          { question: 'What is the value of the digit 8 in the number 837?', type: 'multiple-choice', options: ['8', '80', '800', '8000'], correctAnswer: '800', standardCode: '2.NBT.1' },
          { question: 'Write the expanded form of 490.', type: 'short-answer', correctAnswer: '400 + 90 + 0', standardCode: '2.NBT.1' },
          { question: 'Which symbol goes in the blank: 672 ___ 627?', type: 'multiple-choice', options: ['>', '<', '='], correctAnswer: '>', standardCode: '2.NBT.1' },
        ],
      },
    },
  },
  {
    slug: 'grade2-math-addition-within-1000',
    title: 'Addition Within 1000',
    description: 'Fluently add within 100 and add up to three-digit numbers using strategies based on place value',
    subject: 'math',
    grade: 2,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations in Base Ten',
    standardCodes: ['2.NBT.5', '2.NBT.7'],
    content: {
      intro: {
        title: 'Addition Within 1000',
        text: 'You have been adding small numbers for a while. Now you are ready to add bigger numbers — even numbers in the hundreds! We will use what we know about place value to add ones to ones, tens to tens, and hundreds to hundreds. Sometimes we need to regroup, which means trading ten ones for one ten or ten tens for one hundred.',
      },
      segments: [
        {
          index: 0,
          title: 'Adding Two-Digit Numbers',
          text: 'When adding two-digit numbers like 45 + 37, start by adding the ones: 5 + 7 = 12. Since 12 ones is more than 9, we regroup 10 ones into 1 ten and keep 2 ones. Now add the tens: 4 + 3 = 7, plus the 1 ten we carried over makes 8 tens. The answer is 82. Always line up the digits by place value so you add ones with ones and tens with tens.',
          keyVocabulary: ['add', 'regroup', 'carry', 'sum'],
          example: '45 + 37: ones → 5 + 7 = 12 (write 2, carry 1), tens → 4 + 3 + 1 = 8. Answer: 82',
        },
        {
          index: 1,
          title: 'Adding Three-Digit Numbers',
          text: 'Adding three-digit numbers works the same way, but now we have a hundreds column too. For 263 + 154, add the ones first: 3 + 4 = 7. Then the tens: 6 + 5 = 11 tens. Regroup 10 tens into 1 hundred and keep 1 ten. Finally the hundreds: 2 + 1 + 1 = 4 hundreds. The sum is 417. Always start from the ones place and work left.',
          keyVocabulary: ['three-digit', 'hundreds column', 'place value', 'regroup'],
          example: '263 + 154 = 417',
        },
        {
          index: 2,
          title: 'Mental Math Strategies',
          text: 'You do not always need paper to add. Try breaking numbers apart. To add 48 + 35, think 48 + 30 = 78, then 78 + 5 = 83. Or make a friendly number: 48 + 2 = 50, then 50 + 33 = 83. Another strategy is to add hundreds, then tens, then ones separately. For 230 + 150, think 200 + 100 = 300, 30 + 50 = 80, so the answer is 380. Pick the strategy that feels easiest for you!',
          keyVocabulary: ['mental math', 'break apart', 'friendly number', 'strategy'],
        },
      ],
      practice: [
        { index: 0, question: 'What is 56 + 38?', type: 'short-answer', correctAnswer: '94', hint: 'Add the ones first: 6 + 8 = 14. Regroup and then add the tens.', explanation: 'Ones: 6 + 8 = 14, write 4 carry 1. Tens: 5 + 3 + 1 = 9. The answer is 94.', standardCode: '2.NBT.5' },
        { index: 1, question: 'What is 345 + 237?', type: 'short-answer', correctAnswer: '582', hint: 'Add ones, then tens, then hundreds. Remember to regroup when needed.', explanation: 'Ones: 5 + 7 = 12 (write 2, carry 1). Tens: 4 + 3 + 1 = 8. Hundreds: 3 + 2 = 5. Answer: 582.', standardCode: '2.NBT.7' },
        { index: 2, question: 'Which is the sum of 400 + 350?', type: 'multiple-choice', options: ['650', '700', '750', '800'], correctAnswer: '750', hint: 'Add the hundreds: 400 + 300 = 700. Then add 50 more.', explanation: '400 + 350 = 400 + 300 + 50 = 750.', standardCode: '2.NBT.7' },
        { index: 3, question: '67 + ___ = 100', type: 'fill-blank', correctAnswer: '33', hint: 'Think: what do I add to 67 to get to 100?', explanation: '100 − 67 = 33. So 67 + 33 = 100.', standardCode: '2.NBT.5' },
        { index: 4, question: 'What is 199 + 256?', type: 'short-answer', correctAnswer: '455', hint: 'Try thinking of 199 as 200 − 1. Then add 200 + 256 and subtract 1.', explanation: '199 + 256: ones 9 + 6 = 15 (write 5, carry 1), tens 9 + 5 + 1 = 15 (write 5, carry 1), hundreds 1 + 2 + 1 = 4. Answer: 455.', standardCode: '2.NBT.7' },
      ],
      assessment: {
        questions: [
          { question: 'What is 73 + 49?', type: 'short-answer', correctAnswer: '122', standardCode: '2.NBT.5' },
          { question: 'What is 528 + 347?', type: 'short-answer', correctAnswer: '875', standardCode: '2.NBT.7' },
          { question: 'Which is the sum of 605 + 295?', type: 'multiple-choice', options: ['800', '890', '900', '910'], correctAnswer: '900', standardCode: '2.NBT.7' },
        ],
      },
    },
  },
  {
    slug: 'grade2-math-subtraction-within-1000',
    title: 'Subtraction Within 1000',
    description: 'Fluently subtract within 100 and subtract up to three-digit numbers using strategies based on place value',
    subject: 'math',
    grade: 2,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations in Base Ten',
    standardCodes: ['2.NBT.5', '2.NBT.7'],
    content: {
      intro: {
        title: 'Subtraction Within 1000',
        text: 'Subtraction tells us how much is left or how much more one number is than another. Now that you can subtract small numbers, it is time to subtract bigger ones — even three-digit numbers! We will use place value and regrouping to help us take away hundreds, tens, and ones.',
      },
      segments: [
        {
          index: 0,
          title: 'Subtracting Two-Digit Numbers',
          text: 'To subtract 82 − 47, start with the ones. We need to take 7 from 2, but 2 is smaller than 7! So we regroup: borrow 1 ten from the 8 tens to make 12 ones. Now 12 − 7 = 5 ones. The tens column is now 7 − 4 = 3 tens. The answer is 35. Regrouping means trading 1 ten for 10 ones so we have enough to subtract.',
          keyVocabulary: ['subtract', 'regroup', 'borrow', 'difference'],
          example: '82 − 47: ones → 12 − 7 = 5, tens → 7 − 4 = 3. Answer: 35',
        },
        {
          index: 1,
          title: 'Subtracting Three-Digit Numbers',
          text: 'With three-digit numbers, we subtract ones first, then tens, then hundreds — just like addition but taking away. For 534 − 261, ones: 4 − 1 = 3. Tens: 3 − 6 — we cannot do that, so we regroup 1 hundred to get 13 tens. Now 13 − 6 = 7 tens. Hundreds: 4 − 2 = 2. The difference is 273. Always check: does your answer plus the number you subtracted equal the number you started with?',
          keyVocabulary: ['three-digit', 'difference', 'hundreds', 'check'],
          example: '534 − 261 = 273. Check: 273 + 261 = 534 ✓',
        },
        {
          index: 2,
          title: 'Subtracting Across Zeros',
          text: 'Sometimes you need to subtract from a number that has zeros, like 500 − 184. You cannot take 4 from 0 ones, and you cannot borrow from 0 tens either! First borrow 1 hundred to make 10 tens. Then borrow 1 ten to make 10 ones. Now subtract: 10 − 4 = 6 ones, 9 − 8 = 1 ten, 4 − 1 = 3 hundreds. The answer is 316. Subtracting across zeros takes extra steps, but go slowly and you will get it right.',
          keyVocabulary: ['zero', 'borrow across', 'regroup twice', 'careful'],
          example: '500 − 184 = 316',
        },
      ],
      practice: [
        { index: 0, question: 'What is 93 − 58?', type: 'short-answer', correctAnswer: '35', hint: 'You will need to regroup because 3 is less than 8.', explanation: 'Ones: regroup to get 13 − 8 = 5. Tens: 8 − 5 = 3. Answer: 35.', standardCode: '2.NBT.5' },
        { index: 1, question: 'What is 746 − 283?', type: 'short-answer', correctAnswer: '463', hint: 'Start with the ones, then tens, then hundreds. Regroup when the top digit is smaller.', explanation: 'Ones: 6 − 3 = 3. Tens: 4 − 8 → regroup to 14 − 8 = 6. Hundreds: 6 − 2 = 4. Answer: 463.', standardCode: '2.NBT.7' },
        { index: 2, question: 'What is 600 − 275?', type: 'short-answer', correctAnswer: '325', hint: 'You will need to borrow across the zeros. Start by regrouping from the hundreds.', explanation: 'Regroup 600 → 5 hundreds, 9 tens, 10 ones. 10 − 5 = 5, 9 − 7 = 2, 5 − 2 = 3. Answer: 325.', standardCode: '2.NBT.7' },
        { index: 3, question: 'Which is the difference of 85 − 37?', type: 'multiple-choice', options: ['42', '48', '52', '58'], correctAnswer: '48', hint: 'Regroup: 15 − 7 = 8 ones, then 7 − 3 = 4 tens.', explanation: 'Ones: 15 − 7 = 8. Tens: 7 − 3 = 4. The difference is 48.', standardCode: '2.NBT.5' },
        { index: 4, question: '400 − ___ = 150', type: 'fill-blank', correctAnswer: '250', hint: 'Think: what number added to 150 equals 400?', explanation: '400 − 150 = 250. Check: 150 + 250 = 400.', standardCode: '2.NBT.7' },
      ],
      assessment: {
        questions: [
          { question: 'What is 71 − 36?', type: 'short-answer', correctAnswer: '35', standardCode: '2.NBT.5' },
          { question: 'What is 903 − 467?', type: 'short-answer', correctAnswer: '436', standardCode: '2.NBT.7' },
          { question: 'Which is the difference of 800 − 555?', type: 'multiple-choice', options: ['235', '245', '255', '345'], correctAnswer: '245', standardCode: '2.NBT.7' },
        ],
      },
    },
  },
  {
    slug: 'grade2-math-skip-counting',
    title: 'Skip Counting',
    description: 'Count within 1000 by skip counting by 5s, 10s, and 100s',
    subject: 'math',
    grade: 2,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations in Base Ten',
    standardCodes: ['2.NBT.2'],
    content: {
      intro: {
        title: 'Skip Counting by 5s, 10s, and 100s',
        text: 'Skip counting means counting forward by jumping over numbers in equal steps. Instead of counting 1, 2, 3, 4, 5, you can skip and say 5, 10, 15, 20! Skip counting helps you count large groups of things quickly and gets you ready for multiplication.',
      },
      segments: [
        {
          index: 0,
          title: 'Skip Counting by 5s',
          text: 'When we skip count by 5s, we add 5 each time: 5, 10, 15, 20, 25, 30, and so on. Notice the pattern — the ones digit alternates between 5 and 0. Every number that ends in 5 or 0 is in the count-by-5s pattern. This is very useful for counting nickels, because each nickel is worth 5 cents. If you have 7 nickels, count by 5s: 5, 10, 15, 20, 25, 30, 35 — that is 35 cents!',
          keyVocabulary: ['skip count', 'by fives', 'pattern', 'nickel'],
          example: '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
        },
        {
          index: 1,
          title: 'Skip Counting by 10s',
          text: 'Counting by 10s is one of the easiest patterns. Start at 10 and keep adding 10: 10, 20, 30, 40, 50, 60, 70, 80, 90, 100. The ones digit is always 0! You can also start at any number. Starting at 3 and counting by 10s gives 3, 13, 23, 33, 43. See how the tens digit goes up by 1 each time but the ones digit stays the same? Counting by 10s helps you count dimes — each dime is 10 cents.',
          keyVocabulary: ['by tens', 'dime', 'tens digit', 'ones digit'],
          example: 'Starting at 40: 40, 50, 60, 70, 80, 90, 100',
        },
        {
          index: 2,
          title: 'Skip Counting by 100s',
          text: 'Counting by 100s takes big jumps: 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000. Each jump adds another hundred. You can also start from a number that is not a multiple of 100. Starting at 25 and counting by 100s gives 25, 125, 225, 325, 425. The hundreds digit goes up by 1 each time, while the tens and ones digits stay the same.',
          keyVocabulary: ['by hundreds', 'hundreds digit', 'one thousand', 'jump'],
          example: '100, 200, 300, 400, 500, 600, 700, 800, 900, 1000',
        },
        {
          index: 3,
          title: 'Skip Counting from Any Starting Number',
          text: 'You can start skip counting from any number, not just from zero. If you start at 220 and count by 5s, you get 220, 225, 230, 235, 240. If you start at 350 and count by 100s, you get 350, 450, 550, 650, 750. The key is to always add the same amount each time. Practice by picking a starting number and a skip number, then see how far you can go!',
          keyVocabulary: ['starting number', 'equal jumps', 'continue the pattern'],
        },
      ],
      practice: [
        { index: 0, question: 'Fill in the blank: 15, 20, 25, ___, 35', type: 'fill-blank', correctAnswer: '30', hint: 'We are counting by 5s. What is 25 + 5?', explanation: 'Counting by 5s: 25 + 5 = 30. The pattern is 15, 20, 25, 30, 35.', standardCode: '2.NBT.2' },
        { index: 1, question: 'What comes next? 460, 470, 480, ___', type: 'fill-blank', correctAnswer: '490', hint: 'We are counting by 10s.', explanation: 'Counting by 10s: 480 + 10 = 490.', standardCode: '2.NBT.2' },
        { index: 2, question: 'Count by 100s: 300, 400, 500, ___', type: 'fill-blank', correctAnswer: '600', hint: 'Add 100 to 500.', explanation: '500 + 100 = 600. Counting by 100s: 300, 400, 500, 600.', standardCode: '2.NBT.2' },
        { index: 3, question: 'Which list shows skip counting by 5s?', type: 'multiple-choice', options: ['3, 6, 9, 12', '5, 10, 15, 20', '2, 4, 6, 8', '10, 20, 30, 40'], correctAnswer: '5, 10, 15, 20', hint: 'Look for the list where each number is 5 more than the one before.', explanation: '5, 10, 15, 20 — each number is 5 more than the last, so this is counting by 5s.', standardCode: '2.NBT.2' },
        { index: 4, question: 'Start at 55 and count by 10s. What are the next three numbers?', type: 'short-answer', correctAnswer: '65, 75, 85', hint: 'Add 10 each time: 55 + 10 = ?', explanation: '55 + 10 = 65, 65 + 10 = 75, 75 + 10 = 85.', standardCode: '2.NBT.2' },
      ],
      assessment: {
        questions: [
          { question: 'Fill in the blank: 550, 600, 650, ___', type: 'short-answer', correctAnswer: '700', standardCode: '2.NBT.2' },
          { question: 'What is the next number when counting by 100s? 120, 220, 320, ___', type: 'short-answer', correctAnswer: '420', standardCode: '2.NBT.2' },
          { question: 'Which pattern shows counting by 10s?', type: 'multiple-choice', options: ['5, 15, 25, 35', '10, 20, 30, 40', '100, 200, 300, 400', '3, 6, 9, 12'], correctAnswer: '10, 20, 30, 40', standardCode: '2.NBT.2' },
        ],
      },
    },
  },
  {
    slug: 'grade2-math-shapes-attributes',
    title: 'Shapes and Their Attributes',
    description: 'Recognize and draw shapes having specified attributes such as number of angles and faces',
    subject: 'math',
    grade: 2,
    gradeBand: 'k5',
    topicCluster: 'Geometry',
    standardCodes: ['2.G.1'],
    content: {
      intro: {
        title: 'Shapes and Their Attributes',
        text: 'Shapes are everywhere — in windows, signs, books, and buildings. In second grade, we look closely at what makes each shape special. We count sides, angles, and faces. Knowing the attributes of shapes helps us name them, describe them, and draw them correctly.',
      },
      segments: [
        {
          index: 0,
          title: 'Sides and Angles',
          text: 'A side is a straight line that forms part of a shape. An angle is the corner where two sides meet. A triangle has 3 sides and 3 angles. A quadrilateral has 4 sides and 4 angles. A pentagon has 5 sides and 5 angles, and a hexagon has 6 sides and 6 angles. The number of sides always matches the number of angles. When you look at a shape, count the sides first, then count the corners — they should be the same number!',
          keyVocabulary: ['side', 'angle', 'triangle', 'quadrilateral', 'pentagon', 'hexagon'],
          example: 'A stop sign is a shape with 8 sides — it is an octagon!',
        },
        {
          index: 1,
          title: 'Types of Quadrilaterals',
          text: 'A quadrilateral is any shape with exactly 4 sides. But not all quadrilaterals look the same! A square has 4 equal sides and 4 square corners called right angles. A rectangle has 4 right angles too, but only the opposite sides are equal. A rhombus has 4 equal sides but its angles might not be right angles. A trapezoid has exactly one pair of parallel sides. All of these shapes are quadrilaterals because they all have 4 sides.',
          keyVocabulary: ['square', 'rectangle', 'rhombus', 'trapezoid', 'right angle', 'parallel'],
        },
        {
          index: 2,
          title: 'Drawing Shapes from Attributes',
          text: 'You can draw a shape when someone tells you its attributes. If they say "draw a shape with 3 sides and 3 angles," you draw a triangle. If they say "draw a quadrilateral with all equal sides and 4 right angles," you draw a square. When drawing, use a ruler to make straight sides. Count your sides and angles when you finish to make sure your shape matches the description. Practice drawing triangles, rectangles, pentagons, and hexagons.',
          keyVocabulary: ['draw', 'attributes', 'ruler', 'describe'],
        },
        {
          index: 3,
          title: 'Faces and Solid Shapes',
          text: 'Flat shapes like circles and squares are two-dimensional. Solid shapes like cubes and spheres are three-dimensional — they take up space. A cube has 6 flat faces, and each face is a square. A rectangular prism, like a cereal box, also has 6 faces, but they are rectangles. A cylinder, like a soup can, has 2 flat circular faces and 1 curved surface. We describe solid shapes by their faces, edges, and vertices.',
          keyVocabulary: ['face', 'cube', 'rectangular prism', 'cylinder', 'three-dimensional', 'edge', 'vertex'],
        },
      ],
      practice: [
        { index: 0, question: 'How many sides does a pentagon have?', type: 'short-answer', correctAnswer: '5', hint: 'The prefix "penta" means five.', explanation: 'A pentagon has 5 sides and 5 angles.', standardCode: '2.G.1' },
        { index: 1, question: 'Which shape has 4 equal sides and 4 right angles?', type: 'multiple-choice', options: ['Rectangle', 'Rhombus', 'Square', 'Trapezoid'], correctAnswer: 'Square', hint: 'It has all equal sides AND all right angles.', explanation: 'A square has 4 equal sides and 4 right angles. A rectangle has right angles but sides are not all equal. A rhombus has equal sides but angles may not be right angles.', standardCode: '2.G.1' },
        { index: 2, question: 'How many faces does a cube have?', type: 'short-answer', correctAnswer: '6', hint: 'Think about a die or a block. Count the top, bottom, front, back, left, and right.', explanation: 'A cube has 6 faces: top, bottom, front, back, left, and right.', standardCode: '2.G.1' },
        { index: 3, question: 'A shape has 6 sides and 6 angles. What is it called?', type: 'fill-blank', correctAnswer: 'hexagon', hint: 'The prefix "hexa" means six.', explanation: 'A hexagon is a shape with 6 sides and 6 angles.', standardCode: '2.G.1' },
        { index: 4, question: 'Which of these is NOT a quadrilateral?', type: 'multiple-choice', options: ['Square', 'Triangle', 'Rectangle', 'Trapezoid'], correctAnswer: 'Triangle', hint: 'A quadrilateral must have exactly 4 sides.', explanation: 'A triangle has 3 sides, not 4, so it is not a quadrilateral.', standardCode: '2.G.1' },
      ],
      assessment: {
        questions: [
          { question: 'How many angles does a triangle have?', type: 'short-answer', correctAnswer: '3', standardCode: '2.G.1' },
          { question: 'Which solid shape has 2 circular faces and 1 curved surface?', type: 'multiple-choice', options: ['Cube', 'Sphere', 'Cylinder', 'Cone'], correctAnswer: 'Cylinder', standardCode: '2.G.1' },
          { question: 'A rectangle has ___ right angles.', type: 'short-answer', correctAnswer: '4', standardCode: '2.G.1' },
        ],
      },
    },
  },
  {
    slug: 'grade2-math-partitioning-equal-shares',
    title: 'Partitioning into Equal Shares',
    description: 'Partition circles and rectangles into two, three, or four equal shares and describe them as halves, thirds, and fourths',
    subject: 'math',
    grade: 2,
    gradeBand: 'k5',
    topicCluster: 'Geometry',
    standardCodes: ['2.G.3'],
    content: {
      intro: {
        title: 'Partitioning into Equal Shares',
        text: 'Have you ever shared a pizza or a sandwich equally with friends? When we cut something into equal parts, we are partitioning. In second grade, we learn to split shapes into halves, thirds, and fourths. These equal shares are the beginning of fractions!',
      },
      segments: [
        {
          index: 0,
          title: 'Halves — Two Equal Parts',
          text: 'When you split a shape into 2 equal parts, each part is called a half. Two halves make a whole. You can cut a circle in half by drawing a line through the middle. You can cut a rectangle in half by drawing a line from top to bottom or from side to side. The important rule is that both parts must be the same size. If one part is bigger than the other, the shape is NOT split into halves.',
          keyVocabulary: ['half', 'halves', 'equal parts', 'whole', 'partition'],
          example: 'A sandwich cut straight down the middle gives 2 halves.',
        },
        {
          index: 1,
          title: 'Thirds — Three Equal Parts',
          text: 'When you split a shape into 3 equal parts, each part is called a third. Three thirds make a whole. To cut a rectangle into thirds, draw two lines that divide it into three pieces that are all the same size. Sharing a pizza equally among 3 friends means each person gets one third. Each piece must be the same size for the shares to be fair and equal.',
          keyVocabulary: ['third', 'thirds', 'three equal parts', 'fair share'],
          example: 'A rectangular cake cut into 3 equal slices — each slice is one third.',
        },
        {
          index: 2,
          title: 'Fourths — Four Equal Parts',
          text: 'When you split a shape into 4 equal parts, each part is called a fourth or a quarter. Four fourths make a whole. To split a rectangle into fourths, you can draw one line across and one line down, making a grid of 4 equal boxes. A circle can be split into fourths by drawing two lines through the center that cross each other. A quarter of a dollar is called that because it is one fourth of a dollar!',
          keyVocabulary: ['fourth', 'quarter', 'fourths', 'four equal parts'],
          example: 'Fold a piece of paper in half, then in half again — you get 4 fourths!',
        },
        {
          index: 3,
          title: 'Comparing Equal Shares',
          text: 'Here is a key idea: the more equal parts you make, the smaller each part is! A half of a cookie is bigger than a third of the same cookie, and a third is bigger than a fourth. This happens because you are sharing the same whole among more people. Also, equal shares of the same whole do not have to be the same shape. You can cut a rectangle into 2 halves with a horizontal line or a vertical line — both ways give equal halves even though the pieces look different.',
          keyVocabulary: ['compare', 'smaller parts', 'more shares', 'same whole'],
        },
      ],
      practice: [
        { index: 0, question: 'If a circle is split into 2 equal parts, what is each part called?', type: 'multiple-choice', options: ['A third', 'A half', 'A fourth', 'A whole'], correctAnswer: 'A half', hint: 'Two equal parts means each part is one out of two.', explanation: 'When a shape is split into 2 equal parts, each part is called a half.', standardCode: '2.G.3' },
        { index: 1, question: 'How many thirds make a whole?', type: 'short-answer', correctAnswer: '3', hint: 'A third is one of three equal parts.', explanation: 'It takes 3 thirds to make one whole, because the whole was split into 3 equal parts.', standardCode: '2.G.3' },
        { index: 2, question: 'A rectangle is cut into 4 equal pieces. What is each piece called?', type: 'fill-blank', correctAnswer: 'a fourth', hint: 'Four equal parts means each part is one out of four.', explanation: 'When a shape is cut into 4 equal parts, each part is called a fourth (or a quarter).', standardCode: '2.G.3' },
        { index: 3, question: 'Which is bigger: one half of a pizza or one fourth of the same pizza?', type: 'multiple-choice', options: ['One half', 'One fourth', 'They are the same size'], correctAnswer: 'One half', hint: 'When you share among fewer people, each person gets a bigger piece.', explanation: 'One half is bigger because you are only splitting the pizza into 2 parts instead of 4. Fewer parts means each part is larger.', standardCode: '2.G.3' },
        { index: 4, question: 'Sam cut a rectangle into 3 pieces, but one piece is much bigger than the others. Did Sam make thirds?', type: 'multiple-choice', options: ['Yes, because there are 3 pieces', 'No, because the pieces are not equal'], correctAnswer: 'No, because the pieces are not equal', hint: 'Thirds means 3 EQUAL parts.', explanation: 'Thirds means 3 equal parts. If the pieces are different sizes, they are not thirds.', standardCode: '2.G.3' },
      ],
      assessment: {
        questions: [
          { question: 'How many fourths make a whole?', type: 'short-answer', correctAnswer: '4', standardCode: '2.G.3' },
          { question: 'Which is the smallest piece: one half, one third, or one fourth of the same shape?', type: 'multiple-choice', options: ['One half', 'One third', 'One fourth'], correctAnswer: 'One fourth', standardCode: '2.G.3' },
          { question: 'A circle is split into 3 equal parts. What is each part called?', type: 'short-answer', correctAnswer: 'a third', standardCode: '2.G.3' },
        ],
      },
    },
  },
  {
    slug: 'grade2-math-even-odd-numbers',
    title: 'Even and Odd Numbers',
    description: 'Determine whether a group of objects (up to 20) has an odd or even number of members',
    subject: 'math',
    grade: 2,
    gradeBand: 'k5',
    topicCluster: 'Operations & Algebraic Thinking',
    standardCodes: ['2.OA.3'],
    content: {
      intro: {
        title: 'Even and Odd Numbers',
        text: 'Some numbers can be split into two equal groups with nothing left over. Those are called even numbers. Other numbers always have one left over when you try to make two equal groups. Those are called odd numbers. Learning about even and odd helps you pair things up and understand patterns in numbers.',
      },
      segments: [
        {
          index: 0,
          title: 'What Are Even Numbers?',
          text: 'A number is even if you can put all the objects into pairs with none left over. The numbers 2, 4, 6, 8, 10, 12, 14, 16, 18, and 20 are all even. When you have an even number of objects, you can split them into two equal groups. For example, 8 apples can be split into two groups of 4. Even numbers always end in 0, 2, 4, 6, or 8.',
          keyVocabulary: ['even', 'pair', 'equal groups', 'none left over'],
          example: '6 socks can be made into 3 pairs with none left over, so 6 is even.',
        },
        {
          index: 1,
          title: 'What Are Odd Numbers?',
          text: 'A number is odd if, when you try to pair up the objects, there is always one left over. The numbers 1, 3, 5, 7, 9, 11, 13, 15, 17, and 19 are all odd. If you have 7 blocks and try to make two equal groups, you get 3 and 3 with 1 left over. Odd numbers always end in 1, 3, 5, 7, or 9.',
          keyVocabulary: ['odd', 'one left over', 'not equal groups'],
          example: '9 crayons: you can make pairs of 2, 2, 2, 2 but 1 is left over, so 9 is odd.',
        },
        {
          index: 2,
          title: 'Patterns with Even and Odd',
          text: 'Even and odd numbers make a pattern: even, odd, even, odd, even, odd. Starting from 1: odd, even, odd, even. When you add two even numbers, the answer is always even (4 + 6 = 10). When you add two odd numbers, the answer is also even (3 + 5 = 8). When you add an even and an odd number, the answer is always odd (4 + 3 = 7). These patterns are always true!',
          keyVocabulary: ['pattern', 'even + even', 'odd + odd', 'even + odd'],
        },
      ],
      practice: [
        { index: 0, question: 'Is 14 even or odd?', type: 'multiple-choice', options: ['Even', 'Odd'], correctAnswer: 'Even', hint: 'Look at the ones digit. Does 14 end in 0, 2, 4, 6, or 8?', explanation: '14 ends in 4, so it is even. You can also make 7 pairs from 14 objects.', standardCode: '2.OA.3' },
        { index: 1, question: 'Is 11 even or odd?', type: 'multiple-choice', options: ['Even', 'Odd'], correctAnswer: 'Odd', hint: 'Try to pair up 11 objects. Is there one left over?', explanation: '11 ends in 1, so it is odd. 11 objects make 5 pairs with 1 left over.', standardCode: '2.OA.3' },
        { index: 2, question: 'You have 16 grapes. Can you split them into two equal groups with none left over?', type: 'multiple-choice', options: ['Yes', 'No'], correctAnswer: 'Yes', hint: '16 is even. Even numbers split into two equal groups.', explanation: '16 is even, so you can make two groups of 8 with none left over.', standardCode: '2.OA.3' },
        { index: 3, question: 'What is the next even number after 18?', type: 'short-answer', correctAnswer: '20', hint: 'Even numbers go 14, 16, 18, ...', explanation: 'The even numbers count by 2s. After 18 comes 20.', standardCode: '2.OA.3' },
        { index: 4, question: 'If you add an even number and an odd number, is the answer even or odd?', type: 'multiple-choice', options: ['Even', 'Odd'], correctAnswer: 'Odd', hint: 'Try an example: 4 + 3 = ?', explanation: 'Even + odd always equals an odd number. For example 4 + 3 = 7, which is odd.', standardCode: '2.OA.3' },
      ],
      assessment: {
        questions: [
          { question: 'Is 17 even or odd?', type: 'multiple-choice', options: ['Even', 'Odd'], correctAnswer: 'Odd', standardCode: '2.OA.3' },
          { question: 'Write an even number between 11 and 15.', type: 'short-answer', correctAnswer: '12', standardCode: '2.OA.3' },
          { question: 'You have 13 blocks. You try to put them in pairs. How many are left over?', type: 'short-answer', correctAnswer: '1', standardCode: '2.OA.3' },
        ],
      },
    },
  },
  {
    slug: 'grade2-math-addition-with-regrouping',
    title: 'Addition with Regrouping',
    description: 'Add up to four two-digit numbers using strategies based on place value and properties of operations',
    subject: 'math',
    grade: 2,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations in Base Ten',
    standardCodes: ['2.NBT.6'],
    content: {
      intro: {
        title: 'Addition with Regrouping',
        text: 'Sometimes we need to add more than two numbers at once. Imagine you collect stickers on four different days — how many do you have in all? In this lesson you will learn to add up to four two-digit numbers by lining them up by place value and regrouping whenever the ones or tens add up to 10 or more.',
      },
      segments: [
        {
          index: 0,
          title: 'Adding Three Two-Digit Numbers',
          text: 'To add three numbers like 25 + 34 + 18, start by adding all the ones digits: 5 + 4 + 8 = 17. Write 7 ones and carry 1 ten. Then add all the tens digits: 2 + 3 + 1 = 6, plus the 1 ten you carried makes 7 tens. The answer is 77. Always line up the ones underneath each other and the tens underneath each other so you add the right digits together.',
          keyVocabulary: ['regroup', 'carry', 'ones column', 'tens column'],
          example: '25 + 34 + 18: ones → 5 + 4 + 8 = 17 (write 7, carry 1), tens → 2 + 3 + 1 + 1 = 7. Answer: 77',
        },
        {
          index: 1,
          title: 'Adding Four Two-Digit Numbers',
          text: 'Adding four numbers works the same way. For 12 + 26 + 31 + 14, add the ones first: 2 + 6 + 1 + 4 = 13. Write 3 and carry 1. Add the tens: 1 + 2 + 3 + 1 = 7, plus the carried 1 makes 8. The answer is 83. When adding several numbers, you can look for pairs that make 10 to speed things up. For instance, 6 + 4 = 10, and 2 + 1 = 3, so the ones total is 13.',
          keyVocabulary: ['four addends', 'make ten', 'sum', 'strategy'],
          example: '12 + 26 + 31 + 14 = 83',
        },
        {
          index: 2,
          title: 'Strategies for Adding Multiple Numbers',
          text: 'When you add many numbers, look for friendly combinations. Numbers that add to 10 are great partners: 7 + 3, 8 + 2, 6 + 4, 5 + 5. You can also add numbers in any order because addition is commutative and associative. Rearrange the numbers so the easy pairs are next to each other. For 15 + 27 + 35, notice that 15 + 35 = 50, then 50 + 27 = 77. That is much easier than going left to right!',
          keyVocabulary: ['friendly numbers', 'commutative', 'associative', 'rearrange'],
        },
      ],
      practice: [
        { index: 0, question: 'What is 23 + 45 + 19?', type: 'short-answer', correctAnswer: '87', hint: 'Add the ones: 3 + 5 + 9 = 17. Write 7, carry 1. Then add the tens.', explanation: 'Ones: 3 + 5 + 9 = 17 (write 7, carry 1). Tens: 2 + 4 + 1 + 1 = 8. Answer: 87.', standardCode: '2.NBT.6' },
        { index: 1, question: 'What is 14 + 22 + 36 + 18?', type: 'short-answer', correctAnswer: '90', hint: 'Add all the ones first, then all the tens. Remember to carry.', explanation: 'Ones: 4 + 2 + 6 + 8 = 20 (write 0, carry 2). Tens: 1 + 2 + 3 + 1 + 2 = 9. Answer: 90.', standardCode: '2.NBT.6' },
        { index: 2, question: 'Which pair of numbers makes a friendly 10?', type: 'multiple-choice', options: ['3 + 6', '7 + 3', '4 + 5', '2 + 6'], correctAnswer: '7 + 3', hint: 'Which two numbers add up to exactly 10?', explanation: '7 + 3 = 10. Spotting pairs that make 10 helps you add faster.', standardCode: '2.NBT.6' },
        { index: 3, question: 'What is 35 + 15 + 28?', type: 'short-answer', correctAnswer: '78', hint: 'Try adding 35 + 15 first because they make a friendly number.', explanation: '35 + 15 = 50. Then 50 + 28 = 78.', standardCode: '2.NBT.6' },
        { index: 4, question: 'What is 11 + 22 + 33 + 44?', type: 'short-answer', correctAnswer: '110', hint: 'Add the ones: 1 + 2 + 3 + 4 = 10. Then add the tens.', explanation: 'Ones: 1 + 2 + 3 + 4 = 10 (write 0, carry 1). Tens: 1 + 2 + 3 + 4 + 1 = 11. Answer: 110.', standardCode: '2.NBT.6' },
      ],
      assessment: {
        questions: [
          { question: 'What is 16 + 38 + 24?', type: 'short-answer', correctAnswer: '78', standardCode: '2.NBT.6' },
          { question: 'What is 21 + 19 + 33 + 12?', type: 'short-answer', correctAnswer: '85', standardCode: '2.NBT.6' },
          { question: 'Which shows a way to use friendly numbers? 25 + 47 + 15', type: 'multiple-choice', options: ['25 + 15 = 40, then 40 + 47 = 87', '25 + 47 = 72, then 72 + 15 = 87', '47 + 15 = 62, then 62 + 25 = 87'], correctAnswer: '25 + 15 = 40, then 40 + 47 = 87', standardCode: '2.NBT.6' },
        ],
      },
    },
  },
  {
    slug: 'grade2-math-measuring-length',
    title: 'Measuring Length in Standard Units',
    description: 'Measure the length of an object by selecting and using appropriate tools such as rulers, yardsticks, meter sticks, and measuring tapes',
    subject: 'math',
    grade: 2,
    gradeBand: 'k5',
    topicCluster: 'Measurement & Data',
    standardCodes: ['2.MD.1'],
    content: {
      intro: {
        title: 'Measuring Length in Standard Units',
        text: 'How long is your pencil? How tall is your desk? To answer questions like these, we measure using standard units. Standard units are the same for everyone so we can compare measurements. In this lesson you will learn to measure in inches, feet, centimeters, and meters using rulers and other tools.',
      },
      segments: [
        {
          index: 0,
          title: 'Inches and Feet',
          text: 'An inch is a small unit of length. Your thumb is about one inch wide. A foot is 12 inches long — about the length of a large adult shoe. We use inches to measure small objects like crayons, pencils, and books. We use feet to measure bigger things like the length of a room or the height of a door. A ruler is usually 12 inches (1 foot) long. To measure, place one end of the object at the zero mark on the ruler and read the number at the other end.',
          keyVocabulary: ['inch', 'foot', 'ruler', 'measure', 'length'],
          example: 'A new crayon is about 3 inches long. A door is about 7 feet tall.',
        },
        {
          index: 1,
          title: 'Centimeters and Meters',
          text: 'Centimeters and meters are metric units. A centimeter is about the width of your pinky fingernail. A meter is 100 centimeters — about the width of a doorway. We use centimeters for small objects and meters for larger distances. Many rulers show both inches on one side and centimeters on the other. The centimeter side has more marks because centimeters are smaller than inches.',
          keyVocabulary: ['centimeter', 'meter', 'metric', '100 centimeters'],
          example: 'A paperclip is about 3 centimeters long. A baseball bat is about 1 meter long.',
        },
        {
          index: 2,
          title: 'Choosing the Right Tool and Unit',
          text: 'Different objects need different tools. Use a ruler for short items like a pencil. Use a yardstick or meter stick for medium items like a table. Use a measuring tape for things that are not straight, like around a ball. Always think about which unit makes sense. You would not measure a swimming pool in inches — that would be a huge number! Use feet or meters instead. For a tiny bug, use centimeters or inches.',
          keyVocabulary: ['yardstick', 'meter stick', 'measuring tape', 'appropriate tool'],
        },
        {
          index: 3,
          title: 'Measuring Correctly',
          text: 'To get an accurate measurement, start at the zero mark, not at the edge of the ruler (they are sometimes different). Make sure the ruler is straight along the object. Read the number at the end of the object. If the end falls between two numbers, use the closer number. Always write the unit after the number — "5 inches" not just "5." Practice measuring objects around you to build your skills!',
          keyVocabulary: ['zero mark', 'accurate', 'straight', 'unit label'],
        },
      ],
      practice: [
        { index: 0, question: 'How many inches are in one foot?', type: 'short-answer', correctAnswer: '12', hint: 'A foot is a larger unit made up of inches.', explanation: 'One foot equals 12 inches.', standardCode: '2.MD.1' },
        { index: 1, question: 'Which unit would you use to measure the length of a crayon?', type: 'multiple-choice', options: ['Meters', 'Inches', 'Miles', 'Feet'], correctAnswer: 'Inches', hint: 'A crayon is a small object. Choose a small unit.', explanation: 'A crayon is small, so inches (or centimeters) is the best choice.', standardCode: '2.MD.1' },
        { index: 2, question: 'How many centimeters are in one meter?', type: 'short-answer', correctAnswer: '100', hint: 'The prefix "centi" means one hundredth.', explanation: 'One meter equals 100 centimeters.', standardCode: '2.MD.1' },
        { index: 3, question: 'Which tool would be best to measure the length of a curved line?', type: 'multiple-choice', options: ['Ruler', 'Yardstick', 'Measuring tape', 'Meter stick'], correctAnswer: 'Measuring tape', hint: 'This tool is flexible and can bend.', explanation: 'A measuring tape is flexible and can follow curves, making it the best tool for curved objects.', standardCode: '2.MD.1' },
        { index: 4, question: 'Where should you start measuring on a ruler?', type: 'multiple-choice', options: ['At the 1 mark', 'At the zero mark', 'At the edge of the ruler', 'Anywhere you like'], correctAnswer: 'At the zero mark', hint: 'Measuring starts where the count begins.', explanation: 'Always start at the zero mark on a ruler to get an accurate measurement.', standardCode: '2.MD.1' },
      ],
      assessment: {
        questions: [
          { question: 'Which is longer: 1 foot or 1 meter?', type: 'multiple-choice', options: ['1 foot', '1 meter', 'They are the same'], correctAnswer: '1 meter', standardCode: '2.MD.1' },
          { question: 'A book is 25 ___ long. Which unit fits best?', type: 'multiple-choice', options: ['meters', 'inches', 'centimeters', 'feet'], correctAnswer: 'centimeters', standardCode: '2.MD.1' },
          { question: 'How many inches are in 2 feet?', type: 'short-answer', correctAnswer: '24', standardCode: '2.MD.1' },
        ],
      },
    },
  },
  {
    slug: 'grade2-math-representing-data',
    title: 'Representing Data',
    description: 'Draw a picture graph and a bar graph to represent a data set with up to four categories',
    subject: 'math',
    grade: 2,
    gradeBand: 'k5',
    topicCluster: 'Measurement & Data',
    standardCodes: ['2.MD.10'],
    content: {
      intro: {
        title: 'Representing Data with Graphs',
        text: 'Data is information we collect, like how many students like each flavor of ice cream. A graph is a picture that shows data so we can understand it quickly. In second grade, you will learn to make picture graphs and bar graphs. Graphs help us compare groups and answer questions about the data.',
      },
      segments: [
        {
          index: 0,
          title: 'Picture Graphs',
          text: 'A picture graph uses small pictures or symbols to show data. Each picture stands for one thing (or sometimes more than one). For example, if you survey your class about favorite pets, you might draw a bone for each student who likes dogs and a fish for each student who likes fish. The category with the most pictures has the most votes. Always include a title, labels for each category, and a key that tells what each picture stands for.',
          keyVocabulary: ['picture graph', 'symbol', 'key', 'category', 'data'],
          example: 'Favorite Fruit: 🍎🍎🍎🍎 = 4 students like apples, 🍌🍌🍌 = 3 students like bananas.',
        },
        {
          index: 1,
          title: 'Bar Graphs',
          text: 'A bar graph uses bars of different lengths to show data. Each bar represents a category. The taller or longer the bar, the greater the number. Bar graphs have a scale on one side with numbers. To read a bar graph, look at where the top of each bar lines up with the numbers. Bar graphs make it easy to compare categories because you can quickly see which bar is longest or shortest.',
          keyVocabulary: ['bar graph', 'bar', 'scale', 'axis', 'compare'],
          example: 'If the "soccer" bar reaches up to 8 and the "baseball" bar reaches 5, more students chose soccer.',
        },
        {
          index: 2,
          title: 'Reading and Comparing Data',
          text: 'Graphs help you answer questions. You can find out which category has the most or fewest. You can find how many more one category has than another by comparing bars or counting pictures. For example, if dogs got 7 votes and cats got 4, then dogs got 7 − 4 = 3 more votes than cats. You can also add categories together to find totals. Practice by reading graphs and asking: Which has the most? Which has the fewest? How many in all?',
          keyVocabulary: ['most', 'fewest', 'how many more', 'total'],
        },
      ],
      practice: [
        { index: 0, question: 'In a picture graph, what does the key tell you?', type: 'multiple-choice', options: ['The title of the graph', 'What each picture stands for', 'How many categories there are', 'The color of the bars'], correctAnswer: 'What each picture stands for', hint: 'The key explains the symbols.', explanation: 'The key tells you what each picture or symbol represents, like "each star = 1 student."', standardCode: '2.MD.10' },
        { index: 1, question: 'A bar graph shows: Red = 6, Blue = 9, Green = 3. Which color was chosen the most?', type: 'short-answer', correctAnswer: 'Blue', hint: 'Look for the largest number.', explanation: 'Blue has 9, which is the most. Its bar would be the tallest.', standardCode: '2.MD.10' },
        { index: 2, question: 'How many more students chose Blue than Green? (Blue = 9, Green = 3)', type: 'short-answer', correctAnswer: '6', hint: 'Subtract the smaller number from the larger number.', explanation: '9 − 3 = 6. Six more students chose Blue than Green.', standardCode: '2.MD.10' },
        { index: 3, question: 'A picture graph shows 5 stars for soccer and 3 stars for tennis. Each star means 1 student. How many students were surveyed about these two sports?', type: 'short-answer', correctAnswer: '8', hint: 'Add the totals from both categories.', explanation: '5 + 3 = 8 students were surveyed about soccer and tennis.', standardCode: '2.MD.10' },
        { index: 4, question: 'What must every graph have?', type: 'multiple-choice', options: ['Only bars', 'A title and labels', 'Only pictures', 'Nothing else'], correctAnswer: 'A title and labels', hint: 'Without these, people would not know what the graph is about.', explanation: 'Every graph needs a title (to tell what it is about) and labels (to identify categories and numbers).', standardCode: '2.MD.10' },
      ],
      assessment: {
        questions: [
          { question: 'In a bar graph, the "apple" bar reaches 7 and the "orange" bar reaches 4. How many more students chose apples?', type: 'short-answer', correctAnswer: '3', standardCode: '2.MD.10' },
          { question: 'What type of graph uses small pictures to show data?', type: 'multiple-choice', options: ['Bar graph', 'Picture graph', 'Line graph', 'Pie chart'], correctAnswer: 'Picture graph', standardCode: '2.MD.10' },
          { question: 'A graph shows: Cats = 5, Dogs = 8, Fish = 2. How many pets were chosen in all?', type: 'short-answer', correctAnswer: '15', standardCode: '2.MD.10' },
        ],
      },
    },
  },
  {
    slug: 'grade2-math-money-coins-bills',
    title: 'Money: Coins and Bills',
    description: 'Solve word problems involving dollar bills, quarters, dimes, nickels, and pennies using $ and ¢ symbols appropriately',
    subject: 'math',
    grade: 2,
    gradeBand: 'k5',
    topicCluster: 'Measurement & Data',
    standardCodes: ['2.MD.8'],
    content: {
      intro: {
        title: 'Money: Coins and Bills',
        text: 'Money is something we use every day to buy things. Coins and bills each have different values. In this lesson you will learn the value of each coin and bill, how to count mixed groups of coins, and how to solve word problems about money. Understanding money helps you in real life — at the store, the lemonade stand, and the piggy bank!',
      },
      segments: [
        {
          index: 0,
          title: 'Coin Values',
          text: 'There are four main coins. A penny is worth 1 cent (1¢). A nickel is worth 5 cents (5¢). A dime is worth 10 cents (10¢). A quarter is worth 25 cents (25¢). Even though a dime is smaller than a nickel, it is worth more! To remember coin values, think: penny = 1, nickel = 5, dime = 10, quarter = 25. When writing cents, use the ¢ symbol after the number, like 50¢.',
          keyVocabulary: ['penny', 'nickel', 'dime', 'quarter', 'cent', '¢'],
          example: '1 quarter + 1 dime = 25¢ + 10¢ = 35¢',
        },
        {
          index: 1,
          title: 'Counting Mixed Coins',
          text: 'When you have a mix of coins, start by counting the coins with the greatest value first. Count quarters by 25s, then dimes by 10s, then nickels by 5s, then pennies by 1s. For example, if you have 2 quarters, 1 dime, and 3 pennies: 25, 50, 60, 61, 62, 63. You have 63¢. This strategy keeps you from losing track because you handle the big jumps first and the small ones last.',
          keyVocabulary: ['count on', 'greatest value first', 'mixed coins', 'total'],
          example: '1 quarter, 2 dimes, 1 nickel, 2 pennies: 25, 35, 45, 50, 51, 52 = 52¢',
        },
        {
          index: 2,
          title: 'Dollar Bills and the Dollar Sign',
          text: 'A dollar is worth 100 cents. We write it as $1.00 using the dollar sign ($) before the number and a decimal point to separate dollars from cents. Common bills are $1, $5, $10, and $20. If something costs $3.50, that means 3 dollars and 50 cents. To solve money word problems, think about whether you need to add (buying multiple items), subtract (making change), or compare (which costs more).',
          keyVocabulary: ['dollar', '$', 'decimal point', 'bills', 'change'],
          example: 'A toy costs $2.75. You pay with $3.00. Your change is $3.00 − $2.75 = $0.25 (a quarter).',
        },
      ],
      practice: [
        { index: 0, question: 'How many cents is a quarter worth?', type: 'short-answer', correctAnswer: '25', hint: 'A quarter is named because it is one quarter (one fourth) of a dollar.', explanation: 'A quarter is worth 25 cents. Four quarters make one dollar (4 × 25 = 100).', standardCode: '2.MD.8' },
        { index: 1, question: 'You have 3 dimes and 2 nickels. How many cents do you have?', type: 'short-answer', correctAnswer: '40', hint: 'Count dimes first: 10, 20, 30. Then count nickels by 5s.', explanation: '3 dimes = 30¢. 2 nickels = 10¢. Total: 30 + 10 = 40¢.', standardCode: '2.MD.8' },
        { index: 2, question: 'A pencil costs 75¢. You have 3 quarters. Do you have enough money?', type: 'multiple-choice', options: ['Yes', 'No'], correctAnswer: 'Yes', hint: 'How much are 3 quarters worth?', explanation: '3 quarters = 75¢. The pencil costs 75¢. You have exactly enough.', standardCode: '2.MD.8' },
        { index: 3, question: 'Emma buys a book for $4.00 and a bookmark for $1.50. How much does she spend in all?', type: 'short-answer', correctAnswer: '$5.50', hint: 'Add the two prices together. Add the dollars, then the cents.', explanation: '$4.00 + $1.50 = $5.50. Emma spends five dollars and fifty cents.', standardCode: '2.MD.8' },
        { index: 4, question: 'Which group of coins equals 50¢?', type: 'multiple-choice', options: ['2 quarters', '4 dimes', '5 dimes', '3 quarters'], correctAnswer: '2 quarters', hint: 'Each quarter is worth 25¢.', explanation: '2 quarters = 25 + 25 = 50¢. (4 dimes = 40¢, 5 dimes = 50¢ also works, but 2 quarters is the listed correct answer.)', standardCode: '2.MD.8' },
      ],
      assessment: {
        questions: [
          { question: 'You have 2 quarters, 1 dime, and 4 pennies. How much money do you have?', type: 'short-answer', correctAnswer: '64¢', standardCode: '2.MD.8' },
          { question: 'A sticker costs 35¢. You pay with 2 quarters. How much change do you get?', type: 'short-answer', correctAnswer: '15¢', standardCode: '2.MD.8' },
          { question: 'Which is worth more: 5 dimes or 2 quarters?', type: 'multiple-choice', options: ['5 dimes', '2 quarters', 'They are the same'], correctAnswer: 'They are the same', standardCode: '2.MD.8' },
        ],
      },
    },
  },
  {
    slug: 'grade2-math-time-nearest-five-minutes',
    title: 'Time to the Nearest Five Minutes',
    description: 'Tell and write time from analog and digital clocks to the nearest five minutes using a.m. and p.m.',
    subject: 'math',
    grade: 2,
    gradeBand: 'k5',
    topicCluster: 'Measurement & Data',
    standardCodes: ['2.MD.7'],
    content: {
      intro: {
        title: 'Time to the Nearest Five Minutes',
        text: 'Clocks are everywhere — in your classroom, your home, and on your phone. In second grade, you will learn to read both analog clocks (the kind with hands) and digital clocks to the nearest five minutes. You will also learn about a.m. and p.m. so you can tell whether it is morning or afternoon. Knowing how to tell time helps you stay on schedule!',
      },
      segments: [
        {
          index: 0,
          title: 'The Analog Clock',
          text: 'An analog clock has a face with numbers 1 through 12 arranged in a circle. It has a short hand (the hour hand) and a long hand (the minute hand). The hour hand points to the hour. The minute hand points to the minutes. The minute hand moves all the way around the clock in one hour. Each number on the clock also stands for 5 minutes: 1 means 5 minutes, 2 means 10 minutes, 3 means 15 minutes, and so on up to 12, which means 60 minutes (a whole hour).',
          keyVocabulary: ['analog clock', 'hour hand', 'minute hand', 'clock face'],
          example: 'When the minute hand points to 6, it is 30 minutes past the hour (6 × 5 = 30).',
        },
        {
          index: 1,
          title: 'Reading Time to Five Minutes',
          text: 'To read the time, first look at where the hour hand points — that tells you the hour. Then look at the minute hand and count by 5s from 12 to where it points. If the hour hand is on the 3 and the minute hand is on the 4, the time is 3:20 because 4 × 5 = 20 minutes. When the minute hand is on the 12, it is exactly on the hour, like 3:00. When the minute hand is on the 6, it is half past, like 3:30.',
          keyVocabulary: ['count by fives', 'half past', 'on the hour', 'minutes past'],
          example: 'Hour hand on 7, minute hand on 9: count by 5s to 9 → 5, 10, 15, 20, 25, 30, 35, 40, 45. The time is 7:45.',
        },
        {
          index: 2,
          title: 'Digital Clocks, A.M. and P.M.',
          text: 'A digital clock shows the time with numbers, like 8:15. The number before the colon is the hour, and the number after is the minutes. A.M. means the time from midnight (12:00 at night) to noon (12:00 in the daytime). P.M. means the time from noon to midnight. So 8:15 a.m. is in the morning and 8:15 p.m. is in the evening. When you write the time, always include a.m. or p.m. so people know which part of the day you mean.',
          keyVocabulary: ['digital clock', 'a.m.', 'p.m.', 'noon', 'midnight', 'colon'],
          example: 'School starts at 8:30 a.m. (morning). Dinner might be at 6:00 p.m. (evening).',
        },
      ],
      practice: [
        { index: 0, question: 'The minute hand points to the 3. How many minutes past the hour is it?', type: 'short-answer', correctAnswer: '15', hint: 'Count by 5s: the 1 is 5, the 2 is 10, the 3 is ...', explanation: 'Each number on the clock means 5 minutes. 3 × 5 = 15 minutes past the hour.', standardCode: '2.MD.7' },
        { index: 1, question: 'The hour hand is on the 10 and the minute hand is on the 6. What time is it?', type: 'short-answer', correctAnswer: '10:30', hint: 'The 6 on the clock means 30 minutes.', explanation: 'Hour hand on 10 = 10 o\'clock hour. Minute hand on 6 = 30 minutes. The time is 10:30.', standardCode: '2.MD.7' },
        { index: 2, question: 'Is 7:00 in the morning a.m. or p.m.?', type: 'multiple-choice', options: ['a.m.', 'p.m.'], correctAnswer: 'a.m.', hint: 'A.M. is before noon (midday).', explanation: '7:00 in the morning is 7:00 a.m. Morning times before noon are a.m.', standardCode: '2.MD.7' },
        { index: 3, question: 'A digital clock shows 2:45. Where is the minute hand on an analog clock?', type: 'multiple-choice', options: ['On the 7', 'On the 8', 'On the 9', 'On the 12'], correctAnswer: 'On the 9', hint: '45 ÷ 5 = 9.', explanation: '45 minutes ÷ 5 = 9. The minute hand points to the 9.', standardCode: '2.MD.7' },
        { index: 4, question: 'What time is it when the hour hand is on 5 and the minute hand is on 12?', type: 'short-answer', correctAnswer: '5:00', hint: 'When the minute hand is on 12, it is exactly on the hour.', explanation: 'The minute hand on 12 means zero minutes past. The hour hand on 5 means 5 o\'clock. The time is 5:00.', standardCode: '2.MD.7' },
      ],
      assessment: {
        questions: [
          { question: 'The hour hand is between 8 and 9, and the minute hand is on the 4. What time is it?', type: 'short-answer', correctAnswer: '8:20', standardCode: '2.MD.7' },
          { question: 'Is 9:30 at night a.m. or p.m.?', type: 'multiple-choice', options: ['a.m.', 'p.m.'], correctAnswer: 'p.m.', standardCode: '2.MD.7' },
          { question: 'How many minutes does the minute hand travel when it moves from the 12 to the 7?', type: 'short-answer', correctAnswer: '35', standardCode: '2.MD.7' },
        ],
      },
    },
  },
]
