import type { ModuleSeed } from '../types'

export const GRADE_4_MATH: ModuleSeed[] = [
  {
    slug: 'grade4-math-fraction-equivalence',
    title: 'Equivalent Fractions',
    description: 'Generate and recognize equivalent fractions using visual models and multiplication',
    subject: 'math',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations—Fractions',
    standardCodes: ['4.NF.1'],
    content: {
      intro: {
        title: 'Equivalent Fractions',
        text: 'Have you ever noticed that one half of a pizza looks the same as two quarters of a pizza? That is because 1/2 and 2/4 are equivalent fractions — they name the same amount! Today we will learn how to find fractions that are equal to each other, even though they use different numbers.',
      },
      segments: [
        {
          index: 0,
          title: 'What Are Equivalent Fractions?',
          text: 'Equivalent fractions are fractions that represent the same part of a whole, even though the numerator and denominator are different. Think of a candy bar split into 2 equal pieces. If you eat 1 piece, you ate 1/2. Now imagine that same candy bar split into 4 equal pieces instead. If you eat 2 pieces, you ate 2/4. You ate the same amount of candy bar either way! That means 1/2 = 2/4. The key idea is that equivalent fractions cover the same amount of area or represent the same point on a number line, even though the numbers look different.',
          keyVocabulary: ['equivalent', 'numerator', 'denominator', 'fraction', 'whole'],
          example: 'Picture a rectangle split into 3 equal parts with 1 shaded. Now split each part in half so there are 6 parts with 2 shaded. 1/3 = 2/6.',
        },
        {
          index: 1,
          title: 'Multiplying to Find Equivalent Fractions',
          text: 'Here is a powerful rule: you can create an equivalent fraction by multiplying both the numerator and the denominator by the same number. For example, start with 1/3. Multiply the top and bottom by 2: (1 x 2)/(3 x 2) = 2/6. Multiply the top and bottom by 3 instead: (1 x 3)/(3 x 3) = 3/9. All three fractions — 1/3, 2/6, and 3/9 — are equivalent. This works because multiplying top and bottom by the same number is like multiplying by 1, which does not change the value. You can use 2, 3, 4, or any whole number to create as many equivalent fractions as you want.',
          keyVocabulary: ['multiply', 'equivalent fraction', 'same number', 'value'],
        },
        {
          index: 2,
          title: 'Simplifying Fractions',
          text: 'Sometimes you start with a fraction that uses large numbers and want to write it in a simpler form. To simplify, divide the numerator and denominator by the same number. For example, 4/8: divide the top and bottom by 4 to get (4 / 4)/(8 / 4) = 1/2. The fraction 6/10 can be simplified by dividing both by 2 to get 3/5. Simplifying does not change the amount the fraction represents — it just uses smaller, easier numbers. A fraction is in simplest form when the only number that divides both the numerator and denominator evenly is 1.',
          keyVocabulary: ['simplify', 'divide', 'simplest form', 'evenly'],
        },
        {
          index: 3,
          title: 'Using Models and Number Lines',
          text: 'Visual models help you check that fractions are equivalent. Draw two rectangles of the same size. Divide one into 4 equal parts and shade 3 to show 3/4. Divide the other into 8 equal parts and shade 6 to show 6/8. The shaded areas are the same size, proving 3/4 = 6/8. You can also use a number line. Mark 0 and 1, then place the fractions. If 2/5 and 4/10 land on the same point, they are equivalent. Practicing with models builds your confidence before working with just numbers.',
          keyVocabulary: ['model', 'number line', 'shaded', 'area'],
        },
      ],
      practice: [
        { index: 0, question: 'Find an equivalent fraction for 1/4 by multiplying numerator and denominator by 3.', type: 'short-answer', correctAnswer: '3/12', hint: 'Multiply 1 by 3 for the numerator and 4 by 3 for the denominator.', explanation: '(1 x 3)/(4 x 3) = 3/12. Since we multiplied top and bottom by the same number, 1/4 = 3/12.', standardCode: '4.NF.1' },
        { index: 1, question: 'Which fraction is equivalent to 2/3?', type: 'multiple-choice', options: ['3/4', '4/6', '2/6', '3/2'], correctAnswer: '4/6', hint: 'Multiply both the numerator and denominator of 2/3 by 2.', explanation: '(2 x 2)/(3 x 2) = 4/6, so 2/3 = 4/6.', standardCode: '4.NF.1' },
        { index: 2, question: 'Simplify 6/8 to its simplest form.', type: 'short-answer', correctAnswer: '3/4', hint: 'What number can divide both 6 and 8 evenly?', explanation: 'Divide numerator and denominator by 2: (6 / 2)/(8 / 2) = 3/4.', standardCode: '4.NF.1' },
        { index: 3, question: 'True or false: 3/5 = 9/15.', type: 'multiple-choice', options: ['True', 'False'], correctAnswer: 'True', hint: 'Multiply 3/5 by 3/3 and see what you get.', explanation: '(3 x 3)/(5 x 3) = 9/15, so 3/5 and 9/15 are equivalent.', standardCode: '4.NF.1' },
        { index: 4, question: 'Fill in the blank: 2/5 = ___/10.', type: 'fill-blank', correctAnswer: '4', hint: 'What did you multiply the denominator 5 by to get 10?', explanation: '5 x 2 = 10, so multiply the numerator by 2 as well: 2 x 2 = 4. The answer is 4/10.', standardCode: '4.NF.1' },
      ],
      assessment: {
        questions: [
          { question: 'Write an equivalent fraction for 3/4 with a denominator of 12.', type: 'short-answer', correctAnswer: '9/12', standardCode: '4.NF.1' },
          { question: 'Simplify 8/12 to simplest form.', type: 'short-answer', correctAnswer: '2/3', standardCode: '4.NF.1' },
          { question: 'Which fraction is equivalent to 5/10?', type: 'multiple-choice', options: ['1/2', '2/5', '5/5', '1/5'], correctAnswer: '1/2', standardCode: '4.NF.1' },
        ],
      },
    },
  },
  {
    slug: 'grade4-math-comparing-fractions',
    title: 'Comparing and Ordering Fractions',
    description: 'Compare two fractions with different numerators and denominators using benchmarks and common denominators',
    subject: 'math',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations—Fractions',
    standardCodes: ['4.NF.2'],
    content: {
      intro: {
        title: 'Comparing and Ordering Fractions',
        text: 'Which is bigger: 3/8 or 2/5? When fractions have different denominators, it can be tricky to tell which one is larger. In this module you will learn strategies to compare fractions, including using benchmark fractions and finding common denominators.',
      },
      segments: [
        {
          index: 0,
          title: 'Using Benchmark Fractions',
          text: 'A benchmark fraction is a simple fraction you know well, like 0, 1/2, or 1. You can compare other fractions to these benchmarks. For example, is 3/8 more or less than 1/2? Since 4/8 equals 1/2, and 3/8 is less than 4/8, then 3/8 is less than 1/2. Now check 5/6: since 3/6 = 1/2, and 5/6 is greater than 3/6, then 5/6 is greater than 1/2. So 3/8 is less than 5/6 because 3/8 is below 1/2 and 5/6 is above it. Benchmarks give you a quick way to estimate and compare.',
          keyVocabulary: ['benchmark', 'compare', 'estimate', 'greater than', 'less than'],
        },
        {
          index: 1,
          title: 'Common Denominators',
          text: 'To compare fractions exactly, give them the same denominator. When fractions share a denominator, you just compare the numerators. To find a common denominator, look for a number that both denominators divide into evenly. For 2/3 and 3/4, the denominators are 3 and 4. Both go into 12 evenly. Rewrite 2/3 as 8/12 and 3/4 as 9/12. Now compare: 8/12 is less than 9/12, so 2/3 is less than 3/4. The least common denominator keeps the numbers small and easy to work with.',
          keyVocabulary: ['common denominator', 'least common denominator', 'rewrite'],
          example: 'Compare 1/3 and 2/5. Common denominator is 15. 1/3 = 5/15 and 2/5 = 6/15. Since 5 < 6, we know 1/3 < 2/5.',
        },
        {
          index: 2,
          title: 'Same Numerators',
          text: 'Here is a shortcut: when two fractions have the same numerator, the one with the smaller denominator is larger. Think about it — if you share 1 pizza among 4 people (1/4) versus 1 pizza among 8 people (1/8), each person gets more when there are fewer people sharing. So 1/4 > 1/8. The same applies to any equal numerator: 3/5 > 3/7 because fifths are bigger pieces than sevenths, and you have the same number of pieces.',
          keyVocabulary: ['numerator', 'denominator', 'larger piece', 'smaller piece'],
        },
        {
          index: 3,
          title: 'Ordering Fractions',
          text: 'To order three or more fractions from least to greatest, use the strategies you learned. First, find a common denominator for all the fractions. Then rewrite each fraction with that denominator and compare the numerators. For example, order 1/2, 2/5, and 3/4. A common denominator is 20. Rewrite them: 1/2 = 10/20, 2/5 = 8/20, 3/4 = 15/20. Now order by numerator: 8/20, 10/20, 15/20. So from least to greatest: 2/5, 1/2, 3/4.',
          keyVocabulary: ['order', 'least to greatest', 'greatest to least'],
        },
      ],
      practice: [
        { index: 0, question: 'Compare using <, >, or =: 3/4 ___ 2/4.', type: 'short-answer', correctAnswer: '>', hint: 'The denominators are the same, so compare the numerators.', explanation: 'Since 3 > 2 and the denominators are the same, 3/4 > 2/4.', standardCode: '4.NF.2' },
        { index: 1, question: 'Which is greater: 2/3 or 3/5?', type: 'multiple-choice', options: ['2/3', '3/5', 'They are equal'], correctAnswer: '2/3', hint: 'Find a common denominator of 15 and compare.', explanation: '2/3 = 10/15 and 3/5 = 9/15. Since 10 > 9, 2/3 is greater.', standardCode: '4.NF.2' },
        { index: 2, question: 'Is 5/8 greater than or less than 1/2?', type: 'multiple-choice', options: ['Greater than 1/2', 'Less than 1/2', 'Equal to 1/2'], correctAnswer: 'Greater than 1/2', hint: 'What fraction with denominator 8 equals 1/2?', explanation: '1/2 = 4/8. Since 5/8 > 4/8, we know 5/8 > 1/2.', standardCode: '4.NF.2' },
        { index: 3, question: 'Compare: 2/6 ___ 2/8.', type: 'short-answer', correctAnswer: '>', hint: 'The numerators are the same. Which denominator gives bigger pieces?', explanation: 'Same numerator, so the smaller denominator means larger pieces. 2/6 > 2/8.', standardCode: '4.NF.2' },
        { index: 4, question: 'Order from least to greatest: 1/2, 1/4, 3/4.', type: 'short-answer', correctAnswer: '1/4, 1/2, 3/4', hint: 'All denominators are 2 or 4. Use 4 as the common denominator.', explanation: '1/4 = 1/4, 1/2 = 2/4, 3/4 = 3/4. In order: 1/4, 2/4, 3/4.', standardCode: '4.NF.2' },
      ],
      assessment: {
        questions: [
          { question: 'Compare using < or >: 4/5 ___ 3/4.', type: 'short-answer', correctAnswer: '>', standardCode: '4.NF.2' },
          { question: 'Which fraction is the smallest: 2/3, 3/8, or 1/2?', type: 'multiple-choice', options: ['2/3', '3/8', '1/2'], correctAnswer: '3/8', standardCode: '4.NF.2' },
          { question: 'Order from greatest to least: 5/6, 2/3, 7/12.', type: 'short-answer', correctAnswer: '5/6, 2/3, 7/12', standardCode: '4.NF.2' },
        ],
      },
    },
  },
  {
    slug: 'grade4-math-fraction-add-subtract',
    title: 'Fraction Operations: Add and Subtract',
    description: 'Add and subtract fractions and mixed numbers with like denominators',
    subject: 'math',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations—Fractions',
    standardCodes: ['4.NF.3'],
    content: {
      intro: {
        title: 'Adding and Subtracting Fractions',
        text: 'You already know how to add and subtract whole numbers. Now it is time to add and subtract fractions! When fractions have the same denominator, adding and subtracting them is straightforward — you just work with the numerators. Let us learn how.',
      },
      segments: [
        {
          index: 0,
          title: 'Adding Fractions with Like Denominators',
          text: 'When two fractions have the same denominator, add the numerators and keep the denominator the same. For example, 1/5 + 2/5: the denominators are both 5, so add the numerators 1 + 2 = 3. The answer is 3/5. Think of it like adding slices of pie. If a pie is cut into 5 equal slices and you take 1 slice, then take 2 more slices, you now have 3 slices out of 5 — that is 3/5 of the pie. The denominator tells you the size of the pieces, and the numerator tells you how many pieces you have.',
          keyVocabulary: ['like denominators', 'add numerators', 'sum'],
          example: '2/8 + 3/8 = (2 + 3)/8 = 5/8',
        },
        {
          index: 1,
          title: 'Subtracting Fractions with Like Denominators',
          text: 'Subtracting fractions with the same denominator works the same way — subtract the numerators and keep the denominator. For 5/6 - 2/6: subtract the numerators 5 - 2 = 3, and the denominator stays 6. The answer is 3/6, which simplifies to 1/2. Always check whether your answer can be simplified. If the numerator and denominator share a common factor, divide both by that factor to write the fraction in simplest form.',
          keyVocabulary: ['subtract numerators', 'difference', 'simplify'],
        },
        {
          index: 2,
          title: 'Adding and Subtracting Mixed Numbers',
          text: 'A mixed number has a whole number part and a fraction part, like 2 3/4. To add mixed numbers with like denominators, first add the whole numbers, then add the fractions. For example, 1 2/5 + 2 1/5: add the wholes 1 + 2 = 3, add the fractions 2/5 + 1/5 = 3/5. The answer is 3 3/5. For subtraction, subtract the wholes and subtract the fractions. If the fraction you are subtracting is larger, you may need to regroup by borrowing 1 from the whole number and converting it into a fraction.',
          keyVocabulary: ['mixed number', 'whole number', 'regroup', 'borrow'],
          example: '3 1/4 + 1 2/4 = 4 3/4. Add wholes: 3 + 1 = 4. Add fractions: 1/4 + 2/4 = 3/4.',
        },
        {
          index: 3,
          title: 'Fractions Greater Than 1',
          text: 'Sometimes when you add fractions, the numerator becomes larger than the denominator. For example, 3/4 + 3/4 = 6/4. Since 6/4 is greater than 1, convert it to a mixed number. Divide 6 by 4: that is 1 whole with 2 left over, so 6/4 = 1 2/4 = 1 1/2. Always check your final answer to see if it can be written as a mixed number or simplified. An improper fraction is one where the numerator is greater than or equal to the denominator.',
          keyVocabulary: ['improper fraction', 'mixed number', 'convert', 'greater than 1'],
        },
      ],
      practice: [
        { index: 0, question: '2/7 + 3/7 = ?', type: 'short-answer', correctAnswer: '5/7', hint: 'Add the numerators and keep the denominator.', explanation: '2/7 + 3/7 = (2 + 3)/7 = 5/7. The denominators are the same, so just add 2 + 3.', standardCode: '4.NF.3' },
        { index: 1, question: '7/10 - 4/10 = ?', type: 'short-answer', correctAnswer: '3/10', hint: 'Subtract the numerators and keep the denominator.', explanation: '7/10 - 4/10 = (7 - 4)/10 = 3/10.', standardCode: '4.NF.3' },
        { index: 2, question: '3/8 + 5/8 = ? Write your answer as a mixed number.', type: 'short-answer', correctAnswer: '1', hint: '3 + 5 = 8, and 8/8 is a whole.', explanation: '3/8 + 5/8 = 8/8 = 1 whole.', standardCode: '4.NF.3' },
        { index: 3, question: '2 3/6 + 1 2/6 = ?', type: 'short-answer', correctAnswer: '3 5/6', hint: 'Add the whole numbers, then add the fractions.', explanation: 'Wholes: 2 + 1 = 3. Fractions: 3/6 + 2/6 = 5/6. Answer: 3 5/6.', standardCode: '4.NF.3' },
        { index: 4, question: 'Which is the correct answer for 5/6 - 1/6?', type: 'multiple-choice', options: ['4/6', '6/6', '4/12', '5/6'], correctAnswer: '4/6', hint: 'Subtract the numerators: 5 - 1.', explanation: '5/6 - 1/6 = 4/6. You can simplify this to 2/3.', standardCode: '4.NF.3' },
      ],
      assessment: {
        questions: [
          { question: '4/9 + 3/9 = ?', type: 'short-answer', correctAnswer: '7/9', standardCode: '4.NF.3' },
          { question: '5 2/5 - 2 1/5 = ?', type: 'short-answer', correctAnswer: '3 1/5', standardCode: '4.NF.3' },
          { question: 'What is 5/6 + 4/6? Write as a mixed number in simplest form.', type: 'short-answer', correctAnswer: '1 1/2', standardCode: '4.NF.3' },
        ],
      },
    },
  },
  {
    slug: 'grade4-math-multi-digit-multiplication',
    title: 'Multi-Digit Multiplication',
    description: 'Multiply a whole number of up to four digits by a one-digit number using place value strategies',
    subject: 'math',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations in Base Ten',
    standardCodes: ['4.NBT.5', '4.OA.1'],
    content: {
      intro: {
        title: 'Multi-Digit Multiplication',
        text: 'You already know your basic multiplication facts. Now we will use those facts to multiply much larger numbers! Imagine you need to figure out how many seats are in a theater with 8 rows of 256 seats each. Multiplication can help you solve real problems like this.',
      },
      segments: [
        {
          index: 0,
          title: 'Multiplying Tens, Hundreds, and Thousands',
          text: 'Start by multiplying single digits by multiples of 10, 100, and 1,000. If you know 3 x 4 = 12, then 3 x 40 = 120, 3 x 400 = 1,200, and 3 x 4,000 = 12,000. See the pattern? You multiply the non-zero digits and then attach the zeros from the multiple. This works because of place value: 40 means 4 tens, so 3 groups of 4 tens is 12 tens, which equals 120. Understanding this pattern makes larger multiplication much easier.',
          keyVocabulary: ['place value', 'multiply', 'tens', 'hundreds', 'thousands'],
          example: '5 x 600 = 5 x 6 hundreds = 30 hundreds = 3,000',
        },
        {
          index: 1,
          title: 'The Area Model',
          text: 'The area model breaks a large multiplication into smaller, easier problems using place value. To multiply 4 x 36, break 36 into 30 + 6. Now multiply each part: 4 x 30 = 120 and 4 x 6 = 24. Add the results: 120 + 24 = 144. You can draw this as a rectangle split into two sections. For bigger numbers like 3 x 248, break it into 3 x 200, 3 x 40, and 3 x 8 to get 600 + 120 + 24 = 744. The area model helps you see exactly what is happening at each place value.',
          keyVocabulary: ['area model', 'expanded form', 'partial products'],
        },
        {
          index: 2,
          title: 'The Standard Algorithm',
          text: 'The standard algorithm is the traditional method for multiplication. Write the larger number on top and the single digit below. Multiply the ones digit first, then the tens, then the hundreds. When a product is 10 or more, you regroup (carry) to the next place. For example, 7 x 384: start with 7 x 4 = 28, write 8 and carry the 2. Then 7 x 8 = 56, add the carried 2 to get 58, write 8 and carry 5. Then 7 x 3 = 21, add the 5 to get 26. The answer is 2,688.',
          keyVocabulary: ['standard algorithm', 'regroup', 'carry', 'product'],
        },
        {
          index: 3,
          title: 'Solving Word Problems',
          text: 'Multiplication word problems use phrases like "each," "per," "every," and "times as many." A multiplicative comparison says one amount is a certain number of times as much as another. For example: "The school ordered 6 boxes with 125 pencils in each box. How many pencils in all?" You multiply 6 x 125. Using the area model: 6 x 100 = 600, 6 x 20 = 120, 6 x 5 = 30. Total: 600 + 120 + 30 = 750 pencils. Always check that your answer makes sense by estimating first.',
          keyVocabulary: ['word problem', 'multiplicative comparison', 'estimate', 'reasonable'],
        },
      ],
      practice: [
        { index: 0, question: '7 x 300 = ?', type: 'short-answer', correctAnswer: '2100', hint: 'Multiply 7 x 3, then attach the two zeros.', explanation: '7 x 3 = 21, and 300 has two zeros, so the answer is 2,100.', standardCode: '4.NBT.5' },
        { index: 1, question: 'Use the area model: 5 x 43 = ?', type: 'short-answer', correctAnswer: '215', hint: 'Break 43 into 40 + 3. Multiply each part by 5 and add.', explanation: '5 x 40 = 200 and 5 x 3 = 15. Add: 200 + 15 = 215.', standardCode: '4.NBT.5' },
        { index: 2, question: '4 x 1,236 = ?', type: 'short-answer', correctAnswer: '4944', hint: 'Break it up: 4 x 1,000 + 4 x 200 + 4 x 36.', explanation: '4 x 1,000 = 4,000; 4 x 200 = 800; 4 x 30 = 120; 4 x 6 = 24. Total: 4,944.', standardCode: '4.NBT.5' },
        { index: 3, question: 'A farmer plants 8 rows with 215 seeds in each row. How many seeds in all?', type: 'short-answer', correctAnswer: '1720', hint: 'Multiply 8 x 215 using place value.', explanation: '8 x 200 = 1,600; 8 x 15 = 120. Total: 1,600 + 120 = 1,720 seeds.', standardCode: '4.OA.1' },
        { index: 4, question: 'Which expression shows 3 times as many as 45?', type: 'multiple-choice', options: ['3 + 45', '3 x 45', '45 - 3', '45 / 3'], correctAnswer: '3 x 45', hint: '"Times as many" means multiplication.', explanation: '"3 times as many as 45" is written as 3 x 45 = 135.', standardCode: '4.OA.1' },
      ],
      assessment: {
        questions: [
          { question: '6 x 482 = ?', type: 'short-answer', correctAnswer: '2892', standardCode: '4.NBT.5' },
          { question: 'A store has 9 shelves with 324 books on each shelf. How many books are there in all?', type: 'short-answer', correctAnswer: '2916', standardCode: '4.OA.1' },
          { question: 'Which is the product of 5 x 2,010?', type: 'multiple-choice', options: ['10,050', '10,500', '1,050', '10,005'], correctAnswer: '10,050', standardCode: '4.NBT.5' },
        ],
      },
    },
  },
  {
    slug: 'grade4-math-factors-multiples',
    title: 'Factors and Multiples',
    description: 'Find factor pairs for whole numbers and determine whether a number is prime or composite',
    subject: 'math',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Operations & Algebraic Thinking',
    standardCodes: ['4.OA.4'],
    content: {
      intro: {
        title: 'Factors and Multiples',
        text: 'Numbers have special relationships with each other. Some numbers divide evenly into other numbers — those are called factors. When you multiply a number by 1, 2, 3, and so on, you get its multiples. Understanding factors and multiples helps you work with fractions, division, and many other math topics.',
      },
      segments: [
        {
          index: 0,
          title: 'What Are Factors?',
          text: 'A factor of a number divides into it evenly with no remainder. For example, the factors of 12 are 1, 2, 3, 4, 6, and 12 because each of these numbers divides evenly into 12. To find all the factors of a number, start at 1 and work your way up. Does 1 divide into 12? Yes: 1 x 12 = 12. Does 2? Yes: 2 x 6 = 12. Does 3? Yes: 3 x 4 = 12. Does 4? We already found it. You can stop looking when you reach a factor you already recorded.',
          keyVocabulary: ['factor', 'divide evenly', 'remainder', 'factor pair'],
          example: 'Factor pairs of 12: (1, 12), (2, 6), (3, 4). So the factors are 1, 2, 3, 4, 6, 12.',
        },
        {
          index: 1,
          title: 'What Are Multiples?',
          text: 'A multiple is what you get when you multiply a number by a whole number. The multiples of 5 are 5, 10, 15, 20, 25, 30, and so on — the list goes on forever! You find multiples by skip counting. The multiples of 3 are 3, 6, 9, 12, 15, 18, and so on. A number is always a multiple of itself (5 x 1 = 5) and a multiple of 1. If 20 is a multiple of 4, then 4 is a factor of 20. Factors and multiples are connected like two sides of the same coin.',
          keyVocabulary: ['multiple', 'skip counting', 'whole number', 'connected'],
        },
        {
          index: 2,
          title: 'Prime Numbers',
          text: 'A prime number has exactly two factors: 1 and itself. The number 7 is prime because its only factors are 1 and 7. The number 2 is the smallest prime number and the only even prime. The first several prime numbers are 2, 3, 5, 7, 11, 13, 17, 19, and 23. Notice that 1 is not prime because it has only one factor, not two. To test whether a number is prime, try dividing it by 2, 3, 5, and other small primes. If none divide evenly, the number is prime.',
          keyVocabulary: ['prime number', 'exactly two factors'],
        },
        {
          index: 3,
          title: 'Composite Numbers',
          text: 'A composite number has more than two factors. The number 12 is composite because it has six factors: 1, 2, 3, 4, 6, and 12. Every even number greater than 2 is composite because it is divisible by 2 and by itself and by 1. The numbers 4, 6, 8, 9, 10, 12, 14, and 15 are all composite. Remember: every whole number greater than 1 is either prime or composite. You can organize your thinking with a chart or list of factor pairs to decide which category a number falls into.',
          keyVocabulary: ['composite number', 'more than two factors', 'divisible'],
        },
      ],
      practice: [
        { index: 0, question: 'List all the factors of 18.', type: 'short-answer', correctAnswer: '1, 2, 3, 6, 9, 18', hint: 'Start with 1 x 18, then try 2, 3, and so on.', explanation: '1 x 18 = 18, 2 x 9 = 18, 3 x 6 = 18. Factors: 1, 2, 3, 6, 9, 18.', standardCode: '4.OA.4' },
        { index: 1, question: 'Is 13 prime or composite?', type: 'multiple-choice', options: ['Prime', 'Composite'], correctAnswer: 'Prime', hint: 'Try dividing 13 by 2, 3, and other small numbers.', explanation: '13 is not divisible by 2, 3, or any number other than 1 and 13. It is prime.', standardCode: '4.OA.4' },
        { index: 2, question: 'List the first five multiples of 6.', type: 'short-answer', correctAnswer: '6, 12, 18, 24, 30', hint: 'Multiply 6 by 1, 2, 3, 4, and 5.', explanation: '6 x 1 = 6, 6 x 2 = 12, 6 x 3 = 18, 6 x 4 = 24, 6 x 5 = 30.', standardCode: '4.OA.4' },
        { index: 3, question: 'Is 9 prime or composite?', type: 'multiple-choice', options: ['Prime', 'Composite'], correctAnswer: 'Composite', hint: 'Can any number besides 1 and 9 divide into 9?', explanation: '9 = 3 x 3, so it has factors 1, 3, and 9. That is more than two factors, so 9 is composite.', standardCode: '4.OA.4' },
        { index: 4, question: 'Find the factor pairs for 24.', type: 'short-answer', correctAnswer: '(1, 24), (2, 12), (3, 8), (4, 6)', hint: 'Start with 1 x 24 and keep going.', explanation: '1 x 24, 2 x 12, 3 x 8, 4 x 6. Those are all the factor pairs of 24.', standardCode: '4.OA.4' },
      ],
      assessment: {
        questions: [
          { question: 'List all the factors of 36.', type: 'short-answer', correctAnswer: '1, 2, 3, 4, 6, 9, 12, 18, 36', standardCode: '4.OA.4' },
          { question: 'Is 29 prime or composite?', type: 'multiple-choice', options: ['Prime', 'Composite'], correctAnswer: 'Prime', standardCode: '4.OA.4' },
          { question: 'Is 15 a multiple of 4?', type: 'multiple-choice', options: ['Yes', 'No'], correctAnswer: 'No', standardCode: '4.OA.4' },
        ],
      },
    },
  },
  {
    slug: 'grade4-math-angles-area-perimeter',
    title: 'Angles, Area, and Perimeter',
    description: 'Measure angles in degrees, and calculate the area and perimeter of rectangles',
    subject: 'math',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Measurement & Data',
    standardCodes: ['4.MD.5', '4.MD.3'],
    content: {
      intro: {
        title: 'Angles, Area, and Perimeter',
        text: 'Shapes are everywhere — from the floor tiles in your kitchen to the angles where walls meet. In this module you will learn to measure angles using degrees, and you will practice calculating how much space a shape covers (area) and how far it is around the outside (perimeter).',
      },
      segments: [
        {
          index: 0,
          title: 'Understanding Angles',
          text: 'An angle is formed where two rays meet at a common point called the vertex. We measure angles in degrees using the symbol for degrees. A full turn all the way around is 360 degrees. A right angle, like the corner of a book, is exactly 90 degrees. An angle less than 90 degrees is called acute, and an angle greater than 90 degrees but less than 180 degrees is called obtuse. A straight angle is exactly 180 degrees — it looks like a straight line. You can use a protractor to measure the exact number of degrees in an angle.',
          keyVocabulary: ['angle', 'vertex', 'degree', 'right angle', 'acute', 'obtuse', 'protractor'],
          example: 'The corner of a piece of paper is a right angle — exactly 90 degrees.',
        },
        {
          index: 1,
          title: 'Measuring with a Protractor',
          text: 'A protractor is a tool shaped like a half circle with degree markings from 0 to 180. To measure an angle, place the center point of the protractor on the vertex of the angle. Line up one ray with the 0-degree mark. Read where the other ray crosses the number scale. Be careful to read the correct scale — protractors have two rows of numbers. If the angle is acute, the measurement should be less than 90. If it is obtuse, it should be more than 90. Practice measuring angles in your classroom or home.',
          keyVocabulary: ['protractor', 'center point', 'scale', 'measure'],
        },
        {
          index: 2,
          title: 'Perimeter of Rectangles',
          text: 'The perimeter is the total distance around the outside of a shape. For a rectangle, add up all four sides. Since a rectangle has two pairs of equal sides, you can use the formula: Perimeter = 2 x length + 2 x width. For example, a rectangle with a length of 8 cm and a width of 5 cm has a perimeter of 2 x 8 + 2 x 5 = 16 + 10 = 26 cm. Perimeter is measured in units of length like centimeters, meters, inches, or feet.',
          keyVocabulary: ['perimeter', 'length', 'width', 'formula', 'distance around'],
          example: 'A garden is 10 feet long and 6 feet wide. Perimeter = 2 x 10 + 2 x 6 = 20 + 12 = 32 feet of fencing needed.',
        },
        {
          index: 3,
          title: 'Area of Rectangles',
          text: 'Area is the amount of space inside a flat shape, measured in square units. For a rectangle, use the formula: Area = length x width. A rectangle that is 7 inches long and 4 inches wide has an area of 7 x 4 = 28 square inches. Imagine covering the rectangle with 1-inch square tiles — you would need 28 tiles. Area is always reported in square units, such as square centimeters, square meters, or square feet. Do not confuse area with perimeter: area measures the space inside, and perimeter measures the distance around.',
          keyVocabulary: ['area', 'square units', 'length x width', 'space inside'],
        },
      ],
      practice: [
        { index: 0, question: 'A rectangle has a length of 12 cm and a width of 5 cm. What is its perimeter?', type: 'short-answer', correctAnswer: '34 cm', hint: 'Use the formula: Perimeter = 2 x length + 2 x width.', explanation: 'P = 2 x 12 + 2 x 5 = 24 + 10 = 34 cm.', standardCode: '4.MD.3' },
        { index: 1, question: 'What is the area of a rectangle that is 9 m long and 6 m wide?', type: 'short-answer', correctAnswer: '54 square meters', hint: 'Area = length x width.', explanation: 'A = 9 x 6 = 54 square meters.', standardCode: '4.MD.3' },
        { index: 2, question: 'An angle that measures exactly 90 degrees is called a:', type: 'multiple-choice', options: ['Acute angle', 'Right angle', 'Obtuse angle', 'Straight angle'], correctAnswer: 'Right angle', hint: 'Think of the corner of a book or a piece of paper.', explanation: 'A right angle is exactly 90 degrees. Acute is less than 90, and obtuse is between 90 and 180.', standardCode: '4.MD.5' },
        { index: 3, question: 'Is an angle of 45 degrees acute, right, or obtuse?', type: 'multiple-choice', options: ['Acute', 'Right', 'Obtuse'], correctAnswer: 'Acute', hint: 'Compare 45 to 90.', explanation: '45 is less than 90 degrees, so the angle is acute.', standardCode: '4.MD.5' },
        { index: 4, question: 'A rectangular playground is 30 m long and 20 m wide. What is its area?', type: 'short-answer', correctAnswer: '600 square meters', hint: 'Multiply the length by the width.', explanation: 'A = 30 x 20 = 600 square meters.', standardCode: '4.MD.3' },
      ],
      assessment: {
        questions: [
          { question: 'A rectangle has a perimeter of 28 inches. If the length is 10 inches, what is the width?', type: 'short-answer', correctAnswer: '4 inches', standardCode: '4.MD.3' },
          { question: 'An angle measures 135 degrees. Is it acute, right, or obtuse?', type: 'multiple-choice', options: ['Acute', 'Right', 'Obtuse'], correctAnswer: 'Obtuse', standardCode: '4.MD.5' },
          { question: 'A room is 8 feet long and 7 feet wide. What is the area of the floor?', type: 'short-answer', correctAnswer: '56 square feet', standardCode: '4.MD.3' },
        ],
      },
    },
  },
  {
    slug: 'grade4-math-multi-digit-division',
    title: 'Multi-Digit Division',
    description: 'Divide up to four-digit dividends by one-digit divisors using place value strategies and the standard algorithm',
    subject: 'math',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations in Base Ten',
    standardCodes: ['4.NBT.6'],
    content: {
      intro: {
        title: 'Multi-Digit Division',
        text: 'Division helps you split things into equal groups. You already know basic division facts, so now we will tackle dividing larger numbers — up to four digits — by a single-digit number. Whether you are sharing supplies equally among classrooms or figuring out how many weeks are in a certain number of days, multi-digit division is the tool you need.',
      },
      segments: [
        {
          index: 0,
          title: 'Dividing with Place Value',
          text: 'Just like multiplication, you can use place value to make division easier. Think of 84 divided by 4. Break 84 into 80 + 4. Divide each part: 80 / 4 = 20 and 4 / 4 = 1. Add the results: 20 + 1 = 21. This strategy works for bigger numbers too. For 936 / 3, think of it as 900 / 3 + 30 / 3 + 6 / 3 = 300 + 10 + 2 = 312. Breaking numbers into place-value parts turns a hard problem into several easy ones.',
          keyVocabulary: ['dividend', 'divisor', 'quotient', 'place value', 'break apart'],
          example: '648 / 2: 600 / 2 = 300, 40 / 2 = 20, 8 / 2 = 4. Quotient = 324.',
        },
        {
          index: 1,
          title: 'The Standard Algorithm for Division',
          text: 'The long division algorithm works digit by digit from left to right. To divide 5,724 by 4, start with the thousands place: 5 / 4 = 1 remainder 1. Write 1 above the 5. Bring down the 7 to make 17. 17 / 4 = 4 remainder 1. Bring down the 2 to make 12. 12 / 4 = 3 remainder 0. Bring down the 4. 4 / 4 = 1 remainder 0. The quotient is 1,431. At each step you divide, multiply, subtract, and bring down the next digit.',
          keyVocabulary: ['long division', 'algorithm', 'bring down', 'remainder'],
        },
        {
          index: 2,
          title: 'Interpreting Remainders',
          text: 'Sometimes division does not come out evenly and you get a remainder. For 29 / 6, the quotient is 4 with a remainder of 5, because 6 x 4 = 24 and 29 - 24 = 5. We write this as 29 / 6 = 4 R5. In word problems, you must decide what to do with the remainder. If 29 students need vans that hold 6 each, you need 5 vans (round up) because the remaining students still need a ride. If you are splitting 29 stickers equally among 6 friends, each gets 4 and there are 5 left over.',
          keyVocabulary: ['remainder', 'interpret', 'round up', 'leftover'],
          example: '43 / 5 = 8 R3. Check: 5 x 8 = 40, and 40 + 3 = 43.',
        },
      ],
      practice: [
        { index: 0, question: '96 / 4 = ?', type: 'short-answer', correctAnswer: '24', hint: 'Break 96 into 80 + 16, then divide each part by 4.', explanation: '80 / 4 = 20 and 16 / 4 = 4. So 96 / 4 = 24.', standardCode: '4.NBT.6' },
        { index: 1, question: '1,365 / 5 = ?', type: 'short-answer', correctAnswer: '273', hint: 'Use long division: start with 13 / 5.', explanation: '13 / 5 = 2 R3. Bring down 6 to get 36. 36 / 5 = 7 R1. Bring down 5 to get 15. 15 / 5 = 3. Quotient: 273.', standardCode: '4.NBT.6' },
        { index: 2, question: 'What is the remainder when 47 is divided by 6?', type: 'multiple-choice', options: ['1', '3', '5', '7'], correctAnswer: '5', hint: '6 x 7 = 42, so 47 - 42 = ?', explanation: '6 x 7 = 42 and 47 - 42 = 5. The remainder is 5.', standardCode: '4.NBT.6' },
        { index: 3, question: 'A teacher has 256 sheets of paper to divide equally among 8 students. How many sheets does each student get?', type: 'short-answer', correctAnswer: '32', hint: 'Divide 256 by 8.', explanation: '256 / 8 = 32. Each student gets 32 sheets.', standardCode: '4.NBT.6' },
        { index: 4, question: '3,648 / 6 = ?', type: 'short-answer', correctAnswer: '608', hint: 'Use long division. 36 / 6 = 6, then bring down the 4.', explanation: '36 / 6 = 6. Bring down 4: 4 / 6 = 0 R4. Bring down 8: 48 / 6 = 8. Quotient: 608.', standardCode: '4.NBT.6' },
      ],
      assessment: {
        questions: [
          { question: '2,436 / 3 = ?', type: 'short-answer', correctAnswer: '812', standardCode: '4.NBT.6' },
          { question: 'A factory packs 4,520 crayons into boxes of 8. How many full boxes are there and how many crayons are left over?', type: 'short-answer', correctAnswer: '565 boxes with 0 left over', standardCode: '4.NBT.6' },
          { question: 'What is 987 / 7?', type: 'multiple-choice', options: ['139', '141', '140', '142'], correctAnswer: '141', standardCode: '4.NBT.6' },
        ],
      },
    },
  },
  {
    slug: 'grade4-math-multiplying-fractions-whole',
    title: 'Multiplying Fractions by Whole Numbers',
    description: 'Understand a fraction as a multiple of a unit fraction and multiply fractions by whole numbers',
    subject: 'math',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations—Fractions',
    standardCodes: ['4.NF.4'],
    content: {
      intro: {
        title: 'Multiplying Fractions by Whole Numbers',
        text: 'You already know how to add fractions with the same denominator. But what if you need to add 1/5 + 1/5 + 1/5? That is the same as 3 x 1/5! In this module you will learn that every fraction is really a whole number times a unit fraction, and you will practice multiplying fractions by whole numbers.',
      },
      segments: [
        {
          index: 0,
          title: 'Unit Fractions and Multiples',
          text: 'A unit fraction has a 1 in the numerator, like 1/2, 1/3, 1/4, or 1/8. Any fraction can be written as a multiple of a unit fraction. The fraction 3/4 means 3 copies of 1/4, which is the same as 3 x 1/4. Similarly, 5/6 = 5 x 1/6. This is a powerful idea because it connects fractions to multiplication. When you see a fraction, think of it as repeated addition of its unit fraction: 3/4 = 1/4 + 1/4 + 1/4.',
          keyVocabulary: ['unit fraction', 'multiple', 'copies', 'repeated addition'],
          example: '4/5 = 4 x 1/5 = 1/5 + 1/5 + 1/5 + 1/5',
        },
        {
          index: 1,
          title: 'Multiplying a Whole Number by a Fraction',
          text: 'To multiply a whole number by a fraction, multiply the whole number by the numerator and keep the denominator the same. For example, 3 x 2/5: multiply 3 x 2 = 6, keep the denominator 5, so the answer is 6/5, which equals 1 1/5 as a mixed number. Another example: 4 x 3/8 = 12/8 = 1 4/8 = 1 1/2. Always simplify your answer and convert improper fractions to mixed numbers when possible.',
          keyVocabulary: ['multiply', 'numerator', 'denominator', 'improper fraction', 'mixed number'],
        },
        {
          index: 2,
          title: 'Word Problems with Fraction Multiplication',
          text: 'Fraction multiplication shows up in everyday life. Suppose each serving of juice is 2/3 of a cup and you need 5 servings. How much juice do you need? Multiply 5 x 2/3 = 10/3 = 3 1/3 cups. Or imagine you walk 3/4 of a mile each day for 4 days. The total distance is 4 x 3/4 = 12/4 = 3 miles. Look for key words like "each," "every," and "per" to know when to multiply a fraction by a whole number.',
          keyVocabulary: ['serving', 'total', 'per', 'each', 'word problem'],
          example: 'A recipe uses 1/3 cup of sugar. If you triple the recipe, you need 3 x 1/3 = 3/3 = 1 cup of sugar.',
        },
      ],
      practice: [
        { index: 0, question: 'Write 5/8 as a multiplication expression using a unit fraction.', type: 'short-answer', correctAnswer: '5 x 1/8', hint: 'A unit fraction has 1 as the numerator.', explanation: '5/8 means 5 copies of 1/8, so 5/8 = 5 x 1/8.', standardCode: '4.NF.4' },
        { index: 1, question: '4 x 2/3 = ?', type: 'short-answer', correctAnswer: '8/3 or 2 2/3', hint: 'Multiply 4 by the numerator and keep the denominator.', explanation: '4 x 2 = 8, denominator stays 3: 8/3 = 2 2/3.', standardCode: '4.NF.4' },
        { index: 2, question: '6 x 1/4 = ?', type: 'multiple-choice', options: ['6/4', '4/6', '1/24', '6/24'], correctAnswer: '6/4', hint: 'Multiply 6 by the numerator 1 and keep denominator 4.', explanation: '6 x 1/4 = 6/4, which simplifies to 1 2/4 or 1 1/2.', standardCode: '4.NF.4' },
        { index: 3, question: 'Each ribbon is 3/5 of a yard long. If you cut 5 ribbons, what is the total length?', type: 'short-answer', correctAnswer: '3 yards', hint: 'Multiply 5 x 3/5.', explanation: '5 x 3/5 = 15/5 = 3 yards.', standardCode: '4.NF.4' },
        { index: 4, question: '7 x 3/10 = ? Simplify if possible.', type: 'short-answer', correctAnswer: '21/10 or 2 1/10', hint: 'Multiply 7 by the numerator 3.', explanation: '7 x 3 = 21. The answer is 21/10 = 2 1/10.', standardCode: '4.NF.4' },
      ],
      assessment: {
        questions: [
          { question: '3 x 5/6 = ? Write as a mixed number.', type: 'short-answer', correctAnswer: '2 3/6 or 2 1/2', standardCode: '4.NF.4' },
          { question: 'A hamster drinks 2/5 of a bottle of water each day. How many bottles does it drink in 7 days?', type: 'short-answer', correctAnswer: '14/5 or 2 4/5', standardCode: '4.NF.4' },
          { question: 'Which expression equals 9/4?', type: 'multiple-choice', options: ['4 x 1/9', '9 x 1/4', '9 x 4', '1 x 9/4'], correctAnswer: '9 x 1/4', standardCode: '4.NF.4' },
        ],
      },
    },
  },
  {
    slug: 'grade4-math-decimal-notation',
    title: 'Decimal Notation for Fractions',
    description: 'Use decimal notation for fractions with denominators of 10 or 100 and compare decimal values',
    subject: 'math',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations—Fractions',
    standardCodes: ['4.NF.6'],
    content: {
      intro: {
        title: 'Decimal Notation for Fractions',
        text: 'You see decimals every day — on price tags, sports statistics, and thermometers. A decimal is really just another way to write a fraction! In this module you will learn how fractions with denominators of 10 and 100 connect to decimal notation, and you will practice reading, writing, and comparing decimals.',
      },
      segments: [
        {
          index: 0,
          title: 'Tenths as Decimals',
          text: 'When a whole is divided into 10 equal parts, each part is one tenth, or 1/10. In decimal form, 1/10 is written as 0.1. The digit after the decimal point is in the tenths place. So 3/10 = 0.3, 7/10 = 0.7, and 10/10 = 1.0. If you have more than 10 tenths, you get a number greater than 1. For example, 14/10 = 1.4, which means 1 whole and 4 tenths. Think of a number line from 0 to 1 split into 10 equal segments — each mark represents one tenth.',
          keyVocabulary: ['tenth', 'decimal point', 'tenths place', 'decimal notation'],
          example: '5/10 = 0.5. On a number line this is exactly halfway between 0 and 1.',
        },
        {
          index: 1,
          title: 'Hundredths as Decimals',
          text: 'When a whole is divided into 100 equal parts, each part is one hundredth, or 1/100. In decimal form, 1/100 = 0.01. The second digit after the decimal point is the hundredths place. So 25/100 = 0.25, 99/100 = 0.99, and 100/100 = 1.00. Money uses hundredths — one penny is 1/100 of a dollar, so $0.01. A dime is 10/100 = 0.10 of a dollar. Understanding hundredths helps you read prices, measurements, and more.',
          keyVocabulary: ['hundredth', 'hundredths place', 'penny', 'dime'],
        },
        {
          index: 2,
          title: 'Converting Between Tenths and Hundredths',
          text: 'Since 1/10 = 10/100, you can always rewrite a tenths fraction as a hundredths fraction. For example, 3/10 = 30/100. In decimal form, 0.3 = 0.30 — adding a zero at the end of a decimal does not change its value. This is useful when adding or comparing fractions with different denominators. To add 3/10 + 4/100, rewrite 3/10 as 30/100, then add: 30/100 + 4/100 = 34/100 = 0.34.',
          keyVocabulary: ['convert', 'equivalent', 'adding decimals'],
          example: '7/10 = 70/100 = 0.70. So 7/10 + 5/100 = 70/100 + 5/100 = 75/100 = 0.75.',
        },
        {
          index: 3,
          title: 'Comparing Decimals',
          text: 'To compare decimals, start from the left and compare digit by digit. First compare the ones place, then the tenths, then the hundredths. For example, compare 0.6 and 0.45: the ones digits are both 0. In the tenths place, 6 > 4, so 0.6 > 0.45. It helps to make both decimals the same length: 0.6 = 0.60, and 0.60 > 0.45. Use the symbols >, <, or = to show your comparison. Remember, a larger digit in a higher place value always wins.',
          keyVocabulary: ['compare', 'greater than', 'less than', 'equal to', 'place value'],
        },
      ],
      practice: [
        { index: 0, question: 'Write 4/10 as a decimal.', type: 'short-answer', correctAnswer: '0.4', hint: '4/10 means 4 tenths.', explanation: '4/10 = 0.4. The 4 goes in the tenths place.', standardCode: '4.NF.6' },
        { index: 1, question: 'Write 63/100 as a decimal.', type: 'short-answer', correctAnswer: '0.63', hint: '63 hundredths means the digits 6 and 3 go after the decimal point.', explanation: '63/100 = 0.63. The 6 is in the tenths place and the 3 is in the hundredths place.', standardCode: '4.NF.6' },
        { index: 2, question: 'Which decimal is greater: 0.8 or 0.75?', type: 'multiple-choice', options: ['0.8', '0.75', 'They are equal'], correctAnswer: '0.8', hint: 'Rewrite 0.8 as 0.80 and compare.', explanation: '0.80 > 0.75 because 80 hundredths is more than 75 hundredths.', standardCode: '4.NF.6' },
        { index: 3, question: 'What is 3/10 + 7/100 written as a decimal?', type: 'short-answer', correctAnswer: '0.37', hint: 'Convert 3/10 to 30/100 first, then add.', explanation: '3/10 = 30/100. 30/100 + 7/100 = 37/100 = 0.37.', standardCode: '4.NF.6' },
        { index: 4, question: 'Write the decimal 0.09 as a fraction.', type: 'short-answer', correctAnswer: '9/100', hint: 'The 9 is in the hundredths place.', explanation: '0.09 means 9 hundredths, which is 9/100.', standardCode: '4.NF.6' },
      ],
      assessment: {
        questions: [
          { question: 'Write 52/100 as a decimal.', type: 'short-answer', correctAnswer: '0.52', standardCode: '4.NF.6' },
          { question: 'Compare using < or >: 0.3 ___ 0.29.', type: 'short-answer', correctAnswer: '>', standardCode: '4.NF.6' },
          { question: 'Which fraction equals 0.70?', type: 'multiple-choice', options: ['7/100', '70/100', '7/1000', '70/10'], correctAnswer: '70/100', standardCode: '4.NF.6' },
        ],
      },
    },
  },
  {
    slug: 'grade4-math-line-plots-fractions',
    title: 'Line Plots with Fractions',
    description: 'Make and interpret line plots to display data sets involving fractional measurements',
    subject: 'math',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Measurement & Data',
    standardCodes: ['4.MD.4'],
    content: {
      intro: {
        title: 'Line Plots with Fractions',
        text: 'Scientists, cooks, and builders often measure things and get fractions like 1/2 inch or 3/4 cup. A line plot is a great way to organize and display measurement data that includes fractions. In this module you will learn how to create line plots, read them, and answer questions using the data.',
      },
      segments: [
        {
          index: 0,
          title: 'What Is a Line Plot?',
          text: 'A line plot is a graph that shows data on a number line. Each piece of data is marked with an X (or a dot) above the number line at the correct value. If more than one measurement has the same value, the Xs stack up. Line plots make it easy to see the most common value, the range, and any gaps or clusters. For example, if five students measured the length of leaves and got 2 inches, 2 1/2 inches, 2 inches, 3 inches, and 2 1/2 inches, you would draw a number line from 2 to 3 and mark each value.',
          keyVocabulary: ['line plot', 'number line', 'data', 'X', 'cluster', 'gap'],
          example: 'Leaf lengths: 2, 2 1/2, 2, 3, 2 1/2. The line plot has two Xs at 2, two Xs at 2 1/2, and one X at 3.',
        },
        {
          index: 1,
          title: 'Creating a Line Plot with Fractions',
          text: 'To create a line plot with fractional data, first look at all the values and decide on a scale. If your measurements involve halves, mark every 1/2 on the number line. If they involve fourths, mark every 1/4. If they involve eighths, mark every 1/8. Then go through each measurement and place an X above its position. Make sure to give your line plot a title and label the number line with the unit of measurement. Careful spacing matters — the distance between 0 and 1/4 should be the same as between 1/4 and 2/4.',
          keyVocabulary: ['scale', 'halves', 'fourths', 'eighths', 'label', 'title'],
        },
        {
          index: 2,
          title: 'Interpreting Line Plots',
          text: 'Once your line plot is drawn, you can answer questions about the data. How many measurements are there in total? Count all the Xs. What is the most common measurement? Look for the tallest stack of Xs. What is the difference between the longest and shortest measurement? Subtract the smallest value from the largest. You might also be asked to add or subtract the data values. For example, "What is the total length of all the ribbons measured?" would require you to add all the fractional lengths together.',
          keyVocabulary: ['interpret', 'most common', 'range', 'total', 'difference'],
          example: 'If a line plot shows 3 Xs at 1/4, 2 Xs at 1/2, and 1 X at 3/4, the total of all values is 3/4 + 2/2 + 3/4 = 3/4 + 1 + 3/4 = 2 2/4 = 2 1/2.',
        },
      ],
      practice: [
        { index: 0, question: 'A data set of plant heights in inches is: 3, 3 1/4, 3 1/2, 3 1/4, 3, 3 1/2, 3 1/4. How many Xs would be above 3 1/4 on the line plot?', type: 'short-answer', correctAnswer: '3', hint: 'Count how many times 3 1/4 appears in the data.', explanation: '3 1/4 appears three times, so there are 3 Xs above that value.', standardCode: '4.MD.4' },
        { index: 1, question: 'Using the same data set, what is the most common measurement?', type: 'multiple-choice', options: ['3 inches', '3 1/4 inches', '3 1/2 inches', '3 3/4 inches'], correctAnswer: '3 1/4 inches', hint: 'Which value appears most often?', explanation: '3 1/4 appears 3 times, more than any other value.', standardCode: '4.MD.4' },
        { index: 2, question: 'A line plot shows water amounts: two Xs at 1/2 cup and three Xs at 3/4 cup. What is the total amount of water?', type: 'short-answer', correctAnswer: '3 1/4 cups', hint: 'Add 1/2 + 1/2 + 3/4 + 3/4 + 3/4.', explanation: '2 x 1/2 = 1 cup. 3 x 3/4 = 9/4 = 2 1/4 cups. Total: 1 + 2 1/4 = 3 1/4 cups.', standardCode: '4.MD.4' },
        { index: 3, question: 'What is the range of a data set if the smallest value is 1/8 inch and the largest is 7/8 inch?', type: 'short-answer', correctAnswer: '6/8 or 3/4 inch', hint: 'Subtract the smallest from the largest.', explanation: '7/8 - 1/8 = 6/8 = 3/4 inch.', standardCode: '4.MD.4' },
        { index: 4, question: 'True or false: On a line plot, the number of Xs tells you how many data points have that value.', type: 'multiple-choice', options: ['True', 'False'], correctAnswer: 'True', hint: 'Think about what each X represents.', explanation: 'Each X represents one measurement, so stacked Xs show how many data points share that value.', standardCode: '4.MD.4' },
      ],
      assessment: {
        questions: [
          { question: 'Students measured pencil lengths in inches: 5 1/2, 6, 5 1/2, 5 3/4, 6, 6, 5 3/4. What value has the most Xs on the line plot?', type: 'multiple-choice', options: ['5 1/2', '5 3/4', '6'], correctAnswer: '6', standardCode: '4.MD.4' },
          { question: 'Using the pencil data above, how many total measurements were taken?', type: 'short-answer', correctAnswer: '7', standardCode: '4.MD.4' },
          { question: 'A line plot shows four Xs at 1/4 pound and two Xs at 3/4 pound. What is the total weight of all items?', type: 'short-answer', correctAnswer: '2 1/2 pounds', standardCode: '4.MD.4' },
        ],
      },
    },
  },
  {
    slug: 'grade4-math-lines-rays-angles',
    title: 'Lines, Rays, and Angles',
    description: 'Draw and identify lines, rays, angles, and perpendicular and parallel lines',
    subject: 'math',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Geometry',
    standardCodes: ['4.G.1'],
    content: {
      intro: {
        title: 'Lines, Rays, and Angles',
        text: 'Geometry is all around you — from the edges of your desk to the beams of sunlight coming through a window. In this module you will learn to identify and draw different geometric figures: lines, line segments, rays, and angles. You will also discover what it means for lines to be parallel or perpendicular.',
      },
      segments: [
        {
          index: 0,
          title: 'Points, Lines, and Line Segments',
          text: 'A point is an exact location, often drawn as a dot and labeled with a capital letter like point A. A line goes on forever in both directions and is perfectly straight. We draw it with arrows on both ends and name it using two points on the line, such as line AB. A line segment is part of a line with two endpoints. It has a definite length. The edge of your ruler is a line segment. We name it segment AB, using its two endpoints.',
          keyVocabulary: ['point', 'line', 'line segment', 'endpoint', 'straight'],
          example: 'The top edge of a book is a line segment. If you extended it in both directions forever, it would become a line.',
        },
        {
          index: 1,
          title: 'Rays and Angles',
          text: 'A ray starts at one point and goes on forever in one direction. Think of a flashlight beam — it starts at the flashlight and continues outward. We name a ray by its endpoint first, then another point on the ray, such as ray AB. An angle is formed where two rays share the same endpoint, called the vertex. Angles are measured in degrees. A right angle is 90 degrees, an acute angle is less than 90 degrees, and an obtuse angle is between 90 and 180 degrees.',
          keyVocabulary: ['ray', 'angle', 'vertex', 'acute', 'right', 'obtuse', 'degree'],
        },
        {
          index: 2,
          title: 'Perpendicular Lines',
          text: 'Two lines are perpendicular if they meet to form a right angle — exactly 90 degrees. The corner of a piece of paper shows perpendicular edges. Perpendicular lines can be found everywhere: the legs of a table meet the floor at right angles, and the lines on graph paper are perpendicular. We use a small square at the corner where perpendicular lines meet to show the right angle. The symbol for perpendicular is a sideways T.',
          keyVocabulary: ['perpendicular', 'right angle', '90 degrees', 'symbol'],
          example: 'The letter T has two perpendicular line segments — the horizontal bar meets the vertical bar at a right angle.',
        },
        {
          index: 3,
          title: 'Parallel Lines',
          text: 'Parallel lines run in the same direction and never cross, no matter how far they extend. Think of railroad tracks or the opposite edges of a ruler. Parallel lines are always the same distance apart. We use arrows on the lines or the symbol with two vertical bars to show that lines are parallel. In shapes, opposite sides of a rectangle are parallel. Lines that are not parallel and not perpendicular are called intersecting lines — they cross but not at a right angle.',
          keyVocabulary: ['parallel', 'never cross', 'same distance apart', 'intersecting'],
        },
      ],
      practice: [
        { index: 0, question: 'How is a ray different from a line?', type: 'multiple-choice', options: ['A ray has two endpoints', 'A ray has one endpoint and goes on forever in one direction', 'A ray has no endpoints', 'A ray is curved'], correctAnswer: 'A ray has one endpoint and goes on forever in one direction', hint: 'Think about where a ray starts and where it ends (or does not end).', explanation: 'A line has no endpoints and goes forever in both directions. A ray has exactly one endpoint and extends forever in one direction.', standardCode: '4.G.1' },
        { index: 1, question: 'Two lines meet to form a 90-degree angle. What are these lines called?', type: 'short-answer', correctAnswer: 'perpendicular', hint: 'What special name do we give to lines that form right angles?', explanation: 'Lines that meet at exactly 90 degrees are called perpendicular lines.', standardCode: '4.G.1' },
        { index: 2, question: 'Which of the following best describes parallel lines?', type: 'multiple-choice', options: ['They cross at a right angle', 'They never cross and stay the same distance apart', 'They meet at an acute angle', 'They share an endpoint'], correctAnswer: 'They never cross and stay the same distance apart', hint: 'Think of railroad tracks.', explanation: 'Parallel lines go in the same direction and never intersect.', standardCode: '4.G.1' },
        { index: 3, question: 'Name the geometric figure: it starts at point A and passes through point B, continuing forever past B.', type: 'short-answer', correctAnswer: 'ray AB', hint: 'It has one endpoint and goes on in one direction.', explanation: 'A ray starts at one point (A) and goes through another point (B), continuing forever in that direction.', standardCode: '4.G.1' },
        { index: 4, question: 'An angle of 120 degrees is classified as:', type: 'multiple-choice', options: ['Acute', 'Right', 'Obtuse', 'Straight'], correctAnswer: 'Obtuse', hint: 'Compare 120 to 90 and 180.', explanation: '120 degrees is between 90 and 180 degrees, so it is an obtuse angle.', standardCode: '4.G.1' },
      ],
      assessment: {
        questions: [
          { question: 'How many endpoints does a line segment have?', type: 'multiple-choice', options: ['0', '1', '2', 'Infinite'], correctAnswer: '2', standardCode: '4.G.1' },
          { question: 'Give an example of parallel lines you might see in everyday life.', type: 'short-answer', correctAnswer: 'railroad tracks', standardCode: '4.G.1' },
          { question: 'Two lines cross at a 50-degree angle. Are they perpendicular?', type: 'multiple-choice', options: ['Yes', 'No'], correctAnswer: 'No', standardCode: '4.G.1' },
        ],
      },
    },
  },
  {
    slug: 'grade4-math-patterns-rules',
    title: 'Patterns and Rules',
    description: 'Generate number or shape patterns that follow a given rule and identify features of the pattern',
    subject: 'math',
    grade: 4,
    gradeBand: 'k5',
    topicCluster: 'Operations & Algebraic Thinking',
    standardCodes: ['4.OA.5'],
    content: {
      intro: {
        title: 'Patterns and Rules',
        text: 'Patterns are one of the most important ideas in mathematics. A pattern is a sequence that follows a rule, and once you discover the rule you can predict what comes next. In this module you will learn to create, extend, and analyze number and shape patterns, and you will explore features like whether values are always odd or always even.',
      },
      segments: [
        {
          index: 0,
          title: 'Understanding Rules for Patterns',
          text: 'A rule tells you how to get from one number to the next in a pattern. For example, the rule "add 3" starting at 1 gives: 1, 4, 7, 10, 13, 16, and so on. The rule "multiply by 2" starting at 3 gives: 3, 6, 12, 24, 48. The starting number and the rule together define the entire pattern. To find a rule, look at what operation connects one term to the next. If the terms are 5, 10, 15, 20, each term is 5 more than the one before, so the rule is "add 5."',
          keyVocabulary: ['rule', 'pattern', 'term', 'sequence', 'operation'],
          example: 'Rule: add 6, start at 2. Pattern: 2, 8, 14, 20, 26, 32.',
        },
        {
          index: 1,
          title: 'Identifying Features of Patterns',
          text: 'Once you generate a pattern, you can observe interesting features. Look at the pattern with rule "add 2" starting at 1: 1, 3, 5, 7, 9, 11. Every number in this pattern is odd! Now start at 2 with the same rule: 2, 4, 6, 8, 10, 12. Every number is even! When you add an even number to an even number, the result is always even. When you add an even number to an odd number, the result is always odd. These observations help you predict features of a pattern without listing every term.',
          keyVocabulary: ['odd', 'even', 'feature', 'observation', 'predict'],
        },
        {
          index: 2,
          title: 'Shape Patterns',
          text: 'Patterns are not just about numbers — shapes can follow rules too. Imagine a pattern: circle, square, triangle, circle, square, triangle. The rule is to repeat the group of three shapes. You can predict that the 10th shape is a circle because 10 / 3 has a remainder of 1, and the first shape in the group is a circle. Shape patterns can also grow. A pattern of triangles might have 1 triangle in step 1, 3 in step 2, 6 in step 3. The rule involves adding one more than you added before. Drawing the pattern helps you see the structure.',
          keyVocabulary: ['shape pattern', 'repeating', 'growing', 'predict', 'structure'],
          example: 'Pattern: square, circle, circle, square, circle, circle. The rule repeats every 3 shapes. The 7th shape is a square.',
        },
      ],
      practice: [
        { index: 0, question: 'Use the rule "add 7" starting at 4. Write the first five terms.', type: 'short-answer', correctAnswer: '4, 11, 18, 25, 32', hint: 'Start with 4, then keep adding 7.', explanation: '4, 4 + 7 = 11, 11 + 7 = 18, 18 + 7 = 25, 25 + 7 = 32.', standardCode: '4.OA.5' },
        { index: 1, question: 'What is the rule for this pattern: 5, 10, 20, 40, 80?', type: 'multiple-choice', options: ['Add 5', 'Add 10', 'Multiply by 2', 'Multiply by 3'], correctAnswer: 'Multiply by 2', hint: 'Compare each term to the one before it.', explanation: '5 x 2 = 10, 10 x 2 = 20, 20 x 2 = 40, 40 x 2 = 80. The rule is multiply by 2.', standardCode: '4.OA.5' },
        { index: 2, question: 'A pattern starts at 3 and uses the rule "add 4." Are the numbers in this pattern always odd, always even, or alternating?', type: 'multiple-choice', options: ['Always odd', 'Always even', 'Alternating'], correctAnswer: 'Always odd', hint: 'Write the first few terms: 3, 7, 11, 15...', explanation: '3, 7, 11, 15, 19 — they are all odd. Starting at an odd number and adding an even number always gives an odd result.', standardCode: '4.OA.5' },
        { index: 3, question: 'A shape pattern repeats: triangle, triangle, square. What is the 11th shape?', type: 'multiple-choice', options: ['Triangle', 'Square'], correctAnswer: 'Triangle', hint: 'The pattern repeats every 3 shapes. What is the remainder of 11 / 3?', explanation: '11 / 3 = 3 remainder 2. The 2nd shape in the group is triangle. So the 11th shape is a triangle.', standardCode: '4.OA.5' },
        { index: 4, question: 'Find the next two terms: 100, 90, 80, 70, ___, ___.', type: 'short-answer', correctAnswer: '60, 50', hint: 'What number is being subtracted each time?', explanation: 'The rule is subtract 10. 70 - 10 = 60 and 60 - 10 = 50.', standardCode: '4.OA.5' },
      ],
      assessment: {
        questions: [
          { question: 'Generate the first six terms with the rule "add 9" starting at 2.', type: 'short-answer', correctAnswer: '2, 11, 20, 29, 38, 47', standardCode: '4.OA.5' },
          { question: 'A pattern starts at 6 and follows the rule "multiply by 3." What is the 4th term?', type: 'multiple-choice', options: ['54', '162', '18', '486'], correctAnswer: '162', standardCode: '4.OA.5' },
          { question: 'Describe one feature of the pattern: 2, 6, 10, 14, 18, 22.', type: 'short-answer', correctAnswer: 'All terms are even', standardCode: '4.OA.5' },
        ],
      },
    },
  },
]
