import type { ModuleSeed } from '../types'

export const GRADE_3_ELA: ModuleSeed[] = [
  {
    slug: 'grade3-ela-theme-central-message',
    title: 'Finding the Central Message',
    description: 'Recount stories and determine the central message, lesson, or moral',
    subject: 'ela',
    grade: 3,
    gradeBand: 'k5',
    topicCluster: 'Reading Literature',
    standardCodes: ['3.RL.2'],
    content: {
      intro: {
        title: 'Finding the Central Message',
        text: 'Every story has a big idea that the author wants you to understand. This big idea is called the central message, lesson, or moral. When you read a story, you are not just following what happens — you are also figuring out what the story is really trying to teach you. Today we will learn how to recount a story and find its central message.',
      },
      segments: [
        {
          index: 0,
          title: 'What Is a Central Message?',
          text: 'The central message is the most important idea or lesson in a story. It is different from the topic. The topic might be "friendship," but the central message might be "true friends help each other even when it is hard." Authors do not always tell you the message directly. Instead, they show it through what the characters do, say, and learn. Think about how the main character changes from the beginning to the end. That change often reveals the central message.',
          keyVocabulary: ['central message', 'moral', 'lesson', 'topic'],
          example: 'In "The Tortoise and the Hare," the topic is a race, but the central message is "slow and steady wins the race."',
        },
        {
          index: 1,
          title: 'Recounting a Story',
          text: 'Before you can find the central message, you need to recount the story. Recounting means retelling the important parts in order. Start with who the main characters are and what they want. Then tell the key events: what happens first, next, and last. Focus on the most important events — you do not need every little detail. A good recount includes the problem the character faces and how the problem is solved.',
          keyVocabulary: ['recount', 'retell', 'key events', 'sequence'],
        },
        {
          index: 2,
          title: 'Finding the Message in Characters and Events',
          text: 'To figure out the central message, pay close attention to how the characters act and what happens because of their actions. Ask yourself: What mistake does the character make? What does the character learn? How does the character change? If a character is selfish at the start but learns to share by the end, the message might be "sharing makes everyone happier." The events in the story are clues that lead you to the big idea.',
          keyVocabulary: ['character actions', 'consequences', 'clues', 'change'],
        },
        {
          index: 3,
          title: 'Stating the Central Message',
          text: 'Once you figure out the central message, state it in a complete sentence. A good central message statement sounds like a life lesson that could apply to anyone, not just the characters in the story. For example, instead of saying "Tom learned to be honest," say "Being honest is important even when the truth is hard to tell." Use details from the story to explain how the events support the message you identified. This shows you truly understand what the story teaches.',
          keyVocabulary: ['life lesson', 'support', 'details', 'evidence'],
        },
      ],
      practice: [
        {
          index: 0,
          question: 'A story is about a girl who refuses to practice piano but then fails her recital. She starts practicing every day and succeeds at the next recital. What is the central message?',
          type: 'multiple-choice',
          options: [
            'Pianos are fun to play.',
            'Practice and hard work lead to success.',
            'Recitals are scary.',
            'Girls should play piano.',
          ],
          correctAnswer: 'Practice and hard work lead to success.',
          hint: 'Think about what the girl learned from her experience.',
          explanation: 'The girl failed when she did not practice, then succeeded when she worked hard. The message is that practice and hard work lead to success.',
          standardCode: '3.RL.2',
        },
        {
          index: 1,
          question: 'What is the difference between a topic and a central message?',
          type: 'multiple-choice',
          options: [
            'They are the same thing.',
            'The topic is one word or phrase; the central message is the lesson the story teaches.',
            'The topic is longer than the central message.',
            'The central message is the title of the story.',
          ],
          correctAnswer: 'The topic is one word or phrase; the central message is the lesson the story teaches.',
          hint: 'A topic is broad, like "courage." A central message is a specific lesson about that topic.',
          explanation: 'The topic is a general subject like "friendship." The central message is the specific lesson, like "true friends stick together in hard times."',
          standardCode: '3.RL.2',
        },
        {
          index: 2,
          question: 'When recounting a story, which should you include?',
          type: 'multiple-choice',
          options: [
            'Every single detail in the story',
            'Only the last event',
            'The main characters, key events, and how the problem is solved',
            'Just the title and the author',
          ],
          correctAnswer: 'The main characters, key events, and how the problem is solved',
          hint: 'A recount focuses on the most important parts, told in order.',
          explanation: 'When recounting, include the main characters, the key events in order, the problem, and the solution — not every small detail.',
          standardCode: '3.RL.2',
        },
        {
          index: 3,
          question: 'In a story, a boy lies to his friend and his friend stops talking to him. The boy apologizes and promises to always tell the truth. What is the central message?',
          type: 'short-answer',
          correctAnswer: 'Honesty is important in friendship.',
          hint: 'What did the boy learn about lying and friendship?',
          explanation: 'The boy learned that lying hurt his friendship. The central message is that honesty is important in friendships.',
          standardCode: '3.RL.2',
        },
        {
          index: 4,
          question: 'Which question best helps you find the central message of a story?',
          type: 'multiple-choice',
          options: [
            'What color is the main character\'s hair?',
            'What does the main character learn by the end?',
            'How many pages is the story?',
            'What is the setting of the story?',
          ],
          correctAnswer: 'What does the main character learn by the end?',
          hint: 'The central message is about what lesson the story teaches.',
          explanation: 'Asking what the character learns helps you identify the lesson or moral, which is the central message.',
          standardCode: '3.RL.2',
        },
      ],
      assessment: {
        questions: [
          {
            question: 'A fox brags about being the fastest animal but loses a race to a turtle who never gives up. What is the central message?',
            type: 'short-answer',
            correctAnswer: 'Never give up, because being steady and determined can beat natural talent.',
            standardCode: '3.RL.2',
          },
          {
            question: 'Which best describes what "recounting a story" means?',
            type: 'multiple-choice',
            options: [
              'Reading the story out loud',
              'Retelling the most important events in order',
              'Copying the story word for word',
              'Drawing a picture of the story',
            ],
            correctAnswer: 'Retelling the most important events in order',
            standardCode: '3.RL.2',
          },
          {
            question: 'A central message should sound like which of the following?',
            type: 'multiple-choice',
            options: [
              'A summary of the whole story',
              'A life lesson that could apply to anyone',
              'A description of the main character',
              'The title of the book',
            ],
            correctAnswer: 'A life lesson that could apply to anyone',
            standardCode: '3.RL.2',
          },
        ],
      },
    },
  },
  {
    slug: 'grade3-ela-point-of-view',
    title: 'Understanding Point of View',
    description: 'Distinguish your own point of view from that of the narrator or characters',
    subject: 'ela',
    grade: 3,
    gradeBand: 'k5',
    topicCluster: 'Reading Literature',
    standardCodes: ['3.RL.6'],
    content: {
      intro: {
        title: 'Understanding Point of View',
        text: 'When you read a story, you might agree or disagree with what a character thinks. That is because you have your own point of view! A point of view is how someone thinks or feels about something. Today we will learn to tell the difference between your point of view and the narrator\'s or character\'s point of view.',
      },
      segments: [
        {
          index: 0,
          title: 'What Is Point of View?',
          text: 'Point of view means who is telling the story and what they think and feel. A narrator is the person telling the story. Sometimes the narrator is a character in the story and uses words like "I" and "me." This is called first person. Other times, the narrator is outside the story and uses "he," "she," or "they." This is called third person. The narrator\'s point of view shapes how the story is told and what information you receive.',
          keyVocabulary: ['point of view', 'narrator', 'first person', 'third person'],
        },
        {
          index: 1,
          title: 'The Character\'s Point of View',
          text: 'Characters in a story each have their own point of view. One character might think something is a great idea, while another character disagrees. To find a character\'s point of view, look at their words, thoughts, and actions. If a character says "I think we should explore the cave," that tells you the character is brave and curious. Another character might say "The cave looks dangerous," which shows a more cautious point of view.',
          keyVocabulary: ['character', 'thoughts', 'actions', 'words'],
          example: 'In a story, Sam says "Spiders are cool!" but Mia says "Spiders are scary!" They have different points of view about spiders.',
        },
        {
          index: 2,
          title: 'Your Own Point of View',
          text: 'As a reader, you also have a point of view. You bring your own experiences, feelings, and ideas to every story you read. Your point of view might be different from the narrator\'s or the character\'s. For example, a character might think it is okay to skip homework, but you might disagree because you know homework helps you learn. Recognizing your own point of view helps you think more deeply about what you read.',
          keyVocabulary: ['reader', 'experiences', 'opinions', 'disagree'],
        },
        {
          index: 3,
          title: 'Comparing Points of View',
          text: 'Good readers compare their own point of view with those of the characters and narrator. Ask yourself: Do I agree with this character? Would I make the same choice? Why or why not? When you compare, you understand the story better. You might realize the author wants you to disagree with a character to learn a lesson. Comparing points of view is an important reading skill that makes you a stronger thinker.',
          keyVocabulary: ['compare', 'agree', 'choice', 'stronger thinker'],
        },
      ],
      practice: [
        {
          index: 0,
          question: 'A narrator tells the story using the words "I" and "my." What point of view is this?',
          type: 'multiple-choice',
          options: ['First person', 'Second person', 'Third person', 'No point of view'],
          correctAnswer: 'First person',
          hint: '"I" and "my" mean the narrator is a character in the story.',
          explanation: 'When the narrator uses "I" and "my," the story is told in first person. The narrator is part of the story.',
          standardCode: '3.RL.6',
        },
        {
          index: 1,
          question: 'In a story, a character named Jake thinks lying is no big deal. You think lying is wrong. How are your points of view different?',
          type: 'short-answer',
          correctAnswer: 'Jake thinks lying is acceptable, but I think lying is wrong.',
          hint: 'Compare what Jake believes with what you believe about lying.',
          explanation: 'Your point of view (lying is wrong) is different from Jake\'s point of view (lying is no big deal). Readers can disagree with characters.',
          standardCode: '3.RL.6',
        },
        {
          index: 2,
          question: 'How can you figure out a character\'s point of view?',
          type: 'multiple-choice',
          options: [
            'Look at the cover of the book',
            'Look at what the character says, thinks, and does',
            'Count the pages in the chapter',
            'Read only the last sentence',
          ],
          correctAnswer: 'Look at what the character says, thinks, and does',
          hint: 'A character\'s words, thoughts, and actions reveal their point of view.',
          explanation: 'You discover a character\'s point of view by paying attention to their words, thoughts, and actions throughout the story.',
          standardCode: '3.RL.6',
        },
        {
          index: 3,
          question: 'A narrator describes a rainy day as gloomy and sad. You love rainy days. Whose point of view is shown in the story?',
          type: 'multiple-choice',
          options: [
            'Your point of view',
            'The narrator\'s point of view',
            'The author\'s biography',
            'No one\'s point of view',
          ],
          correctAnswer: 'The narrator\'s point of view',
          hint: 'The words "gloomy and sad" reflect how the narrator sees the rain.',
          explanation: 'The story shows the narrator\'s point of view about rain. Your point of view as a reader may be different.',
          standardCode: '3.RL.6',
        },
        {
          index: 4,
          question: 'Why is it important to compare your point of view with a character\'s point of view?',
          type: 'multiple-choice',
          options: [
            'It makes the book longer.',
            'It helps you understand the story more deeply.',
            'It changes the story ending.',
            'It is not important.',
          ],
          correctAnswer: 'It helps you understand the story more deeply.',
          hint: 'Comparing helps you think about the story in a deeper way.',
          explanation: 'Comparing your point of view with a character\'s helps you think critically about the story and understand its message better.',
          standardCode: '3.RL.6',
        },
      ],
      assessment: {
        questions: [
          {
            question: 'A story uses "he" and "she" to describe the characters. What point of view is the narrator using?',
            type: 'multiple-choice',
            options: ['First person', 'Third person', 'Second person'],
            correctAnswer: 'Third person',
            standardCode: '3.RL.6',
          },
          {
            question: 'In a story, a girl thinks school is boring. You think school is fun. Describe how your point of view is different from the character\'s.',
            type: 'short-answer',
            correctAnswer: 'The character thinks school is boring, but I think school is fun. We have different points of view about school.',
            standardCode: '3.RL.6',
          },
          {
            question: 'What is a narrator?',
            type: 'multiple-choice',
            options: [
              'The person who illustrated the book',
              'The person telling the story',
              'The person who bought the book',
              'The main character\'s best friend',
            ],
            correctAnswer: 'The person telling the story',
            standardCode: '3.RL.6',
          },
        ],
      },
    },
  },
  {
    slug: 'grade3-ela-figurative-language-intro',
    title: 'Literal and Non-Literal Language',
    description: 'Determine the meaning of literal and non-literal words and phrases in stories',
    subject: 'ela',
    grade: 3,
    gradeBand: 'k5',
    topicCluster: 'Reading Literature',
    standardCodes: ['3.RL.4'],
    content: {
      intro: {
        title: 'Literal and Non-Literal Language',
        text: 'Sometimes words mean exactly what they say, and sometimes they mean something completely different! When someone says "it is raining cats and dogs," no animals are actually falling from the sky. Today we will learn to tell the difference between literal language and non-literal (figurative) language.',
      },
      segments: [
        {
          index: 0,
          title: 'What Is Literal Language?',
          text: 'Literal language means the words mean exactly what they say. If someone says "the cat sat on the mat," there really is a cat sitting on a mat. Literal language is straightforward. Most of the sentences you read in informational texts use literal language. When you read directions, recipes, or science books, the words mean exactly what they say. Understanding literal language is the first step to understanding all language.',
          keyVocabulary: ['literal', 'straightforward', 'exact meaning'],
        },
        {
          index: 1,
          title: 'What Is Non-Literal Language?',
          text: 'Non-literal language, also called figurative language, uses words in creative ways. The words do not mean exactly what they say. Instead, they paint a picture or create a feeling. When someone says "I am so hungry I could eat a horse," they do not really mean they would eat a horse. They mean they are very, very hungry. Authors use non-literal language to make their writing more interesting, fun, and expressive.',
          keyVocabulary: ['non-literal', 'figurative language', 'creative', 'expressive'],
          example: '"Her smile was as bright as the sun" does not mean her face glows. It means she had a very big, happy smile.',
        },
        {
          index: 2,
          title: 'Common Types of Figurative Language',
          text: 'There are several types of figurative language you will see in stories. A simile compares two things using "like" or "as," such as "fast as a cheetah." A metaphor says something is something else, like "the classroom was a zoo." An idiom is a common phrase with a special meaning, like "break a leg" means "good luck." Knowing these types helps you spot non-literal language when you read.',
          keyVocabulary: ['simile', 'metaphor', 'idiom', 'compare'],
        },
        {
          index: 3,
          title: 'Figuring Out What Non-Literal Language Means',
          text: 'When you find non-literal language in a story, use context clues to figure out what it means. Read the sentences around it. Think about what is happening in the story. Ask yourself: Does this phrase make sense if I take it literally? If not, what could it really mean? For example, if a story says "Maria had butterflies in her stomach before the big test," the context tells you she felt nervous, not that actual butterflies were inside her.',
          keyVocabulary: ['context clues', 'surrounding sentences', 'interpret'],
        },
      ],
      practice: [
        {
          index: 0,
          question: 'Is the sentence "The dog ran across the yard" literal or non-literal language?',
          type: 'multiple-choice',
          options: ['Literal', 'Non-literal'],
          correctAnswer: 'Literal',
          hint: 'Does the sentence mean exactly what it says?',
          explanation: 'This is literal language. A dog really did run across the yard. The words mean exactly what they say.',
          standardCode: '3.RL.4',
        },
        {
          index: 1,
          question: 'What does the phrase "it is raining cats and dogs" really mean?',
          type: 'multiple-choice',
          options: [
            'Animals are falling from the sky.',
            'It is raining very hard.',
            'Cats and dogs are playing outside.',
            'The weather is nice.',
          ],
          correctAnswer: 'It is raining very hard.',
          hint: 'This is an idiom. Think about what kind of weather it describes.',
          explanation: '"Raining cats and dogs" is an idiom that means it is raining very heavily. No animals are actually falling!',
          standardCode: '3.RL.4',
        },
        {
          index: 2,
          question: '"She ran like the wind." What type of figurative language is this?',
          type: 'multiple-choice',
          options: ['Simile', 'Metaphor', 'Idiom', 'Literal language'],
          correctAnswer: 'Simile',
          hint: 'Look for the word "like" or "as" comparing two things.',
          explanation: 'This is a simile because it uses the word "like" to compare how she ran to the wind. It means she ran very fast.',
          standardCode: '3.RL.4',
        },
        {
          index: 3,
          question: 'A story says "the test was a piece of cake." What does this mean?',
          type: 'short-answer',
          correctAnswer: 'The test was very easy.',
          hint: 'Think about whether the test was actually a piece of cake, or if the phrase means something else.',
          explanation: '"A piece of cake" is an idiom that means something is very easy. The test was not actually made of cake.',
          standardCode: '3.RL.4',
        },
        {
          index: 4,
          question: 'How can you figure out the meaning of non-literal language in a story?',
          type: 'multiple-choice',
          options: [
            'Skip the phrase and keep reading',
            'Use context clues from the surrounding sentences',
            'Look at the pictures only',
            'Guess without reading anything else',
          ],
          correctAnswer: 'Use context clues from the surrounding sentences',
          hint: 'The sentences before and after can help you understand the meaning.',
          explanation: 'Context clues from the surrounding sentences help you figure out what non-literal language really means.',
          standardCode: '3.RL.4',
        },
      ],
      assessment: {
        questions: [
          {
            question: '"The classroom was a zoo today." Is this literal or non-literal language, and what does it mean?',
            type: 'short-answer',
            correctAnswer: 'Non-literal. It means the classroom was very noisy and wild, not that it was an actual zoo.',
            standardCode: '3.RL.4',
          },
          {
            question: 'Which sentence uses a simile?',
            type: 'multiple-choice',
            options: [
              'The boy ate his lunch.',
              'She was as quiet as a mouse.',
              'The door slammed shut.',
              'They played at the park.',
            ],
            correctAnswer: 'She was as quiet as a mouse.',
            standardCode: '3.RL.4',
          },
          {
            question: 'What is the difference between literal and non-literal language?',
            type: 'multiple-choice',
            options: [
              'Literal language uses long words; non-literal uses short words.',
              'Literal language means exactly what it says; non-literal language has a different meaning from the actual words.',
              'They mean the same thing.',
              'Non-literal language is only used in math.',
            ],
            correctAnswer: 'Literal language means exactly what it says; non-literal language has a different meaning from the actual words.',
            standardCode: '3.RL.4',
          },
        ],
      },
    },
  },
  {
    slug: 'grade3-ela-text-structure',
    title: 'Text Structure and Connections',
    description: 'Describe the logical connection between sentences and paragraphs in informational text',
    subject: 'ela',
    grade: 3,
    gradeBand: 'k5',
    topicCluster: 'Reading Informational',
    standardCodes: ['3.RI.8'],
    content: {
      intro: {
        title: 'Text Structure and Connections',
        text: 'When you read a science book or a news article, the sentences and paragraphs are connected in special ways. Authors organize their ideas so that readers can follow along and understand the information. Today we will learn how to describe the logical connections between sentences and paragraphs in informational texts.',
      },
      segments: [
        {
          index: 0,
          title: 'What Is Text Structure?',
          text: 'Text structure is the way an author organizes information. Some texts describe a topic. Some texts explain cause and effect, meaning why something happens and what happens because of it. Some texts compare two things to show how they are alike or different. Some texts present a problem and a solution. Knowing the structure helps you understand and remember what you read because you can see how the ideas fit together.',
          keyVocabulary: ['text structure', 'organize', 'cause and effect', 'compare'],
        },
        {
          index: 1,
          title: 'Connections Between Sentences',
          text: 'Sentences in a paragraph work together. One sentence might state a fact, and the next sentence might give an example or explain why. Authors use signal words to show these connections. Words like "because," "so," and "as a result" show cause and effect. Words like "for example" and "such as" introduce examples. Words like "however" and "but" show a contrast. Spotting these signal words helps you see how ideas connect.',
          keyVocabulary: ['signal words', 'because', 'for example', 'however', 'contrast'],
          example: '"Bears hibernate in winter because food is hard to find." The word "because" connects the effect (hibernating) with the cause (no food).',
        },
        {
          index: 2,
          title: 'Connections Between Paragraphs',
          text: 'Paragraphs also connect to each other in logical ways. One paragraph might introduce a topic, and the next paragraph might give more details. Sometimes each paragraph covers a different subtopic. For example, an article about weather might have one paragraph about rain, one about snow, and one about sunshine. The paragraphs work together to explain the bigger topic. Pay attention to headings and topic sentences to see how paragraphs are connected.',
          keyVocabulary: ['subtopic', 'headings', 'topic sentence', 'details'],
        },
        {
          index: 3,
          title: 'Describing Connections in Your Own Words',
          text: 'Strong readers can describe how ideas in a text are connected. You can say things like "The author gives the cause first and then the effect" or "This paragraph compares two animals." Practice using sentences like: "The first paragraph introduces the topic, and the second paragraph gives examples." When you describe these connections, you show that you understand not just what the text says, but how it is organized.',
          keyVocabulary: ['describe', 'connections', 'organized', 'logical'],
        },
      ],
      practice: [
        {
          index: 0,
          question: '"The plants died because they did not get enough water." What type of connection does the word "because" show?',
          type: 'multiple-choice',
          options: ['Compare and contrast', 'Cause and effect', 'Problem and solution', 'Time order'],
          correctAnswer: 'Cause and effect',
          hint: '"Because" tells you why something happened.',
          explanation: 'The word "because" signals a cause and effect connection. The cause is not enough water, and the effect is that the plants died.',
          standardCode: '3.RI.8',
        },
        {
          index: 1,
          question: 'Which signal word shows a contrast between two ideas?',
          type: 'multiple-choice',
          options: ['Because', 'However', 'For example', 'Also'],
          correctAnswer: 'However',
          hint: 'A contrast means the ideas are different from each other.',
          explanation: '"However" signals that the next idea is different from or contrasts with the previous idea.',
          standardCode: '3.RI.8',
        },
        {
          index: 2,
          question: 'An article has three paragraphs: one about lions, one about tigers, and one about bears. How are the paragraphs connected?',
          type: 'short-answer',
          correctAnswer: 'Each paragraph covers a different subtopic under the bigger topic of wild animals.',
          hint: 'Think about what all three paragraphs have in common and how they are organized.',
          explanation: 'The paragraphs are connected because they each describe a different type of wild animal. Together they cover the bigger topic.',
          standardCode: '3.RI.8',
        },
        {
          index: 3,
          question: '"Many students were slipping on the icy sidewalk. The school put down salt to melt the ice." What text structure is this?',
          type: 'multiple-choice',
          options: ['Cause and effect', 'Compare and contrast', 'Problem and solution', 'Description'],
          correctAnswer: 'Problem and solution',
          hint: 'One sentence describes something going wrong, and the next describes what was done to fix it.',
          explanation: 'The problem is students slipping on ice. The solution is the school putting down salt. This is a problem-and-solution structure.',
          standardCode: '3.RI.8',
        },
        {
          index: 4,
          question: 'Why is it helpful to know the text structure when you read?',
          type: 'multiple-choice',
          options: [
            'It helps you read faster.',
            'It helps you understand and remember how ideas fit together.',
            'It makes the text shorter.',
            'It only matters for fiction stories.',
          ],
          correctAnswer: 'It helps you understand and remember how ideas fit together.',
          hint: 'Knowing how a text is organized helps your brain make sense of the information.',
          explanation: 'Knowing the text structure helps you see how ideas connect, which improves your understanding and memory of the information.',
          standardCode: '3.RI.8',
        },
      ],
      assessment: {
        questions: [
          {
            question: '"Frogs live in wet places such as ponds and swamps. However, toads can live in drier areas." What connection is shown between these sentences?',
            type: 'short-answer',
            correctAnswer: 'The sentences show a contrast between where frogs and toads live, signaled by the word "however."',
            standardCode: '3.RI.8',
          },
          {
            question: 'Which word signals that an example is coming next?',
            type: 'multiple-choice',
            options: ['Because', 'But', 'For example', 'Finally'],
            correctAnswer: 'For example',
            standardCode: '3.RI.8',
          },
          {
            question: 'What does "text structure" mean?',
            type: 'multiple-choice',
            options: [
              'The font and size of the words',
              'The way an author organizes information in a text',
              'The number of pages in a book',
              'The pictures in a text',
            ],
            correctAnswer: 'The way an author organizes information in a text',
            standardCode: '3.RI.8',
          },
        ],
      },
    },
  },
  {
    slug: 'grade3-ela-multiple-sources',
    title: 'Comparing Two Texts on the Same Topic',
    description: 'Compare and contrast the most important points in two texts on the same topic',
    subject: 'ela',
    grade: 3,
    gradeBand: 'k5',
    topicCluster: 'Reading Informational',
    standardCodes: ['3.RI.9'],
    content: {
      intro: {
        title: 'Comparing Two Texts on the Same Topic',
        text: 'Have you ever read two books about the same thing and noticed they were a little different? When we read two texts on the same topic, we can compare them to learn more. Comparing means finding what is the same and what is different. Today we will practice comparing the important points in two texts.',
      },
      segments: [
        {
          index: 0,
          title: 'Why Compare Two Texts?',
          text: 'Different authors may write about the same topic but include different information. One author might focus on one set of facts, while another author shares different details. By reading and comparing both texts, you get a fuller picture of the topic. Comparing also helps you notice which facts both authors agree on, which makes those facts especially important and reliable.',
          keyVocabulary: ['compare', 'different information', 'reliable', 'fuller picture'],
        },
        {
          index: 1,
          title: 'Finding the Most Important Points',
          text: 'Before you can compare two texts, you need to identify the most important points in each one. The most important points are the key facts and main ideas that the author wants you to know. Look at the topic sentences of paragraphs, headings, and repeated ideas. Take notes on the main ideas from each text. Writing a short list of key points for each text makes it easier to compare them side by side.',
          keyVocabulary: ['key facts', 'main ideas', 'topic sentences', 'notes'],
        },
        {
          index: 2,
          title: 'Finding Similarities and Differences',
          text: 'Once you have the key points from each text, look for similarities and differences. Similarities are things both texts say that are the same. Differences are things that appear in one text but not the other, or things the two texts say differently. A Venn diagram is a helpful tool. Draw two overlapping circles. Put what is unique to Text 1 on the left, what is unique to Text 2 on the right, and what they share in the middle.',
          keyVocabulary: ['similarities', 'differences', 'Venn diagram', 'overlapping'],
          example: 'Text 1 says dolphins are mammals. Text 2 also says dolphins are mammals. This goes in the middle of the Venn diagram because both texts agree.',
        },
        {
          index: 3,
          title: 'Writing About Your Comparison',
          text: 'After comparing, you can write about what you found. Use phrases like "Both texts say..." for similarities and "Text 1 says... but Text 2 says..." for differences. A good comparison statement might be: "Both articles explain that recycling reduces trash. However, the first article focuses on recycling at home, while the second focuses on recycling at school." Sharing your comparison shows that you have read carefully and thought deeply.',
          keyVocabulary: ['both', 'however', 'comparison statement', 'focuses on'],
        },
      ],
      practice: [
        {
          index: 0,
          question: 'Why is it useful to read two texts about the same topic?',
          type: 'multiple-choice',
          options: [
            'It wastes time.',
            'You get a fuller picture because each author may share different details.',
            'Both texts always say the exact same thing.',
            'One text is always wrong.',
          ],
          correctAnswer: 'You get a fuller picture because each author may share different details.',
          hint: 'Different authors may include different facts about the same topic.',
          explanation: 'Reading two texts gives you more information and a fuller picture of the topic, because each author may share different details.',
          standardCode: '3.RI.9',
        },
        {
          index: 1,
          question: 'What tool can help you organize similarities and differences between two texts?',
          type: 'multiple-choice',
          options: ['A ruler', 'A Venn diagram', 'A dictionary', 'A calculator'],
          correctAnswer: 'A Venn diagram',
          hint: 'It has two overlapping circles.',
          explanation: 'A Venn diagram with two overlapping circles helps you organize what is the same and what is different between two texts.',
          standardCode: '3.RI.9',
        },
        {
          index: 2,
          question: 'Text 1 says penguins eat fish. Text 2 says penguins eat fish and squid. What is the similarity? What is the difference?',
          type: 'short-answer',
          correctAnswer: 'Both texts say penguins eat fish. The difference is that Text 2 also mentions squid.',
          hint: 'Look for what both texts mention, and what only one text mentions.',
          explanation: 'The similarity is that both texts say penguins eat fish. The difference is that Text 2 adds squid as another food source.',
          standardCode: '3.RI.9',
        },
        {
          index: 3,
          question: 'Where do you put information that both texts share on a Venn diagram?',
          type: 'multiple-choice',
          options: [
            'On the left circle only',
            'On the right circle only',
            'In the overlapping middle section',
            'Outside both circles',
          ],
          correctAnswer: 'In the overlapping middle section',
          hint: 'The overlapping part is where the two circles meet.',
          explanation: 'Information shared by both texts goes in the overlapping middle section of the Venn diagram.',
          standardCode: '3.RI.9',
        },
        {
          index: 4,
          question: 'Which phrase is best for writing about a difference between two texts?',
          type: 'multiple-choice',
          options: [
            'Both texts say...',
            'Text 1 says... but Text 2 says...',
            'In conclusion...',
            'Once upon a time...',
          ],
          correctAnswer: 'Text 1 says... but Text 2 says...',
          hint: 'You need a phrase that shows the two texts are different.',
          explanation: '"Text 1 says... but Text 2 says..." clearly shows a difference between the two texts.',
          standardCode: '3.RI.9',
        },
      ],
      assessment: {
        questions: [
          {
            question: 'Text 1 says bats sleep during the day. Text 2 says bats sleep during the day and hang upside down. Describe one similarity and one difference.',
            type: 'short-answer',
            correctAnswer: 'Similarity: both say bats sleep during the day. Difference: only Text 2 mentions they hang upside down.',
            standardCode: '3.RI.9',
          },
          {
            question: 'When both texts agree on a fact, what does that tell you?',
            type: 'multiple-choice',
            options: [
              'The fact is probably not true.',
              'The fact is especially important and reliable.',
              'You should ignore it.',
              'Only one text is correct.',
            ],
            correctAnswer: 'The fact is especially important and reliable.',
            standardCode: '3.RI.9',
          },
          {
            question: 'Before comparing two texts, what should you do first?',
            type: 'multiple-choice',
            options: [
              'Write a conclusion',
              'Identify the most important points in each text',
              'Pick your favorite text',
              'Count the words in each text',
            ],
            correctAnswer: 'Identify the most important points in each text',
            standardCode: '3.RI.9',
          },
        ],
      },
    },
  },
  {
    slug: 'grade3-ela-opinion-research-writing',
    title: 'Opinion and Research Writing',
    description: 'Write opinion pieces with a claim and supporting reasons, and conduct short research projects',
    subject: 'ela',
    grade: 3,
    gradeBand: 'k5',
    topicCluster: 'Writing',
    standardCodes: ['3.W.1', '3.W.7'],
    content: {
      intro: {
        title: 'Opinion and Research Writing',
        text: 'Everyone has opinions — things you believe or feel strongly about. But to convince others, you need to support your opinion with reasons and facts. Today we will learn to write opinion pieces with a clear claim and strong reasons. We will also learn how to do short research to find information that supports our writing.',
      },
      segments: [
        {
          index: 0,
          title: 'What Is an Opinion Piece?',
          text: 'An opinion piece is a type of writing where you share what you think about a topic and try to convince the reader to agree with you. Every opinion piece starts with a claim, which is a clear statement of your opinion. For example: "I believe recess should be longer." After your claim, you give reasons that explain why you think this way. A strong opinion piece has at least two or three reasons. Each reason should make sense and connect back to your claim.',
          keyVocabulary: ['opinion', 'claim', 'reasons', 'convince'],
        },
        {
          index: 1,
          title: 'Supporting Your Opinion with Reasons',
          text: 'Good reasons make your opinion stronger. Reasons answer the question "Why do I think this?" They should be based on facts, examples, or personal experience. For the claim "Recess should be longer," your reasons might be: kids need exercise to stay healthy, breaks help students focus better in class, and playing together builds friendships. Use linking words like "because," "for instance," and "another reason" to connect your reasons to your claim clearly.',
          keyVocabulary: ['supporting reasons', 'facts', 'linking words', 'for instance'],
          example: '"I believe dogs are the best pets. First, dogs are loyal and love their owners. Second, dogs encourage families to go outside and exercise."',
        },
        {
          index: 2,
          title: 'Organizing Your Opinion Writing',
          text: 'A well-organized opinion piece has three parts. The introduction states your claim and gets the reader interested. The body paragraphs present your reasons, with each paragraph focusing on one reason and giving details to support it. The conclusion restates your claim and wraps up your writing. You can end with a strong closing statement like "For all these reasons, I believe..." This organization makes your writing clear and easy to follow.',
          keyVocabulary: ['introduction', 'body paragraphs', 'conclusion', 'closing statement'],
        },
        {
          index: 3,
          title: 'Short Research Projects',
          text: 'Sometimes you need to find facts to support your opinion. A short research project helps you gather information. Start by choosing a question you want to answer. Then look for answers in books, articles, or trusted websites. Take notes on the important facts you find. Use those facts in your writing to make your opinion stronger. Always remember where you found your information so you can tell your reader. Research turns a regular opinion into a well-supported argument.',
          keyVocabulary: ['research', 'gather information', 'sources', 'notes', 'argument'],
        },
      ],
      practice: [
        {
          index: 0,
          question: 'What is a claim in an opinion piece?',
          type: 'multiple-choice',
          options: [
            'A question about the topic',
            'A clear statement of your opinion',
            'A fact from a textbook',
            'The title of your essay',
          ],
          correctAnswer: 'A clear statement of your opinion',
          hint: 'A claim tells the reader exactly what you believe.',
          explanation: 'A claim is a clear statement of your opinion. It tells the reader what you think and sets up the rest of your writing.',
          standardCode: '3.W.1',
        },
        {
          index: 1,
          question: 'Which is a strong reason to support the claim "Students should read every day"?',
          type: 'multiple-choice',
          options: [
            'Books have pages.',
            'Reading every day improves vocabulary and makes you a better writer.',
            'My friend does not like reading.',
            'The library is a big building.',
          ],
          correctAnswer: 'Reading every day improves vocabulary and makes you a better writer.',
          hint: 'A strong reason explains why the claim is true with a clear benefit.',
          explanation: 'This reason directly supports the claim by explaining a clear benefit of reading every day.',
          standardCode: '3.W.1',
        },
        {
          index: 2,
          question: 'What are the three parts of a well-organized opinion piece?',
          type: 'short-answer',
          correctAnswer: 'Introduction, body paragraphs, and conclusion.',
          hint: 'Think about the beginning, middle, and end of the writing.',
          explanation: 'A well-organized opinion piece has an introduction (states the claim), body paragraphs (give reasons), and a conclusion (wraps up).',
          standardCode: '3.W.1',
        },
        {
          index: 3,
          question: 'When doing a short research project, what should you do first?',
          type: 'multiple-choice',
          options: [
            'Write the conclusion',
            'Choose a question you want to answer',
            'Decorate your paper',
            'Pick the longest book you can find',
          ],
          correctAnswer: 'Choose a question you want to answer',
          hint: 'Research starts with knowing what you are looking for.',
          explanation: 'A short research project begins with choosing a clear question. Then you look for information to answer that question.',
          standardCode: '3.W.7',
        },
        {
          index: 4,
          question: 'Which linking word helps connect a reason to a claim?',
          type: 'multiple-choice',
          options: ['Then', 'Because', 'Once upon a time', 'The end'],
          correctAnswer: 'Because',
          hint: 'This word explains why something is true.',
          explanation: '"Because" is a linking word that connects your reason to your claim by explaining why you hold your opinion.',
          standardCode: '3.W.1',
        },
      ],
      assessment: {
        questions: [
          {
            question: 'Write a claim about a topic you care about and give one reason to support it.',
            type: 'short-answer',
            correctAnswer: 'Example: I believe schools should have gardens because growing plants teaches students about science and healthy eating.',
            standardCode: '3.W.1',
          },
          {
            question: 'Why is research helpful when writing an opinion piece?',
            type: 'multiple-choice',
            options: [
              'It makes your paper longer.',
              'It gives you facts to support your opinion and make it stronger.',
              'It replaces your opinion with someone else\'s.',
              'It is not helpful.',
            ],
            correctAnswer: 'It gives you facts to support your opinion and make it stronger.',
            standardCode: '3.W.7',
          },
          {
            question: 'Which is the best way to end an opinion piece?',
            type: 'multiple-choice',
            options: [
              'Stop writing in the middle of a sentence.',
              'Restate your claim and give a strong closing statement.',
              'Start a new topic.',
              'Ask the reader an unrelated question.',
            ],
            correctAnswer: 'Restate your claim and give a strong closing statement.',
            standardCode: '3.W.1',
          },
        ],
      },
    },
  },
  {
    slug: 'grade3-ela-context-clues-word-meaning',
    title: 'Context Clues for Word Meaning',
    description: 'Use sentence-level context as a clue to the meaning of a word or phrase',
    subject: 'ela',
    grade: 3,
    gradeBand: 'k5',
    topicCluster: 'Language',
    standardCodes: ['3.L.4a'],
    content: {
      intro: {
        title: 'Context Clues for Word Meaning',
        text: 'When you come across a word you do not know, you do not always need a dictionary. The other words in the sentence can give you clues about what the unknown word means. These clues are called context clues. Today we will learn how to use the words and sentences around an unfamiliar word to figure out its meaning.',
      },
      segments: [
        {
          index: 0,
          title: 'What Are Context Clues?',
          text: 'Context clues are hints found in the words and sentences surrounding an unknown word. Authors often include information nearby that helps you figure out what a word means without looking it up. The context is everything around the word — the sentence it is in, the sentences before and after it, and the overall topic. Learning to spot context clues is one of the most powerful reading skills you can develop.',
          keyVocabulary: ['context clues', 'surrounding words', 'unfamiliar word', 'hints'],
        },
        {
          index: 1,
          title: 'Types of Context Clues',
          text: 'There are several types of context clues. A definition clue gives the meaning right in the sentence, often after the words "which means" or "that is." An example clue gives examples of the word, often after "such as" or "for example." A synonym clue uses a word with a similar meaning nearby. An antonym clue uses an opposite word, often with "but" or "unlike." Knowing these types helps you search for clues more effectively.',
          keyVocabulary: ['definition clue', 'example clue', 'synonym', 'antonym'],
          example: '"The arid, or very dry, desert gets little rain." The words "very dry" are a definition clue for "arid."',
        },
        {
          index: 2,
          title: 'Steps for Using Context Clues',
          text: 'When you find a word you do not know, follow these steps. First, reread the sentence and look for clues like definitions, examples, synonyms, or antonyms. Second, read the sentences before and after for more information. Third, use the clues to make a guess about the meaning. Fourth, try your guess in place of the unknown word to see if the sentence still makes sense. If it does, you have probably found the right meaning.',
          keyVocabulary: ['reread', 'guess', 'substitute', 'makes sense'],
        },
        {
          index: 3,
          title: 'Practicing with Context Clues',
          text: 'The more you practice using context clues, the better you will get. When reading, keep a list of new words you figure out from context. Write down the word, the clue that helped you, and the meaning you discovered. Over time, these words become part of your vocabulary. Strong readers use context clues automatically, and with practice, you will too. This skill helps you in every subject, not just reading.',
          keyVocabulary: ['vocabulary', 'practice', 'automatic', 'every subject'],
        },
      ],
      practice: [
        {
          index: 0,
          question: '"The enormous elephant towered over the tiny mouse." What does "enormous" most likely mean?',
          type: 'multiple-choice',
          options: ['Very small', 'Very large', 'Very fast', 'Very quiet'],
          correctAnswer: 'Very large',
          hint: 'The elephant towered over the tiny mouse. What kind of size would make it tower?',
          explanation: 'The clue "towered over the tiny mouse" tells you the elephant is very big. "Enormous" means very large.',
          standardCode: '3.L.4a',
        },
        {
          index: 1,
          question: '"The child was famished after skipping lunch, so she ate three sandwiches." What does "famished" mean?',
          type: 'multiple-choice',
          options: ['Happy', 'Tired', 'Very hungry', 'Confused'],
          correctAnswer: 'Very hungry',
          hint: 'She skipped lunch and ate three sandwiches. How was she feeling?',
          explanation: 'Skipping lunch and eating three sandwiches are clues that "famished" means very hungry.',
          standardCode: '3.L.4a',
        },
        {
          index: 2,
          question: 'What is a synonym clue?',
          type: 'multiple-choice',
          options: [
            'A clue that gives the opposite meaning',
            'A clue that uses a word with a similar meaning nearby',
            'A clue that lists examples',
            'A clue found in the dictionary',
          ],
          correctAnswer: 'A clue that uses a word with a similar meaning nearby',
          hint: 'Synonyms are words that mean the same or nearly the same thing.',
          explanation: 'A synonym clue places a word with a similar meaning near the unknown word, helping you figure out what it means.',
          standardCode: '3.L.4a',
        },
        {
          index: 3,
          question: '"Unlike her timid sister, Rosa was bold and always spoke up in class." What does "timid" most likely mean?',
          type: 'short-answer',
          correctAnswer: 'Shy or not bold.',
          hint: '"Unlike" signals an opposite. Rosa is bold. What is the opposite?',
          explanation: 'The word "unlike" tells you "timid" is the opposite of "bold." Timid means shy or fearful.',
          standardCode: '3.L.4a',
        },
        {
          index: 4,
          question: 'What should you do after you guess the meaning of an unknown word using context clues?',
          type: 'multiple-choice',
          options: [
            'Move on without checking',
            'Substitute your guess into the sentence to see if it makes sense',
            'Erase the word from the page',
            'Ask someone else to read the sentence for you',
          ],
          correctAnswer: 'Substitute your guess into the sentence to see if it makes sense',
          hint: 'After guessing, you should test your guess.',
          explanation: 'After guessing, substitute your meaning into the sentence. If the sentence still makes sense, your guess is likely correct.',
          standardCode: '3.L.4a',
        },
      ],
      assessment: {
        questions: [
          {
            question: '"The frigid wind made everyone shiver and pull their coats tighter." What does "frigid" mean? What context clue helped you?',
            type: 'short-answer',
            correctAnswer: 'Frigid means very cold. The clues "shiver" and "pull their coats tighter" show that the wind was cold.',
            standardCode: '3.L.4a',
          },
          {
            question: 'Which type of context clue gives the meaning of a word right in the sentence?',
            type: 'multiple-choice',
            options: ['Antonym clue', 'Example clue', 'Definition clue', 'Picture clue'],
            correctAnswer: 'Definition clue',
            standardCode: '3.L.4a',
          },
          {
            question: '"The benevolent, or kind and generous, teacher helped every student." What does "benevolent" mean?',
            type: 'multiple-choice',
            options: ['Strict', 'Kind and generous', 'Funny', 'Quiet'],
            correctAnswer: 'Kind and generous',
            standardCode: '3.L.4a',
          },
        ],
      },
    },
  },
  {
    slug: 'grade3-ela-root-words-affixes',
    title: 'Root Words and Affixes',
    description: 'Identify and know the meaning of common prefixes and suffixes',
    subject: 'ela',
    grade: 3,
    gradeBand: 'k5',
    topicCluster: 'Reading Foundational Skills',
    standardCodes: ['3.RF.3a'],
    content: {
      intro: {
        title: 'Root Words and Affixes',
        text: 'Did you know that many words are made up of smaller parts? A root word is the main part of a word that carries its core meaning. Prefixes and suffixes are word parts added to the beginning or end of a root word to change its meaning. Today we will learn how to break words apart and use prefixes and suffixes to figure out what words mean.',
      },
      segments: [
        {
          index: 0,
          title: 'What Is a Root Word?',
          text: 'A root word is the simplest form of a word, with no prefixes or suffixes added. It is the base that carries the main meaning. For example, "happy" is a root word. When you add "un-" to the beginning, you get "unhappy," which means not happy. When you add "-ness" to the end, you get "happiness," which means the state of being happy. If you can find the root word inside a longer word, you already have a clue about what the bigger word means.',
          keyVocabulary: ['root word', 'base word', 'main meaning', 'simplest form'],
        },
        {
          index: 1,
          title: 'Common Prefixes',
          text: 'A prefix is a word part added to the beginning of a root word. It changes the meaning of the word. The prefix "un-" means "not," so "unkind" means "not kind." The prefix "re-" means "again," so "rewrite" means "write again." The prefix "pre-" means "before," so "preview" means "view before." The prefix "dis-" means "not" or "opposite of," so "disagree" means "not agree." Knowing these common prefixes helps you decode many new words.',
          keyVocabulary: ['prefix', 'un-', 're-', 'pre-', 'dis-'],
          example: '"The teacher asked us to reread the story." "Re-" means "again," so "reread" means "read again."',
        },
        {
          index: 2,
          title: 'Common Suffixes',
          text: 'A suffix is a word part added to the end of a root word. The suffix "-ful" means "full of," so "hopeful" means "full of hope." The suffix "-less" means "without," so "careless" means "without care." The suffix "-er" can mean "a person who," so "teacher" means "a person who teaches." The suffix "-ly" changes a word to describe how something is done, so "quickly" means "in a quick way." Recognizing suffixes helps you understand and read longer words.',
          keyVocabulary: ['suffix', '-ful', '-less', '-er', '-ly'],
        },
        {
          index: 3,
          title: 'Breaking Words Apart',
          text: 'When you see a long word you do not know, try breaking it into parts. Look for a prefix at the beginning, a root word in the middle, and a suffix at the end. For example, "unhelpful" has the prefix "un-" (not), the root word "help," and the suffix "-ful" (full of). Put them together: "not full of help." This strategy works with many words and gives you the power to figure out meanings on your own. Practice with words you encounter in your reading every day.',
          keyVocabulary: ['break apart', 'decode', 'strategy', 'word parts'],
        },
      ],
      practice: [
        {
          index: 0,
          question: 'What is the root word in "replay"?',
          type: 'multiple-choice',
          options: ['Re', 'Play', 'Rep', 'Lay'],
          correctAnswer: 'Play',
          hint: 'Take away the prefix at the beginning. What word is left?',
          explanation: 'The prefix is "re-" and the root word is "play." "Replay" means to play again.',
          standardCode: '3.RF.3a',
        },
        {
          index: 1,
          question: 'What does the prefix "un-" mean?',
          type: 'multiple-choice',
          options: ['Again', 'Before', 'Not', 'After'],
          correctAnswer: 'Not',
          hint: 'Think about what "unhappy" means compared to "happy."',
          explanation: 'The prefix "un-" means "not." Unhappy means not happy. Unsafe means not safe.',
          standardCode: '3.RF.3a',
        },
        {
          index: 2,
          question: 'What does the suffix "-less" mean in the word "fearless"?',
          type: 'multiple-choice',
          options: ['Full of', 'Without', 'A person who', 'Again'],
          correctAnswer: 'Without',
          hint: 'A fearless person does not have fear.',
          explanation: 'The suffix "-less" means "without." Fearless means without fear.',
          standardCode: '3.RF.3a',
        },
        {
          index: 3,
          question: 'Break apart the word "unkindly" into its prefix, root word, and suffix.',
          type: 'short-answer',
          correctAnswer: 'Prefix: un- (not), root word: kind, suffix: -ly (in a way that).',
          hint: 'Look for a prefix at the start, a root in the middle, and a suffix at the end.',
          explanation: '"Unkindly" has the prefix "un-" (not), the root word "kind," and the suffix "-ly" (in a certain way). It means in a way that is not kind.',
          standardCode: '3.RF.3a',
        },
        {
          index: 4,
          question: 'Which word means "a person who teaches"?',
          type: 'multiple-choice',
          options: ['Teaching', 'Teacher', 'Teachable', 'Reteach'],
          correctAnswer: 'Teacher',
          hint: 'The suffix "-er" can mean "a person who."',
          explanation: '"Teacher" uses the suffix "-er," which means "a person who." A teacher is a person who teaches.',
          standardCode: '3.RF.3a',
        },
      ],
      assessment: {
        questions: [
          {
            question: 'What does the word "pretest" mean? Use your knowledge of prefixes to explain.',
            type: 'short-answer',
            correctAnswer: '"Pre-" means before and "test" is the root word. A pretest is a test given before the main lesson or test.',
            standardCode: '3.RF.3a',
          },
          {
            question: 'Which word means "full of joy"?',
            type: 'multiple-choice',
            options: ['Joyless', 'Joyful', 'Rejoy', 'Unjoy'],
            correctAnswer: 'Joyful',
            standardCode: '3.RF.3a',
          },
          {
            question: 'What does the prefix "dis-" mean in the word "dislike"?',
            type: 'multiple-choice',
            options: ['Again', 'Before', 'Not or opposite of', 'Full of'],
            correctAnswer: 'Not or opposite of',
            standardCode: '3.RF.3a',
          },
        ],
      },
    },
  },
  {
    slug: 'grade3-ela-writing-narratives-sequence',
    title: 'Writing Narratives with Sequence',
    description: 'Write narratives with a clear event sequence, details, and a sense of closure',
    subject: 'ela',
    grade: 3,
    gradeBand: 'k5',
    topicCluster: 'Writing',
    standardCodes: ['3.W.3'],
    content: {
      intro: {
        title: 'Writing Narratives with Sequence',
        text: 'A narrative is a story, and every good story has a beginning, a middle, and an end. When you write a narrative, you take your reader on a journey through events that happen in order. Today we will learn how to write narratives with a clear sequence of events, descriptive details, and a satisfying ending.',
      },
      segments: [
        {
          index: 0,
          title: 'What Is Narrative Writing?',
          text: 'Narrative writing tells a story. It can be a true story from your life or a made-up story from your imagination. Every narrative has characters (the people or animals in the story), a setting (where and when it takes place), and a plot (what happens). The plot is built from a series of events that happen in order. Good narrative writing makes the reader feel like they are right there in the story.',
          keyVocabulary: ['narrative', 'characters', 'setting', 'plot', 'events'],
        },
        {
          index: 1,
          title: 'Organizing Events in Order',
          text: 'A clear sequence means the events in your story are told in an order that makes sense. Most stories are told in time order — what happens first, next, then, and last. Transition words help your reader follow along. Use words like "first," "then," "next," "after that," and "finally" to show the order of events. Without these words, your story might feel jumbled and confusing. Plan your events before you write so you know what happens at each stage.',
          keyVocabulary: ['sequence', 'time order', 'transition words', 'first', 'then', 'finally'],
          example: '"First, I woke up early. Then, I packed my bag. Finally, I walked to school." The transition words show the order.',
        },
        {
          index: 2,
          title: 'Adding Descriptive Details',
          text: 'Details bring your story to life. Instead of writing "the dog ran," you might write "the big brown dog raced across the muddy yard, barking loudly." Details about what characters see, hear, feel, smell, and taste help the reader picture the story. You can also describe what characters are thinking and feeling. Details about thoughts and feelings help the reader care about what happens. Choose details that are important to the story and make key moments vivid.',
          keyVocabulary: ['descriptive details', 'senses', 'vivid', 'thoughts and feelings'],
        },
        {
          index: 3,
          title: 'Writing a Satisfying Ending',
          text: 'Every good narrative needs closure — a sense that the story is finished. Your ending should wrap up the events and show how the problem was solved or how the character feels at the end. A strong ending might show what the character learned, how they changed, or what happened as a result of the events. Avoid endings that stop suddenly or leave the reader confused. Your last sentences should give the reader a complete, satisfied feeling.',
          keyVocabulary: ['closure', 'ending', 'resolution', 'wrap up'],
        },
      ],
      practice: [
        {
          index: 0,
          question: 'Which transition word best shows what happened last in a story?',
          type: 'multiple-choice',
          options: ['First', 'Then', 'Finally', 'Once'],
          correctAnswer: 'Finally',
          hint: 'This word signals the end of a sequence of events.',
          explanation: '"Finally" signals the last event in a sequence. It tells the reader you are reaching the end of the story.',
          standardCode: '3.W.3',
        },
        {
          index: 1,
          question: 'Which sentence has better descriptive details?',
          type: 'multiple-choice',
          options: [
            'The boy ate food.',
            'The hungry boy gobbled up a warm slice of pepperoni pizza.',
            'He ate.',
            'Eating happened.',
          ],
          correctAnswer: 'The hungry boy gobbled up a warm slice of pepperoni pizza.',
          hint: 'Look for the sentence that paints a picture with specific details.',
          explanation: 'This sentence uses specific details (hungry, gobbled, warm, pepperoni pizza) that help the reader picture the scene.',
          standardCode: '3.W.3',
        },
        {
          index: 2,
          question: 'What are the three main parts of a narrative?',
          type: 'short-answer',
          correctAnswer: 'A beginning, a middle, and an end.',
          hint: 'Think about how stories are organized from start to finish.',
          explanation: 'Every narrative has a beginning (introduces characters and setting), a middle (events and problem), and an end (resolution and closure).',
          standardCode: '3.W.3',
        },
        {
          index: 3,
          question: 'Why is it important to write events in order?',
          type: 'multiple-choice',
          options: [
            'So the story is longer',
            'So the reader can follow what happens and the story makes sense',
            'So you can use bigger words',
            'It is not important',
          ],
          correctAnswer: 'So the reader can follow what happens and the story makes sense',
          hint: 'Think about what would happen if events were all mixed up.',
          explanation: 'Writing events in order helps the reader follow the story. A jumbled sequence would be confusing.',
          standardCode: '3.W.3',
        },
        {
          index: 4,
          question: 'What makes a satisfying ending to a narrative?',
          type: 'multiple-choice',
          options: [
            'Stopping in the middle of a sentence',
            'Introducing a brand new character',
            'Showing how the problem was solved or how the character feels',
            'Starting a new story',
          ],
          correctAnswer: 'Showing how the problem was solved or how the character feels',
          hint: 'The ending should wrap things up, not leave the reader confused.',
          explanation: 'A satisfying ending wraps up the story by showing how the problem was resolved or how the character changed or feels.',
          standardCode: '3.W.3',
        },
      ],
      assessment: {
        questions: [
          {
            question: 'Put these events in the correct order for a narrative: "She won the race. She trained every day. She signed up for the race." Write them in order using transition words.',
            type: 'short-answer',
            correctAnswer: 'First, she signed up for the race. Then, she trained every day. Finally, she won the race.',
            standardCode: '3.W.3',
          },
          {
            question: 'Which is NOT part of a narrative?',
            type: 'multiple-choice',
            options: ['Characters', 'Setting', 'A claim and reasons', 'A plot'],
            correctAnswer: 'A claim and reasons',
            standardCode: '3.W.3',
          },
          {
            question: 'Which detail best describes a setting?',
            type: 'multiple-choice',
            options: [
              'The boy felt happy.',
              'The sun set behind the tall mountains, painting the sky orange and pink.',
              'She ran fast.',
              'They went somewhere.',
            ],
            correctAnswer: 'The sun set behind the tall mountains, painting the sky orange and pink.',
            standardCode: '3.W.3',
          },
        ],
      },
    },
  },
  {
    slug: 'grade3-ela-literal-nonliteral-language',
    title: 'Distinguishing Literal from Nonliteral Language',
    description: 'Determine the meaning of words and phrases as they are used in a text, distinguishing literal from nonliteral language',
    subject: 'ela',
    grade: 3,
    gradeBand: 'k5',
    topicCluster: 'Reading Literature',
    standardCodes: ['3.RL.4'],
    content: {
      intro: {
        title: 'Distinguishing Literal from Nonliteral Language',
        text: 'Authors choose their words carefully. Sometimes they mean exactly what they say, and other times they use language in surprising ways to make their writing more colorful and exciting. Being able to tell the difference between literal and nonliteral language helps you become a stronger, more thoughtful reader. Today we will practice determining the meaning of words and phrases as they are used in stories and poems.',
      },
      segments: [
        {
          index: 0,
          title: 'Words and Phrases in Context',
          text: 'The same word can mean different things depending on how it is used. The word "bright" can describe a light that shines strongly, or it can describe a person who is very smart. The meaning depends on the context — the words and sentences around it. When you read, always look at how a word or phrase is being used in that particular sentence and paragraph. Context tells you whether the author means the literal or a nonliteral meaning.',
          keyVocabulary: ['context', 'meaning', 'literal', 'nonliteral', 'multiple meanings'],
        },
        {
          index: 1,
          title: 'Identifying Literal Language in Stories',
          text: 'Literal language in stories describes exactly what is happening. When an author writes "the girl walked to the store," the girl is actually walking to a store. Literal language is important because it tells you the basic facts of the story — what characters do, where they go, and what they say. Most of the sentences in a story use literal language to move the plot forward and give you a clear picture of the events.',
          keyVocabulary: ['literal meaning', 'facts', 'plot', 'basic meaning'],
        },
        {
          index: 2,
          title: 'Identifying Nonliteral Language in Stories',
          text: 'Nonliteral language is used to create images, feelings, or comparisons that go beyond the basic meaning of the words. In a story, an author might write "Maria\'s heart sank when she heard the news." Maria\'s heart did not actually sink — this phrase means she felt very sad or disappointed. Authors use nonliteral language to help readers feel emotions more deeply and to make descriptions more memorable and engaging.',
          keyVocabulary: ['nonliteral meaning', 'imagery', 'emotions', 'figurative expressions'],
          example: '"Time flew by during the fun party." Time cannot actually fly. This means the party went by very quickly because everyone was enjoying it.',
        },
        {
          index: 3,
          title: 'Determining Meaning in Poetry and Prose',
          text: 'Poems especially use nonliteral language. A poem might say "the trees danced in the wind." Trees cannot really dance, but this gives you a picture of branches swaying gracefully. To determine the meaning, ask yourself: Can this really happen? If not, what picture or feeling is the author trying to create? Think about how the phrase connects to the rest of the text. With practice, you will be able to enjoy and understand the creative ways authors use language.',
          keyVocabulary: ['poetry', 'prose', 'personification', 'creative language'],
        },
      ],
      practice: [
        {
          index: 0,
          question: '"Jake had a mountain of homework to do." Is this literal or nonliteral language?',
          type: 'multiple-choice',
          options: ['Literal', 'Nonliteral'],
          correctAnswer: 'Nonliteral',
          hint: 'Can homework really form a mountain?',
          explanation: 'This is nonliteral language. Jake does not have an actual mountain. It means he has a very large amount of homework.',
          standardCode: '3.RL.4',
        },
        {
          index: 1,
          question: '"The stars winked at us from the night sky." What does this nonliteral phrase mean?',
          type: 'multiple-choice',
          options: [
            'The stars have eyes and can wink.',
            'The stars were twinkling or flickering in the sky.',
            'Someone was winking at the stars.',
            'The sky was completely dark.',
          ],
          correctAnswer: 'The stars were twinkling or flickering in the sky.',
          hint: 'Stars cannot actually wink. What do they do that looks like winking?',
          explanation: 'Stars cannot wink. The author uses this nonliteral phrase to describe stars twinkling, which looks like winking.',
          standardCode: '3.RL.4',
        },
        {
          index: 2,
          question: '"She picked up the book and read the first page." Is this literal or nonliteral language?',
          type: 'multiple-choice',
          options: ['Literal', 'Nonliteral'],
          correctAnswer: 'Literal',
          hint: 'Can someone really pick up a book and read it?',
          explanation: 'This is literal language. The sentence describes exactly what happened — a girl picked up a book and read.',
          standardCode: '3.RL.4',
        },
        {
          index: 3,
          question: '"The wind howled through the empty streets." What does "howled" mean in this sentence?',
          type: 'short-answer',
          correctAnswer: 'The wind made a loud, moaning sound, like the sound a wolf makes.',
          hint: 'The wind is not an animal, so it cannot actually howl. What kind of sound does it describe?',
          explanation: '"Howled" is nonliteral. It means the wind was blowing very hard and making a loud, eerie sound, similar to a howling animal.',
          standardCode: '3.RL.4',
        },
        {
          index: 4,
          question: 'Why do authors use nonliteral language in stories?',
          type: 'multiple-choice',
          options: [
            'To confuse the reader',
            'To create vivid images and help readers feel emotions more deeply',
            'Because they cannot think of literal words',
            'To make the story shorter',
          ],
          correctAnswer: 'To create vivid images and help readers feel emotions more deeply',
          hint: 'Think about how nonliteral language makes you picture and feel things.',
          explanation: 'Authors use nonliteral language to paint pictures, stir emotions, and make their writing more interesting and memorable.',
          standardCode: '3.RL.4',
        },
      ],
      assessment: {
        questions: [
          {
            question: '"The news was music to her ears." Is this literal or nonliteral? What does it mean?',
            type: 'short-answer',
            correctAnswer: 'Nonliteral. It means the news made her very happy, not that she actually heard music.',
            standardCode: '3.RL.4',
          },
          {
            question: 'Which sentence uses nonliteral language?',
            type: 'multiple-choice',
            options: [
              'The cat slept on the couch.',
              'He ran to the bus stop.',
              'Her eyes were sparkling diamonds.',
              'The teacher read a book aloud.',
            ],
            correctAnswer: 'Her eyes were sparkling diamonds.',
            standardCode: '3.RL.4',
          },
          {
            question: 'What should you ask yourself to tell if language is nonliteral?',
            type: 'multiple-choice',
            options: [
              'Is this word long or short?',
              'Can this really happen, or is the author creating a picture or feeling?',
              'How many syllables does the word have?',
              'Is this word in the dictionary?',
            ],
            correctAnswer: 'Can this really happen, or is the author creating a picture or feeling?',
            standardCode: '3.RL.4',
          },
        ],
      },
    },
  },
  {
    slug: 'grade3-ela-comparing-contrasting-texts',
    title: 'Comparing and Contrasting Two Texts',
    description: 'Compare and contrast the most important points and key details in two texts on the same topic',
    subject: 'ela',
    grade: 3,
    gradeBand: 'k5',
    topicCluster: 'Reading Informational',
    standardCodes: ['3.RI.9'],
    content: {
      intro: {
        title: 'Comparing and Contrasting Two Texts',
        text: 'Reading one text teaches you a lot, but reading two texts on the same topic makes you even smarter. Different authors may choose different facts, organize information differently, or share different opinions about the same subject. Today we will sharpen our skills at comparing and contrasting the most important points and key details presented in two informational texts.',
      },
      segments: [
        {
          index: 0,
          title: 'Compare and Contrast as a Reading Strategy',
          text: 'Comparing means finding how two things are alike. Contrasting means finding how they are different. When you compare and contrast two texts, you look at the main ideas, key details, and the way each author presents information. This strategy helps you think critically. You begin to ask: Why did one author include this detail but the other did not? Which text gives me more information? Comparing and contrasting makes you an active, thinking reader.',
          keyVocabulary: ['compare', 'contrast', 'critically', 'active reader'],
        },
        {
          index: 1,
          title: 'Identifying Key Details in Each Text',
          text: 'Before you can compare, you need to understand each text on its own. Read the first text carefully and identify its most important points. What is the main idea? What key details support it? Then do the same for the second text. Take brief notes or make a list. Key details include facts, examples, and explanations that help you understand the topic. Focus on the information that matters most, not minor details.',
          keyVocabulary: ['key details', 'main idea', 'notes', 'facts'],
        },
        {
          index: 2,
          title: 'Using a Graphic Organizer',
          text: 'A T-chart or Venn diagram helps you organize your comparison. With a T-chart, write one text\'s key points on the left and the other text\'s on the right. With a Venn diagram, put unique details on each side and shared details in the middle. A graphic organizer makes it easier to see patterns. You might notice that both texts agree on some facts, one text covers a subtopic the other does not, or the authors use different examples to explain the same idea.',
          keyVocabulary: ['T-chart', 'Venn diagram', 'graphic organizer', 'patterns'],
          example: 'Text A about recycling focuses on home recycling. Text B focuses on school recycling. Both say recycling helps the environment — that goes in the middle of the Venn diagram.',
        },
        {
          index: 3,
          title: 'Writing a Comparison',
          text: 'After organizing your ideas, write sentences that describe the similarities and differences. Use comparison language: "Both texts explain..." for similarities and "Text A states... while Text B states..." for differences. You can also note which text was more detailed or covered more information. A strong comparison shows that you read both texts carefully, identified the important points, and thought about how they relate to each other.',
          keyVocabulary: ['comparison language', 'both', 'while', 'more detailed'],
        },
      ],
      practice: [
        {
          index: 0,
          question: 'What does it mean to contrast two texts?',
          type: 'multiple-choice',
          options: [
            'To find how they are alike',
            'To find how they are different',
            'To read them at the same time',
            'To copy them word for word',
          ],
          correctAnswer: 'To find how they are different',
          hint: 'Contrast is the opposite of compare.',
          explanation: 'Contrasting means finding the differences between two things. Comparing means finding similarities.',
          standardCode: '3.RI.9',
        },
        {
          index: 1,
          question: 'Text A says whales can hold their breath for up to 90 minutes. Text B says whales breathe air but does not mention how long they hold their breath. What is one difference between the texts?',
          type: 'short-answer',
          correctAnswer: 'Text A gives the specific detail that whales can hold their breath for 90 minutes, but Text B does not include this detail.',
          hint: 'Look for information that appears in one text but not the other.',
          explanation: 'Text A includes the specific time (90 minutes), while Text B only gives the general fact that whales breathe air. This is a difference in the level of detail.',
          standardCode: '3.RI.9',
        },
        {
          index: 2,
          question: 'Which graphic organizer has two overlapping circles?',
          type: 'multiple-choice',
          options: ['T-chart', 'Venn diagram', 'Web', 'Timeline'],
          correctAnswer: 'Venn diagram',
          hint: 'The overlapping area shows what two things have in common.',
          explanation: 'A Venn diagram uses two overlapping circles. Shared details go in the middle, and unique details go on each side.',
          standardCode: '3.RI.9',
        },
        {
          index: 3,
          question: 'Which phrase best introduces a similarity between two texts?',
          type: 'multiple-choice',
          options: [
            'On the other hand...',
            'Both texts explain...',
            'Only Text A says...',
            'In contrast...',
          ],
          correctAnswer: 'Both texts explain...',
          hint: 'You need a phrase that shows the texts agree or share information.',
          explanation: '"Both texts explain..." shows that the two texts share a similar point. This is comparison language for similarities.',
          standardCode: '3.RI.9',
        },
        {
          index: 4,
          question: 'Before comparing two texts, what should you do first for each text?',
          type: 'multiple-choice',
          options: [
            'Write the comparison right away',
            'Read each text carefully and identify its most important points',
            'Pick which text you like better',
            'Count the words in each text',
          ],
          correctAnswer: 'Read each text carefully and identify its most important points',
          hint: 'You need to understand each text before you can compare them.',
          explanation: 'You should read each text carefully and find the main ideas and key details before comparing them.',
          standardCode: '3.RI.9',
        },
      ],
      assessment: {
        questions: [
          {
            question: 'Text A says exercise keeps your heart healthy. Text B says exercise keeps your heart healthy and also strengthens your muscles. Describe one similarity and one difference.',
            type: 'short-answer',
            correctAnswer: 'Similarity: both texts say exercise keeps your heart healthy. Difference: Text B also mentions strengthening muscles, which Text A does not.',
            standardCode: '3.RI.9',
          },
          {
            question: 'What does it mean to compare two texts?',
            type: 'multiple-choice',
            options: [
              'To find how they are different',
              'To find how they are alike',
              'To read only one of them',
              'To rewrite them',
            ],
            correctAnswer: 'To find how they are alike',
            standardCode: '3.RI.9',
          },
          {
            question: 'Why might two texts on the same topic include different details?',
            type: 'multiple-choice',
            options: [
              'Because one author is always wrong',
              'Because different authors may focus on different aspects of the topic',
              'Because only one text is real',
              'Because the topic does not have many facts',
            ],
            correctAnswer: 'Because different authors may focus on different aspects of the topic',
            standardCode: '3.RI.9',
          },
        ],
      },
    },
  },
  {
    slug: 'grade3-ela-search-tools-research',
    title: 'Using Search Tools to Find Information',
    description: 'Conduct short research projects that build knowledge about a topic using search tools',
    subject: 'ela',
    grade: 3,
    gradeBand: 'k5',
    topicCluster: 'Writing',
    standardCodes: ['3.W.7'],
    content: {
      intro: {
        title: 'Using Search Tools to Find Information',
        text: 'When you want to learn about a topic, you need to know where and how to look for information. Books, encyclopedias, websites, and other reference materials are all search tools you can use. Today we will learn how to conduct short research projects that help you build knowledge about a topic by finding, selecting, and using information from different sources.',
      },
      segments: [
        {
          index: 0,
          title: 'What Is a Research Project?',
          text: 'A research project is when you explore a question or topic by finding information from different sources. A short research project might only take a day or two. You start with a question you want to answer, such as "How do butterflies grow?" Then you use search tools to find the answer. The goal is to learn something new and share what you learned through writing, a poster, or a presentation. Research helps you become an expert on a topic.',
          keyVocabulary: ['research project', 'question', 'sources', 'explore'],
        },
        {
          index: 1,
          title: 'Choosing and Using Search Tools',
          text: 'Search tools help you find information. A table of contents tells you what is in a book and where to find it. An index lists topics in alphabetical order at the back of a book. A glossary defines key words. Search engines on the computer let you type in keywords to find websites. An encyclopedia organizes information by topic. The key is to choose the right tool for the kind of information you need. A book about animals might be great for one project, while a website might be better for another.',
          keyVocabulary: ['table of contents', 'index', 'glossary', 'search engine', 'keywords'],
          example: 'If you want to know what "metamorphosis" means, you could use the glossary in your science book. If you want detailed information about butterfly life cycles, you might search for "butterfly life cycle" on a trusted website.',
        },
        {
          index: 2,
          title: 'Taking Notes from Sources',
          text: 'When you find useful information, take notes. Write down the important facts in your own words — do not copy sentences from the source. Use short phrases or bullet points. Write down where you found the information (the book title or website name) so you can find it again and give credit. Focus on facts that answer your research question. You do not need to write down everything — just the most important and relevant details.',
          keyVocabulary: ['notes', 'own words', 'bullet points', 'source', 'credit'],
        },
        {
          index: 3,
          title: 'Sharing What You Learned',
          text: 'After gathering your notes, organize your information and share what you learned. You might write a short report, create a poster, or give a brief presentation. Start by stating your topic and research question. Then share the facts you found, organized in a way that makes sense. End with a conclusion that sums up what you learned. Always mention the sources you used. Sharing your research shows that you can find, understand, and communicate new information.',
          keyVocabulary: ['report', 'organize', 'conclusion', 'communicate'],
        },
      ],
      practice: [
        {
          index: 0,
          question: 'What is the first step in a short research project?',
          type: 'multiple-choice',
          options: [
            'Write the conclusion',
            'Choose a question you want to answer',
            'Make a poster',
            'Read every book in the library',
          ],
          correctAnswer: 'Choose a question you want to answer',
          hint: 'Research starts with curiosity about something you want to learn.',
          explanation: 'The first step is choosing a question. This guides your research and helps you know what information to look for.',
          standardCode: '3.W.7',
        },
        {
          index: 1,
          question: 'You want to find the meaning of a difficult word in your science textbook. Which search tool should you use?',
          type: 'multiple-choice',
          options: ['Table of contents', 'Index', 'Glossary', 'Search engine'],
          correctAnswer: 'Glossary',
          hint: 'This tool defines key words used in a book.',
          explanation: 'A glossary defines important words used in the book. It is the best tool for finding the meaning of a difficult word in a textbook.',
          standardCode: '3.W.7',
        },
        {
          index: 2,
          question: 'When taking notes from a source, what should you do?',
          type: 'multiple-choice',
          options: [
            'Copy whole sentences from the book',
            'Write the important facts in your own words',
            'Only draw pictures',
            'Ignore where you found the information',
          ],
          correctAnswer: 'Write the important facts in your own words',
          hint: 'Good notes use your own words and focus on the most important facts.',
          explanation: 'You should write facts in your own words, not copy directly. This shows you understand the information.',
          standardCode: '3.W.7',
        },
        {
          index: 3,
          question: 'Why is it important to write down where you found your information?',
          type: 'short-answer',
          correctAnswer: 'So you can find it again and give credit to the source.',
          hint: 'Think about what happens if someone asks where you learned a fact.',
          explanation: 'Writing down your sources lets you find information again if needed and gives proper credit to the author or website.',
          standardCode: '3.W.7',
        },
        {
          index: 4,
          question: 'Which of these is a search tool you can use to find information in a book?',
          type: 'multiple-choice',
          options: ['A calculator', 'An index', 'A ruler', 'A pencil sharpener'],
          correctAnswer: 'An index',
          hint: 'This tool lists topics in alphabetical order at the back of a book.',
          explanation: 'An index is found at the back of a book and lists topics in alphabetical order with page numbers so you can find information quickly.',
          standardCode: '3.W.7',
        },
      ],
      assessment: {
        questions: [
          {
            question: 'You are researching how volcanoes erupt. Name two search tools you could use and explain how each would help.',
            type: 'short-answer',
            correctAnswer: 'A book about volcanoes with an index to find the right pages, and a search engine to find trusted websites with information and diagrams about eruptions.',
            standardCode: '3.W.7',
          },
          {
            question: 'What should you do after gathering your research notes?',
            type: 'multiple-choice',
            options: [
              'Throw the notes away',
              'Organize the information and share what you learned',
              'Start a completely different project',
              'Copy your notes exactly as a final report',
            ],
            correctAnswer: 'Organize the information and share what you learned',
            standardCode: '3.W.7',
          },
          {
            question: 'Why should you write notes in your own words instead of copying from a source?',
            type: 'multiple-choice',
            options: [
              'Because copying is faster',
              'Because writing in your own words shows you understand the information',
              'Because the source words are too long',
              'Because notes do not need to be accurate',
            ],
            correctAnswer: 'Because writing in your own words shows you understand the information',
            standardCode: '3.W.7',
          },
        ],
      },
    },
  },
]
