import type { ModuleSeed } from '../types'

export const GRADE_5_MATH: ModuleSeed[] = [
  {
    slug: 'grade5-math-adding-subtracting-fractions',
    title: 'Adding and Subtracting Fractions',
    description: 'Add and subtract fractions with unlike denominators by finding common denominators',
    subject: 'math',
    grade: 5,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations—Fractions',
    standardCodes: ['5.NF.1'],
    content: {
      intro: {
        title: 'Adding and Subtracting Fractions',
        text: 'You already know how to add fractions that have the same denominator. But what happens when the denominators are different? In this module you will learn how to find a common denominator so you can add and subtract any two fractions. This skill shows up everywhere — in cooking, building, and sharing things equally.',
      },
      segments: [
        {
          index: 0,
          title: 'Why We Need a Common Denominator',
          text: 'Fractions describe parts of a whole, but the parts must be the same size before we can combine them. Think about slicing one pizza into halves and another into thirds. A half is a different-sized piece from a third, so we cannot just count the slices together. We need to re-slice both pizzas so every piece is the same size. When fractions share the same denominator, their pieces are equal and we can add or subtract the numerators directly. For example, 2/6 + 1/6 = 3/6 works because both fractions are sixths.',
          keyVocabulary: ['denominator', 'numerator', 'common denominator', 'equivalent fraction'],
          example: '1/2 + 1/3 — halves and thirds are different sizes, so we must find a common denominator first.',
        },
        {
          index: 1,
          title: 'Finding the Least Common Denominator',
          text: 'The least common denominator (LCD) is the smallest number that both denominators divide into evenly. To find the LCD, list the multiples of each denominator until you find a match. For 2 and 3, the multiples of 2 are 2, 4, 6, 8 and the multiples of 3 are 3, 6, 9. The first number in both lists is 6, so the LCD is 6. Next, convert each fraction: multiply the numerator and denominator of 1/2 by 3 to get 3/6, and multiply the numerator and denominator of 1/3 by 2 to get 2/6. Now you can add: 3/6 + 2/6 = 5/6.',
          keyVocabulary: ['least common denominator', 'multiples', 'convert', 'equivalent'],
          example: 'LCD of 4 and 5 → multiples of 4: 4, 8, 12, 16, 20; multiples of 5: 5, 10, 15, 20 → LCD = 20.',
        },
        {
          index: 2,
          title: 'Adding Fractions with Unlike Denominators',
          text: 'Follow these steps to add fractions: first, find the LCD; second, write equivalent fractions using the LCD; third, add the numerators and keep the denominator the same; fourth, simplify if possible. Let us try 2/5 + 1/4. The LCD of 5 and 4 is 20. Convert: 2/5 = 8/20 and 1/4 = 5/20. Add: 8/20 + 5/20 = 13/20. Since 13 and 20 share no common factor other than 1, the fraction is already in simplest form.',
          keyVocabulary: ['simplify', 'simplest form', 'greatest common factor'],
        },
        {
          index: 3,
          title: 'Subtracting Fractions with Unlike Denominators',
          text: 'Subtracting fractions follows the same first two steps as adding — find the LCD and create equivalent fractions. Then subtract the numerators instead of adding them. For example, 3/4 − 1/3: the LCD of 4 and 3 is 12. Convert: 3/4 = 9/12 and 1/3 = 4/12. Subtract: 9/12 − 4/12 = 5/12. Always check whether the answer can be simplified. Here, 5 and 12 share no common factor, so 5/12 is the final answer.',
          keyVocabulary: ['subtract', 'difference', 'regroup'],
          example: '5/6 − 1/4: LCD = 12 → 10/12 − 3/12 = 7/12.',
        },
      ],
      practice: [
        { index: 0, question: 'What is 1/3 + 1/6?', type: 'short-answer', correctAnswer: '1/2', hint: 'The LCD of 3 and 6 is 6. Convert 1/3 to sixths.', explanation: '1/3 = 2/6. Then 2/6 + 1/6 = 3/6, which simplifies to 1/2.', standardCode: '5.NF.1' },
        { index: 1, question: 'What is 2/5 + 3/10?', type: 'short-answer', correctAnswer: '7/10', hint: 'The LCD of 5 and 10 is 10. Convert 2/5.', explanation: '2/5 = 4/10. Then 4/10 + 3/10 = 7/10.', standardCode: '5.NF.1' },
        { index: 2, question: 'What is 3/4 − 1/2?', type: 'short-answer', correctAnswer: '1/4', hint: 'Convert 1/2 to fourths.', explanation: '1/2 = 2/4. Then 3/4 − 2/4 = 1/4.', standardCode: '5.NF.1' },
        { index: 3, question: 'What is the least common denominator of 4 and 6?', type: 'multiple-choice', options: ['6', '10', '12', '24'], correctAnswer: '12', hint: 'List multiples of 4 and 6 until you find a match.', explanation: 'Multiples of 4: 4, 8, 12. Multiples of 6: 6, 12. The first common multiple is 12.', standardCode: '5.NF.1' },
        { index: 4, question: 'What is 5/8 − 1/4?', type: 'short-answer', correctAnswer: '3/8', hint: 'Convert 1/4 to eighths.', explanation: '1/4 = 2/8. Then 5/8 − 2/8 = 3/8.', standardCode: '5.NF.1' },
      ],
      assessment: {
        questions: [
          { question: 'What is 2/3 + 1/4?', type: 'short-answer', correctAnswer: '11/12', standardCode: '5.NF.1' },
          { question: 'What is 7/10 − 2/5?', type: 'short-answer', correctAnswer: '3/10', standardCode: '5.NF.1' },
          { question: 'Which expression equals 5/6?', type: 'multiple-choice', options: ['1/2 + 1/3', '1/3 + 1/6', '2/3 + 1/6', '1/2 + 1/6'], correctAnswer: '2/3 + 1/6', standardCode: '5.NF.1' },
        ],
      },
    },
  },
  {
    slug: 'grade5-math-multiplying-fractions',
    title: 'Multiplying Fractions',
    description: 'Multiply fractions by whole numbers and by other fractions using area models and equations',
    subject: 'math',
    grade: 5,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations—Fractions',
    standardCodes: ['5.NF.4'],
    content: {
      intro: {
        title: 'Multiplying Fractions',
        text: 'Multiplying fractions is a powerful skill. If a recipe calls for 2/3 cup of sugar and you want to make half the recipe, you need 1/2 of 2/3. In this module you will learn how to multiply a fraction by a whole number and a fraction by a fraction, using models and a simple rule.',
      },
      segments: [
        {
          index: 0,
          title: 'Multiplying a Fraction by a Whole Number',
          text: 'Multiplying a fraction by a whole number is like repeated addition. For example, 3 x 2/5 means 2/5 + 2/5 + 2/5. Add the numerators: 2 + 2 + 2 = 6, and keep the denominator: 6/5, which equals 1 1/5 as a mixed number. You can also multiply the whole number by the numerator: 3 x 2 = 6, then place it over the denominator 5. This shortcut always works and saves time when dealing with larger numbers.',
          keyVocabulary: ['repeated addition', 'mixed number', 'improper fraction', 'whole number'],
          example: '4 x 3/8 = 12/8 = 1 4/8 = 1 1/2.',
        },
        {
          index: 1,
          title: 'Multiplying a Fraction by a Fraction',
          text: 'To multiply two fractions, multiply the numerators together and then multiply the denominators together. For example, 2/3 x 4/5: multiply the numerators 2 x 4 = 8 and the denominators 3 x 5 = 15, giving 8/15. Think of it as finding a part of a part. If you shade 2/3 of a rectangle and then shade 4/5 of that shaded area, the overlapping region is 8/15 of the whole rectangle.',
          keyVocabulary: ['product', 'part of a part', 'area model'],
          example: '1/2 x 3/4 = 3/8 — half of three-fourths is three-eighths.',
        },
        {
          index: 2,
          title: 'Using Area Models',
          text: 'An area model is a rectangle divided into rows and columns. To model 2/3 x 3/4, divide the rectangle into 3 rows and 4 columns, making 12 equal parts. Shade 2 of the 3 rows to represent 2/3, and shade 3 of the 4 columns to represent 3/4. Count the parts where both shadings overlap: 6 out of 12, which simplifies to 1/2. Area models help you see why the multiplication rule works.',
          keyVocabulary: ['area model', 'rows', 'columns', 'overlap'],
        },
        {
          index: 3,
          title: 'Simplifying Products',
          text: 'After multiplying, always check whether you can simplify the answer. Find the greatest common factor (GCF) of the numerator and denominator and divide both by it. For 6/12, the GCF is 6, so 6/12 = 1/2. You can also simplify before you multiply by canceling common factors across the numerator and denominator. In 2/3 x 3/4, the 3 in the numerator and the 3 in the denominator cancel, leaving 2/1 x 1/4 = 2/4 = 1/2.',
          keyVocabulary: ['simplify', 'greatest common factor', 'cancel', 'cross-simplify'],
        },
      ],
      practice: [
        { index: 0, question: 'What is 3 x 1/4?', type: 'short-answer', correctAnswer: '3/4', hint: 'Multiply 3 times the numerator 1, and keep the denominator 4.', explanation: '3 x 1/4 = 3/4. The whole number multiplies only the numerator.', standardCode: '5.NF.4' },
        { index: 1, question: 'What is 1/2 x 2/3?', type: 'short-answer', correctAnswer: '1/3', hint: 'Multiply numerators and denominators, then simplify.', explanation: '1/2 x 2/3 = 2/6 = 1/3.', standardCode: '5.NF.4' },
        { index: 2, question: 'What is 2/5 x 5/6?', type: 'short-answer', correctAnswer: '1/3', hint: 'Try canceling the 5s before multiplying.', explanation: '2/5 x 5/6 — the 5s cancel, giving 2/6 = 1/3.', standardCode: '5.NF.4' },
        { index: 3, question: 'A recipe needs 3/4 cup of flour. If you make 2 batches, how much flour do you need?', type: 'short-answer', correctAnswer: '1 1/2', hint: 'Multiply 2 x 3/4.', explanation: '2 x 3/4 = 6/4 = 1 2/4 = 1 1/2 cups.', standardCode: '5.NF.4' },
        { index: 4, question: 'Which model shows 1/3 x 1/2?', type: 'multiple-choice', options: ['A rectangle with 1 of 6 parts shaded', 'A rectangle with 2 of 6 parts shaded', 'A rectangle with 3 of 6 parts shaded', 'A rectangle with 1 of 3 parts shaded'], correctAnswer: 'A rectangle with 1 of 6 parts shaded', hint: '1/3 x 1/2 = 1/6. How many parts should be shaded?', explanation: '1/3 x 1/2 = 1/6, so 1 out of 6 equal parts should be shaded.', standardCode: '5.NF.4' },
      ],
      assessment: {
        questions: [
          { question: 'What is 3/5 x 2/7?', type: 'short-answer', correctAnswer: '6/35', standardCode: '5.NF.4' },
          { question: 'What is 4 x 2/3?', type: 'short-answer', correctAnswer: '2 2/3', standardCode: '5.NF.4' },
          { question: 'What is 3/4 x 2/3 simplified?', type: 'multiple-choice', options: ['6/12', '1/2', '2/4', '3/6'], correctAnswer: '1/2', standardCode: '5.NF.4' },
        ],
      },
    },
  },
  {
    slug: 'grade5-math-division-of-fractions',
    title: 'Division of Fractions',
    description: 'Divide unit fractions by whole numbers and whole numbers by unit fractions using models and equations',
    subject: 'math',
    grade: 5,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations—Fractions',
    standardCodes: ['5.NF.7'],
    content: {
      intro: {
        title: 'Division of Fractions',
        text: 'What does it mean to divide with fractions? Imagine splitting half a pie among 3 friends, or figuring out how many quarter-cup scoops fit in 3 cups of rice. Division with fractions answers these real questions. In Grade 5 we focus on dividing a unit fraction by a whole number and a whole number by a unit fraction.',
      },
      segments: [
        {
          index: 0,
          title: 'Dividing a Unit Fraction by a Whole Number',
          text: 'A unit fraction has 1 as its numerator, like 1/2, 1/3, or 1/4. When you divide a unit fraction by a whole number, you are splitting that fraction into equal parts. For example, 1/2 divided by 3 means splitting one-half into 3 equal pieces. Each piece is 1/6 of the whole. To compute this, multiply the denominator by the whole number: 1/(2 x 3) = 1/6. You can picture a fraction strip: take the half and cut it into 3 equal sections.',
          keyVocabulary: ['unit fraction', 'divide', 'equal parts', 'fraction strip'],
          example: '1/4 ÷ 2 = 1/8 — split one-fourth into 2 equal pieces to get one-eighth.',
        },
        {
          index: 1,
          title: 'Dividing a Whole Number by a Unit Fraction',
          text: 'When you divide a whole number by a unit fraction, you are asking how many of that fraction fit into the whole number. For example, 3 ÷ 1/4 means how many quarters are in 3 wholes? Since each whole has 4 quarters, 3 wholes have 3 x 4 = 12 quarters. The rule is: multiply the whole number by the denominator of the fraction. Notice the answer is larger than the number you started with, because many small pieces fit into a larger amount.',
          keyVocabulary: ['quotient', 'fit into', 'multiply by denominator'],
          example: '2 ÷ 1/3 = 6 — there are 6 thirds in 2 wholes.',
        },
        {
          index: 2,
          title: 'Using Models and Number Lines',
          text: 'A number line is a great way to see fraction division. To show 2 ÷ 1/4, draw a number line from 0 to 2 and mark every 1/4. Count the jumps: 1/4, 2/4, 3/4, 1, 5/4, 6/4, 7/4, 2. That is 8 jumps, so 2 ÷ 1/4 = 8. For 1/3 ÷ 2, start at 0 and mark 1/3. Split that segment into 2 equal parts. Each part is 1/6 of the whole, confirming 1/3 ÷ 2 = 1/6. Models make the abstract rule concrete.',
          keyVocabulary: ['number line', 'jumps', 'segment', 'concrete model'],
        },
      ],
      practice: [
        { index: 0, question: 'What is 1/3 ÷ 4?', type: 'short-answer', correctAnswer: '1/12', hint: 'Split one-third into 4 equal pieces.', explanation: '1/3 ÷ 4 = 1/(3 x 4) = 1/12.', standardCode: '5.NF.7' },
        { index: 1, question: 'What is 5 ÷ 1/2?', type: 'short-answer', correctAnswer: '10', hint: 'How many halves fit in 5 wholes?', explanation: '5 ÷ 1/2 = 5 x 2 = 10. There are 10 halves in 5.', standardCode: '5.NF.7' },
        { index: 2, question: 'What is 1/6 ÷ 3?', type: 'short-answer', correctAnswer: '1/18', hint: 'Multiply the denominator by the whole number.', explanation: '1/6 ÷ 3 = 1/(6 x 3) = 1/18.', standardCode: '5.NF.7' },
        { index: 3, question: 'A ribbon is 1/4 yard long. It is cut into 2 equal pieces. How long is each piece?', type: 'short-answer', correctAnswer: '1/8', hint: 'Divide 1/4 by 2.', explanation: '1/4 ÷ 2 = 1/8. Each piece is 1/8 of a yard.', standardCode: '5.NF.7' },
        { index: 4, question: 'How many 1/5-cup servings are in 4 cups of juice?', type: 'multiple-choice', options: ['4/5', '5', '9', '20'], correctAnswer: '20', hint: '4 ÷ 1/5 = 4 x 5.', explanation: '4 ÷ 1/5 = 20. Each cup has 5 fifths, and 4 x 5 = 20.', standardCode: '5.NF.7' },
      ],
      assessment: {
        questions: [
          { question: 'What is 1/2 ÷ 5?', type: 'short-answer', correctAnswer: '1/10', standardCode: '5.NF.7' },
          { question: 'What is 6 ÷ 1/3?', type: 'short-answer', correctAnswer: '18', standardCode: '5.NF.7' },
          { question: 'How many 1/4-pound bags can you fill from 3 pounds of rice?', type: 'short-answer', correctAnswer: '12', standardCode: '5.NF.7' },
        ],
      },
    },
  },
  {
    slug: 'grade5-math-multi-digit-multiplication-division',
    title: 'Multi-Digit Multiplication and Division',
    description: 'Fluently multiply multi-digit whole numbers and divide with two-digit divisors using the standard algorithm',
    subject: 'math',
    grade: 5,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations in Base Ten',
    standardCodes: ['5.NBT.5', '5.NBT.6'],
    content: {
      intro: {
        title: 'Multi-Digit Multiplication and Division',
        text: 'In fifth grade you are expected to multiply multi-digit numbers fluently and divide with up to four-digit dividends and two-digit divisors. These skills are the foundation for algebra and help you solve real-world problems like calculating distances, costs, and measurements.',
      },
      segments: [
        {
          index: 0,
          title: 'Reviewing Multi-Digit Multiplication',
          text: 'To multiply numbers like 345 x 27, break the problem into parts using the standard algorithm. First multiply 345 by 7 (the ones digit of 27): 7 x 5 = 35, write 5 carry 3; 7 x 4 = 28 plus 3 = 31, write 1 carry 3; 7 x 3 = 21 plus 3 = 24. The first partial product is 2,415. Next multiply 345 by 20 (the tens digit): this gives 6,900. Add the partial products: 2,415 + 6,900 = 9,315. Keeping your columns aligned is essential for accuracy.',
          keyVocabulary: ['standard algorithm', 'partial product', 'carry', 'regroup'],
          example: '123 x 45: partial products are 123 x 5 = 615 and 123 x 40 = 4,920. Sum: 5,535.',
        },
        {
          index: 1,
          title: 'Estimating Before You Multiply',
          text: 'Before working through the algorithm, estimate the answer to check your work later. Round each factor to its leading digit. For 345 x 27, round to 300 x 30 = 9,000. Your exact answer should be close to this estimate. If you calculate 93,150 by mistake, the estimate tells you something is off. Estimation is a powerful error-checking strategy that takes only a few seconds.',
          keyVocabulary: ['estimate', 'round', 'leading digit', 'reasonable'],
        },
        {
          index: 2,
          title: 'Long Division with Two-Digit Divisors',
          text: 'Dividing by a two-digit number uses the same divide-multiply-subtract-bring-down cycle. For 1,368 ÷ 24, ask how many times 24 fits into 136. Estimate: 24 x 5 = 120 and 24 x 6 = 144. Since 144 is too large, use 5. Write 5 above the 6 in 1,368. Multiply: 5 x 24 = 120. Subtract: 136 − 120 = 16. Bring down the 8 to get 168. Now 24 x 7 = 168 exactly, so write 7. The quotient is 57 with no remainder.',
          keyVocabulary: ['dividend', 'divisor', 'quotient', 'remainder', 'long division'],
          example: '945 ÷ 15 = 63 — 15 x 6 = 90, subtract from 94 to get 4, bring down 5 to get 45, 15 x 3 = 45.',
        },
        {
          index: 3,
          title: 'Interpreting Remainders',
          text: 'Sometimes division does not come out evenly. For 1,500 ÷ 32, the quotient is 46 with a remainder of 28, because 32 x 46 = 1,472 and 1,500 − 1,472 = 28. The remainder can be written as R28 or as the fraction 28/32, which simplifies to 7/8. In word problems, think about what the remainder means. If you are packing 1,500 items into boxes of 32, you need 47 boxes — 46 full boxes plus one more for the leftover 28 items.',
          keyVocabulary: ['remainder', 'interpret', 'leftover', 'context'],
        },
      ],
      practice: [
        { index: 0, question: 'What is 246 x 13?', type: 'short-answer', correctAnswer: '3198', hint: 'Compute 246 x 3 and 246 x 10 separately, then add.', explanation: '246 x 3 = 738 and 246 x 10 = 2,460. Sum: 738 + 2,460 = 3,198.', standardCode: '5.NBT.5' },
        { index: 1, question: 'Estimate 489 x 21 by rounding.', type: 'multiple-choice', options: ['8,000', '10,000', '12,000', '15,000'], correctAnswer: '10,000', hint: 'Round 489 to 500 and 21 to 20.', explanation: '500 x 20 = 10,000. The exact answer (10,269) is close to this estimate.', standardCode: '5.NBT.5' },
        { index: 2, question: 'What is 1,296 ÷ 18?', type: 'short-answer', correctAnswer: '72', hint: 'Use long division: how many 18s fit into 129?', explanation: '18 x 7 = 126, subtract from 129 to get 3, bring down 6 to get 36, 18 x 2 = 36. Quotient: 72.', standardCode: '5.NBT.6' },
        { index: 3, question: 'What is the remainder when 500 is divided by 12?', type: 'short-answer', correctAnswer: '8', hint: '12 x 41 = 492. What is left over?', explanation: '12 x 41 = 492. 500 − 492 = 8, so the remainder is 8.', standardCode: '5.NBT.6' },
        { index: 4, question: 'A school has 1,150 students split equally among 25 classrooms. How many students per classroom?', type: 'short-answer', correctAnswer: '46', hint: 'Divide 1,150 by 25.', explanation: '1,150 ÷ 25 = 46. Each classroom has 46 students.', standardCode: '5.NBT.6' },
      ],
      assessment: {
        questions: [
          { question: 'What is 305 x 24?', type: 'short-answer', correctAnswer: '7320', standardCode: '5.NBT.5' },
          { question: 'What is 2,184 ÷ 28?', type: 'short-answer', correctAnswer: '78', standardCode: '5.NBT.6' },
          { question: 'A factory produces 4,536 bottles per day. Bottles are packed 36 to a case. How many full cases are produced?', type: 'short-answer', correctAnswer: '126', standardCode: '5.NBT.6' },
        ],
      },
    },
  },
  {
    slug: 'grade5-math-decimals-to-thousandths',
    title: 'Decimals to Thousandths',
    description: 'Read, write, compare, round, and perform operations with decimals to the thousandths place',
    subject: 'math',
    grade: 5,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations in Base Ten',
    standardCodes: ['5.NBT.3', '5.NBT.7'],
    content: {
      intro: {
        title: 'Decimals to Thousandths',
        text: 'Decimals are another way to write fractions. You already know tenths and hundredths from money — a dime is 0.10 and a penny is 0.01. Now we will extend to thousandths. Understanding decimals to the thousandths place helps with precise measurements in science, sports times, and engineering.',
      },
      segments: [
        {
          index: 0,
          title: 'Reading and Writing Decimals to Thousandths',
          text: 'Each place to the right of the decimal point is ten times smaller than the one before it. The first place is tenths (1/10), the second is hundredths (1/100), and the third is thousandths (1/1000). The number 3.274 is read as "three and two hundred seventy-four thousandths." To write it in expanded form: 3 + 2/10 + 7/100 + 4/1000. Notice the last digit tells us the smallest place value, which names the decimal — thousandths.',
          keyVocabulary: ['tenths', 'hundredths', 'thousandths', 'expanded form', 'place value'],
          example: '0.635 = 6 tenths + 3 hundredths + 5 thousandths = 635/1000.',
        },
        {
          index: 1,
          title: 'Comparing and Ordering Decimals',
          text: 'To compare decimals, line up the decimal points and compare digits from left to right. Compare 4.302 and 4.32. The ones digits are both 4. The tenths are both 3. The hundredths are 0 and 2. Since 0 is less than 2, we know 4.302 < 4.32. Adding a trailing zero can help: 4.320 versus 4.302 makes the comparison clearer. Remember, 4.32 and 4.320 are the same value — trailing zeros do not change the number.',
          keyVocabulary: ['compare', 'order', 'trailing zero', 'greater than', 'less than'],
        },
        {
          index: 2,
          title: 'Adding and Subtracting Decimals',
          text: 'Adding and subtracting decimals is just like adding and subtracting whole numbers — as long as you line up the decimal points. Write each number so the decimal points are directly above one another, then add zeros to fill empty places. For 12.6 + 3.475, rewrite as 12.600 + 3.475. Add column by column from right to left: 0 + 5 = 5, 0 + 7 = 7, 6 + 4 = 10 (write 0 carry 1), 2 + 3 + 1 = 6, 1 + 0 = 1. The answer is 16.075.',
          keyVocabulary: ['line up', 'decimal point', 'placeholder zero', 'regroup'],
          example: '8.25 − 3.109 = 8.250 − 3.109 = 5.141.',
        },
        {
          index: 3,
          title: 'Multiplying and Dividing Decimals',
          text: 'To multiply decimals, ignore the decimal points and multiply as whole numbers. Then count the total number of decimal places in both factors and place the decimal point that many places from the right in the product. For 0.6 x 0.04: multiply 6 x 4 = 24, count decimal places (1 + 2 = 3), so the answer is 0.024. To divide a decimal by a whole number, place the decimal point in the quotient directly above the decimal point in the dividend and divide normally.',
          keyVocabulary: ['factor', 'product', 'decimal places', 'quotient'],
          example: '2.4 x 0.3: multiply 24 x 3 = 72, two decimal places total → 0.72.',
        },
      ],
      practice: [
        { index: 0, question: 'Write 0.047 in words.', type: 'short-answer', correctAnswer: 'forty-seven thousandths', hint: 'The last digit is in the thousandths place.', explanation: '0.047 is read as forty-seven thousandths because the 7 is in the thousandths place.', standardCode: '5.NBT.3' },
        { index: 1, question: 'Which is greater: 0.52 or 0.519?', type: 'multiple-choice', options: ['0.52', '0.519', 'They are equal'], correctAnswer: '0.52', hint: 'Write 0.52 as 0.520 and compare hundredths.', explanation: '0.520 vs 0.519: the hundredths are both 2 and 1, wait — tenths are 5 and 5, hundredths are 2 and 1. 2 > 1, so 0.52 > 0.519.', standardCode: '5.NBT.3' },
        { index: 2, question: 'What is 4.75 + 2.386?', type: 'short-answer', correctAnswer: '7.136', hint: 'Line up the decimals: 4.750 + 2.386.', explanation: '4.750 + 2.386 = 7.136. Line up the decimal points and add.', standardCode: '5.NBT.7' },
        { index: 3, question: 'What is 10.2 − 3.875?', type: 'short-answer', correctAnswer: '6.325', hint: 'Rewrite as 10.200 − 3.875.', explanation: '10.200 − 3.875 = 6.325. Add placeholder zeros, then subtract.', standardCode: '5.NBT.7' },
        { index: 4, question: 'What is 0.8 x 0.5?', type: 'short-answer', correctAnswer: '0.40', hint: '8 x 5 = 40, then place the decimal point.', explanation: '8 x 5 = 40. There are two total decimal places (one in each factor), so the answer is 0.40 or 0.4.', standardCode: '5.NBT.7' },
      ],
      assessment: {
        questions: [
          { question: 'Order from least to greatest: 0.305, 0.35, 0.3', type: 'short-answer', correctAnswer: '0.3, 0.305, 0.35', standardCode: '5.NBT.3' },
          { question: 'What is 6.04 + 12.198?', type: 'short-answer', correctAnswer: '18.238', standardCode: '5.NBT.7' },
          { question: 'What is 1.2 x 0.03?', type: 'short-answer', correctAnswer: '0.036', standardCode: '5.NBT.7' },
        ],
      },
    },
  },
  {
    slug: 'grade5-math-coordinate-plane-volume',
    title: 'Coordinate Plane and Volume',
    description: 'Graph points on the coordinate plane and calculate the volume of rectangular prisms',
    subject: 'math',
    grade: 5,
    gradeBand: 'k5',
    topicCluster: 'Geometry & Measurement',
    standardCodes: ['5.G.1', '5.MD.3'],
    content: {
      intro: {
        title: 'Coordinate Plane and Volume',
        text: 'In this module you will explore two big ideas. First, you will learn to use a coordinate plane to describe exact locations with ordered pairs. Second, you will discover how to measure the space inside three-dimensional shapes by calculating volume. Both skills connect math to the real world — from maps and video games to packing boxes.',
      },
      segments: [
        {
          index: 0,
          title: 'The Coordinate Plane',
          text: 'A coordinate plane is formed by two number lines that cross at a point called the origin. The horizontal line is the x-axis and the vertical line is the y-axis. The origin is at (0, 0). Every point on the plane is described by an ordered pair (x, y). The first number tells how far to move right from the origin, and the second number tells how far to move up. For example, the point (3, 5) means move 3 units right and 5 units up. In Grade 5 we work only with positive numbers, so all points are in the first quadrant.',
          keyVocabulary: ['coordinate plane', 'x-axis', 'y-axis', 'origin', 'ordered pair', 'quadrant'],
          example: 'Point A is at (2, 4): start at the origin, go 2 right and 4 up.',
        },
        {
          index: 1,
          title: 'Plotting and Reading Points',
          text: 'To plot a point, start at the origin. Move right along the x-axis the number of units shown by the first coordinate. Then move up the number of units shown by the second coordinate. Mark the spot with a dot and label it. To read a point that is already plotted, reverse the process: look straight down to the x-axis to find the x-coordinate and straight across to the y-axis to find the y-coordinate. Practice: the point at 4 units right and 6 units up is written as (4, 6).',
          keyVocabulary: ['plot', 'label', 'x-coordinate', 'y-coordinate'],
        },
        {
          index: 2,
          title: 'Understanding Volume',
          text: 'Volume measures the amount of space inside a three-dimensional figure. We measure volume in cubic units — imagine filling a box with tiny cubes that are each one unit on every side. A rectangular prism is a box shape with length, width, and height. The volume formula is V = l x w x h. For a box that is 5 units long, 3 units wide, and 2 units high, V = 5 x 3 x 2 = 30 cubic units. You can also think of volume as the area of the base times the height: V = B x h.',
          keyVocabulary: ['volume', 'cubic units', 'rectangular prism', 'length', 'width', 'height'],
          example: 'A box is 4 cm x 3 cm x 2 cm. Volume = 4 x 3 x 2 = 24 cubic centimeters.',
        },
        {
          index: 3,
          title: 'Composite Figures and Real-World Volume',
          text: 'Some shapes are made by combining two or more rectangular prisms. To find the total volume, break the shape into non-overlapping prisms, calculate each volume, and add them together. Imagine an L-shaped pool: split it into two rectangles, find each volume, then add. For example, one section is 6 x 4 x 2 = 48 cubic feet and the other is 3 x 4 x 2 = 24 cubic feet, so the total volume is 48 + 24 = 72 cubic feet.',
          keyVocabulary: ['composite figure', 'non-overlapping', 'decompose', 'total volume'],
        },
      ],
      practice: [
        { index: 0, question: 'What ordered pair describes a point 5 units right and 3 units up from the origin?', type: 'short-answer', correctAnswer: '(5, 3)', hint: 'The first number is the horizontal distance and the second is the vertical distance.', explanation: 'Moving 5 right and 3 up gives the ordered pair (5, 3).', standardCode: '5.G.1' },
        { index: 1, question: 'A point is at (0, 7). Where is it located?', type: 'multiple-choice', options: ['On the x-axis', 'On the y-axis', 'At the origin', 'In the middle of the grid'], correctAnswer: 'On the y-axis', hint: 'The x-coordinate is 0, so there is no movement to the right.', explanation: 'When x = 0 the point sits on the y-axis, 7 units up.', standardCode: '5.G.1' },
        { index: 2, question: 'What is the volume of a box that is 6 cm long, 4 cm wide, and 3 cm high?', type: 'short-answer', correctAnswer: '72', hint: 'Use V = l x w x h.', explanation: 'V = 6 x 4 x 3 = 72 cubic centimeters.', standardCode: '5.MD.3' },
        { index: 3, question: 'A cube has sides of 5 inches. What is its volume?', type: 'short-answer', correctAnswer: '125', hint: 'A cube has equal length, width, and height.', explanation: 'V = 5 x 5 x 5 = 125 cubic inches.', standardCode: '5.MD.3' },
        { index: 4, question: 'An L-shaped figure is made of two prisms: one is 4 x 2 x 3 and the other is 4 x 2 x 2. What is the total volume?', type: 'short-answer', correctAnswer: '40', hint: 'Find each volume separately and add.', explanation: '4 x 2 x 3 = 24 and 4 x 2 x 2 = 16. Total = 24 + 16 = 40 cubic units.', standardCode: '5.MD.3' },
      ],
      assessment: {
        questions: [
          { question: 'Plot the point (6, 2). Which axis do you move along first?', type: 'multiple-choice', options: ['y-axis', 'x-axis', 'Either one', 'Neither'], correctAnswer: 'x-axis', standardCode: '5.G.1' },
          { question: 'A rectangular prism is 10 m long, 5 m wide, and 2 m high. What is its volume?', type: 'short-answer', correctAnswer: '100', standardCode: '5.MD.3' },
          { question: 'Two boxes are stacked. The bottom box is 8 x 4 x 3 and the top box is 8 x 4 x 2. What is the combined volume in cubic units?', type: 'short-answer', correctAnswer: '160', standardCode: '5.MD.3' },
        ],
      },
    },
  },
  {
    slug: 'grade5-math-place-value-to-billions',
    title: 'Place Value to Billions',
    description: 'Understand that a digit in one place represents 10 times what it represents in the place to its right',
    subject: 'math',
    grade: 5,
    gradeBand: 'k5',
    topicCluster: 'Number & Operations in Base Ten',
    standardCodes: ['5.NBT.1'],
    content: {
      intro: {
        title: 'Place Value to Billions',
        text: 'Our number system is built on a simple but powerful idea: each place is worth ten times the place to its right. A 3 in the tens place is worth 30, but move it one place left and it is worth 300 — ten times as much. In this module you will extend place value understanding all the way to the billions, which helps you read population counts, national budgets, and distances in space.',
      },
      segments: [
        {
          index: 0,
          title: 'The 10-to-1 Relationship Between Places',
          text: 'In our base-ten system, moving one place to the left multiplies the value of a digit by 10. Moving one place to the right divides it by 10. Consider the digit 5: in the ones place it is worth 5, in the tens place it is worth 50, in the hundreds place it is worth 500, and so on. This pattern continues without end. The same idea works with decimals — the tenths place is one-tenth of the ones place. Understanding this relationship is the key to reading and writing very large numbers.',
          keyVocabulary: ['place value', 'base ten', 'digit', 'ten times', 'one-tenth'],
          example: 'The 7 in 70,000 is worth ten times the 7 in 7,000.',
        },
        {
          index: 1,
          title: 'Reading and Writing Numbers to Billions',
          text: 'Large numbers are organized into periods separated by commas: ones, thousands, millions, and billions. Each period has three places — hundreds, tens, and ones. The number 4,528,063,197 is read as "four billion, five hundred twenty-eight million, sixty-three thousand, one hundred ninety-seven." When writing a number in expanded form, show the value of each digit: 4,000,000,000 + 500,000,000 + 28,000,000 + 63,000 + 197.',
          keyVocabulary: ['period', 'billions', 'millions', 'thousands', 'expanded form', 'standard form'],
          example: '2,305,000,000 is read as two billion, three hundred five million.',
        },
        {
          index: 2,
          title: 'Comparing and Rounding Large Numbers',
          text: 'To compare large numbers, start at the leftmost digit and work right until you find a difference. For 3,482,000,000 and 3,479,000,000, the digits match until the millions place: 2 versus 9 — wait, compare carefully: 482 million versus 479 million, and since 482 > 479, the first number is greater. When rounding, find the digit in the target place, look at the digit to its right, and round up if it is 5 or more, down if it is less than 5. Rounding 6,749,000,000 to the nearest billion gives 7,000,000,000.',
          keyVocabulary: ['compare', 'round', 'greater than', 'less than', 'approximate'],
        },
      ],
      practice: [
        { index: 0, question: 'In 450,000, how many times greater is the 4 than it would be in 45,000?', type: 'short-answer', correctAnswer: '10', hint: 'The 4 moved one place to the left.', explanation: 'In 450,000 the 4 is in the hundred-thousands place (400,000). In 45,000 it is in the ten-thousands place (40,000). 400,000 is 10 times 40,000.', standardCode: '5.NBT.1' },
        { index: 1, question: 'What is the value of the 6 in 3,600,000,000?', type: 'multiple-choice', options: ['6 million', '60 million', '600 million', '6 billion'], correctAnswer: '600 million', hint: 'Count the place from the right: the 6 is in the hundred-millions place.', explanation: 'The 6 is in the hundred-millions place, so its value is 600,000,000 or 600 million.', standardCode: '5.NBT.1' },
        { index: 2, question: 'Write 5,080,000,000 in words.', type: 'short-answer', correctAnswer: 'five billion, eighty million', hint: 'Break the number into periods: billions, millions, thousands, ones.', explanation: '5 billion and 80 million. The thousands and ones periods are zero.', standardCode: '5.NBT.1' },
        { index: 3, question: 'Round 2,450,000,000 to the nearest billion.', type: 'short-answer', correctAnswer: '2,000,000,000', hint: 'Look at the digit in the hundred-millions place: 4. Is it 5 or more?', explanation: 'The hundred-millions digit is 4, which is less than 5, so round down to 2,000,000,000.', standardCode: '5.NBT.1' },
        { index: 4, question: 'Which number has a 9 that is worth 10 times the 9 in 290,000?', type: 'multiple-choice', options: ['29,000', '2,900,000', '900,000', '9,000'], correctAnswer: '2,900,000', hint: 'The 9 in 290,000 is in the ten-thousands place (90,000). Ten times that is 900,000.', explanation: 'In 290,000 the 9 is worth 90,000. Ten times that is 900,000. In 2,900,000 the 9 is in the hundred-thousands place and is worth 900,000.', standardCode: '5.NBT.1' },
      ],
      assessment: {
        questions: [
          { question: 'How many times greater is the 3 in 3,000,000 than the 3 in 300,000?', type: 'short-answer', correctAnswer: '10', standardCode: '5.NBT.1' },
          { question: 'What is 7,250,000,000 rounded to the nearest billion?', type: 'short-answer', correctAnswer: '7,000,000,000', standardCode: '5.NBT.1' },
          { question: 'Which digit is in the billions place in 8,432,107,000?', type: 'multiple-choice', options: ['4', '8', '3', '2'], correctAnswer: '8', standardCode: '5.NBT.1' },
        ],
      },
    },
  },
  {
    slug: 'grade5-math-order-of-operations',
    title: 'Order of Operations',
    description: 'Use parentheses, brackets, and braces in numerical expressions and evaluate them correctly',
    subject: 'math',
    grade: 5,
    gradeBand: 'k5',
    topicCluster: 'Operations & Algebraic Thinking',
    standardCodes: ['5.OA.1'],
    content: {
      intro: {
        title: 'Order of Operations',
        text: 'When a math expression has more than one operation, the order in which you compute matters. Without agreed-upon rules, the expression 3 + 4 x 2 could equal 14 or 11 depending on what you do first. Mathematicians follow a standard order of operations so everyone gets the same answer. In this module you will learn that order and practice using parentheses, brackets, and braces to control it.',
      },
      segments: [
        {
          index: 0,
          title: 'The Standard Order',
          text: 'The order of operations tells us to first evaluate expressions inside grouping symbols (parentheses, brackets, braces), then multiply and divide from left to right, and finally add and subtract from left to right. A common way to remember this is PEMDAS: Parentheses, Exponents, Multiplication and Division, Addition and Subtraction. In Grade 5 we focus on the steps involving grouping symbols, multiplication, division, addition, and subtraction. For 3 + 4 x 2, multiply first: 4 x 2 = 8, then add: 3 + 8 = 11.',
          keyVocabulary: ['order of operations', 'PEMDAS', 'grouping symbols', 'evaluate'],
          example: '6 + 2 x 5 = 6 + 10 = 16, not 8 x 5 = 40.',
        },
        {
          index: 1,
          title: 'Parentheses, Brackets, and Braces',
          text: 'Grouping symbols tell you to compute what is inside first, no matter what operations are there. Parentheses ( ) are the most common. Brackets [ ] go around parentheses when you need a second layer, and braces { } add a third layer. For example, {2 x [3 + (4 − 1)]} means: first compute 4 − 1 = 3 inside the parentheses, then 3 + 3 = 6 inside the brackets, then 2 x 6 = 12 inside the braces. Always work from the innermost grouping symbol outward.',
          keyVocabulary: ['parentheses', 'brackets', 'braces', 'innermost', 'nested'],
          example: '[(8 − 2) x 3] + 1 = [6 x 3] + 1 = 18 + 1 = 19.',
        },
        {
          index: 2,
          title: 'Writing and Interpreting Expressions',
          text: 'You can use grouping symbols to write expressions for word problems. "Add 3 and 5, then multiply by 2" becomes (3 + 5) x 2. Without the parentheses, 3 + 5 x 2 would mean something different — multiply 5 by 2 first, then add 3. Reading expressions carefully and placing grouping symbols correctly ensures the math matches the real-world situation. Practice translating between words and symbols until it feels natural.',
          keyVocabulary: ['expression', 'translate', 'interpret', 'numerical expression'],
        },
      ],
      practice: [
        { index: 0, question: 'Evaluate: 8 + 2 x 3', type: 'short-answer', correctAnswer: '14', hint: 'Multiply before adding.', explanation: '2 x 3 = 6, then 8 + 6 = 14.', standardCode: '5.OA.1' },
        { index: 1, question: 'Evaluate: (8 + 2) x 3', type: 'short-answer', correctAnswer: '30', hint: 'Do what is in the parentheses first.', explanation: '(8 + 2) = 10, then 10 x 3 = 30.', standardCode: '5.OA.1' },
        { index: 2, question: 'Evaluate: 5 x {2 + [3 x (1 + 1)]}', type: 'short-answer', correctAnswer: '40', hint: 'Work from the innermost grouping outward: 1 + 1 first.', explanation: '1 + 1 = 2, then 3 x 2 = 6, then 2 + 6 = 8, then 5 x 8 = 40.', standardCode: '5.OA.1' },
        { index: 3, question: 'Which expression means "subtract 1 from 9, then divide by 4"?', type: 'multiple-choice', options: ['9 − 1 ÷ 4', '(9 − 1) ÷ 4', '9 − (1 ÷ 4)', '9 ÷ 4 − 1'], correctAnswer: '(9 − 1) ÷ 4', hint: 'You want to subtract first, so group the subtraction.', explanation: '(9 − 1) ÷ 4 = 8 ÷ 4 = 2. The parentheses make the subtraction happen first.', standardCode: '5.OA.1' },
        { index: 4, question: 'Evaluate: 12 ÷ (2 + 4) + 1', type: 'short-answer', correctAnswer: '3', hint: 'Parentheses first: 2 + 4 = 6.', explanation: '2 + 4 = 6, then 12 ÷ 6 = 2, then 2 + 1 = 3.', standardCode: '5.OA.1' },
      ],
      assessment: {
        questions: [
          { question: 'Evaluate: 4 x (6 − 2) + 5', type: 'short-answer', correctAnswer: '21', standardCode: '5.OA.1' },
          { question: 'Evaluate: {10 − [2 x (1 + 2)]}', type: 'short-answer', correctAnswer: '4', standardCode: '5.OA.1' },
          { question: 'Which expression equals 20?', type: 'multiple-choice', options: ['2 + 3 x 6', '(2 + 3) x 6', '(2 + 3) x 4', '2 x 3 + 6'], correctAnswer: '(2 + 3) x 4', standardCode: '5.OA.1' },
        ],
      },
    },
  },
  {
    slug: 'grade5-math-classifying-2d-shapes',
    title: 'Classifying Two-Dimensional Shapes',
    description: 'Classify two-dimensional figures based on properties of their sides and angles, including subcategories',
    subject: 'math',
    grade: 5,
    gradeBand: 'k5',
    topicCluster: 'Geometry',
    standardCodes: ['5.G.3', '5.G.4'],
    content: {
      intro: {
        title: 'Classifying Two-Dimensional Shapes',
        text: 'Shapes can be sorted into groups based on their properties — the number of sides, whether sides are parallel or equal in length, and the types of angles they have. In this module you will learn to classify triangles and quadrilaterals into subcategories, and you will discover that some categories fit inside others. For example, every square is a rectangle, but not every rectangle is a square.',
      },
      segments: [
        {
          index: 0,
          title: 'Properties of Triangles',
          text: 'Triangles can be classified by their sides or their angles. By sides: equilateral (all three sides equal), isosceles (exactly two sides equal), and scalene (no sides equal). By angles: acute (all angles less than 90°), right (one angle exactly 90°), and obtuse (one angle greater than 90°). A single triangle can belong to categories from both systems. For example, a right isosceles triangle has a 90° angle and two equal sides.',
          keyVocabulary: ['equilateral', 'isosceles', 'scalene', 'acute', 'right', 'obtuse'],
          example: 'A triangle with sides 5, 5, and 7 is isosceles. If all its angles are less than 90°, it is also acute.',
        },
        {
          index: 1,
          title: 'Properties of Quadrilaterals',
          text: 'A quadrilateral is any four-sided polygon. Special quadrilaterals include parallelograms (two pairs of parallel sides), rectangles (parallelograms with four right angles), rhombuses (parallelograms with four equal sides), and squares (rectangles that are also rhombuses — four right angles and four equal sides). A trapezoid has exactly one pair of parallel sides. Understanding these properties shows how the categories relate to each other in a hierarchy.',
          keyVocabulary: ['quadrilateral', 'parallelogram', 'rectangle', 'rhombus', 'square', 'trapezoid'],
          example: 'A square has all the properties of a rectangle and all the properties of a rhombus.',
        },
        {
          index: 2,
          title: 'Shape Hierarchies',
          text: 'Shapes fit into a hierarchy where more specific categories belong inside more general ones. All squares are rectangles, all rectangles are parallelograms, and all parallelograms are quadrilaterals. This means any property that is true for parallelograms is automatically true for rectangles and squares. If you know a shape is a square, you know it has parallel sides, right angles, and equal sides — all inherited from the categories above it.',
          keyVocabulary: ['hierarchy', 'subcategory', 'classify', 'property', 'attribute'],
        },
      ],
      practice: [
        { index: 0, question: 'A quadrilateral has four right angles and opposite sides that are equal but not all four sides equal. What is it?', type: 'short-answer', correctAnswer: 'rectangle', hint: 'It has right angles like a square, but not all sides are the same length.', explanation: 'Four right angles and opposite sides equal describes a rectangle (that is not a square).', standardCode: '5.G.3' },
        { index: 1, question: 'True or false: Every square is a rhombus.', type: 'multiple-choice', options: ['True', 'False'], correctAnswer: 'True', hint: 'A rhombus has four equal sides. Does a square have four equal sides?', explanation: 'A square has four equal sides and four right angles. Since a rhombus requires four equal sides, every square meets that requirement.', standardCode: '5.G.4' },
        { index: 2, question: 'A triangle has sides of 3 cm, 4 cm, and 5 cm and one 90° angle. Classify it by sides and by angles.', type: 'short-answer', correctAnswer: 'scalene right triangle', hint: 'No sides are equal, and there is a 90° angle.', explanation: 'All three sides are different lengths (scalene), and one angle is exactly 90° (right).', standardCode: '5.G.3' },
        { index: 3, question: 'Which of these is NOT always true about a parallelogram?', type: 'multiple-choice', options: ['It has two pairs of parallel sides', 'Opposite sides are equal', 'All angles are 90°', 'Opposite angles are equal'], correctAnswer: 'All angles are 90°', hint: 'Think about a slanted parallelogram.', explanation: 'A parallelogram can have angles other than 90°. Only rectangles (a special parallelogram) guarantee four right angles.', standardCode: '5.G.4' },
        { index: 4, question: 'Name a quadrilateral that has exactly one pair of parallel sides.', type: 'short-answer', correctAnswer: 'trapezoid', hint: 'It is not a parallelogram.', explanation: 'A trapezoid has exactly one pair of parallel sides, unlike a parallelogram which has two.', standardCode: '5.G.3' },
      ],
      assessment: {
        questions: [
          { question: 'Is every rectangle a square? Explain why or why not.', type: 'short-answer', correctAnswer: 'No, because a rectangle does not require all four sides to be equal.', standardCode: '5.G.4' },
          { question: 'A triangle has three equal sides and three angles of 60°. What type of triangle is it?', type: 'multiple-choice', options: ['Scalene acute', 'Isosceles right', 'Equilateral acute', 'Equilateral right'], correctAnswer: 'Equilateral acute', standardCode: '5.G.3' },
          { question: 'Which shape belongs to ALL of these categories: quadrilateral, parallelogram, rectangle, rhombus?', type: 'short-answer', correctAnswer: 'square', standardCode: '5.G.4' },
        ],
      },
    },
  },
  {
    slug: 'grade5-math-converting-measurement-units',
    title: 'Converting Measurement Units',
    description: 'Convert among different-sized standard measurement units within a given measurement system',
    subject: 'math',
    grade: 5,
    gradeBand: 'k5',
    topicCluster: 'Measurement & Data',
    standardCodes: ['5.MD.1'],
    content: {
      intro: {
        title: 'Converting Measurement Units',
        text: 'If a recipe calls for 2 cups but your measuring jug is in ounces, you need to convert. If a race is 5 kilometers but you want to know the distance in meters, you need to convert. In this module you will learn to move between units of length, weight, and capacity within the same measurement system. The key idea is multiplying or dividing by conversion factors.',
      },
      segments: [
        {
          index: 0,
          title: 'Customary Units of Length, Weight, and Capacity',
          text: 'The U.S. customary system uses inches, feet, yards, and miles for length; ounces and pounds for weight; and cups, pints, quarts, and gallons for capacity. Key conversion facts: 1 foot = 12 inches, 1 yard = 3 feet, 1 mile = 5,280 feet, 1 pound = 16 ounces, 1 gallon = 4 quarts, 1 quart = 2 pints, 1 pint = 2 cups. To convert from a larger unit to a smaller unit, multiply. To go from smaller to larger, divide.',
          keyVocabulary: ['customary', 'convert', 'inch', 'foot', 'yard', 'mile', 'ounce', 'pound', 'cup', 'pint', 'quart', 'gallon'],
          example: '3 feet = 3 x 12 = 36 inches. 48 ounces = 48 ÷ 16 = 3 pounds.',
        },
        {
          index: 1,
          title: 'Metric Units of Length, Mass, and Capacity',
          text: 'The metric system is based on powers of 10, making conversions simpler. Length uses millimeters, centimeters, meters, and kilometers. Mass uses grams and kilograms. Capacity uses milliliters and liters. Key facts: 1 cm = 10 mm, 1 m = 100 cm, 1 km = 1,000 m, 1 kg = 1,000 g, 1 L = 1,000 mL. Since every conversion is by 10, 100, or 1,000, you just move the decimal point the right number of places.',
          keyVocabulary: ['metric', 'millimeter', 'centimeter', 'meter', 'kilometer', 'gram', 'kilogram', 'milliliter', 'liter'],
          example: '2.5 m = 2.5 x 100 = 250 cm. 4,500 mL = 4,500 ÷ 1,000 = 4.5 L.',
        },
        {
          index: 2,
          title: 'Multi-Step Conversions and Word Problems',
          text: 'Some problems require more than one conversion step or combine conversion with another operation. For instance, if you have 3 gallons of lemonade and serve 8-ounce cups, how many cups can you serve? First convert gallons to ounces: 3 gallons = 3 x 4 quarts = 12 quarts = 12 x 2 pints = 24 pints = 24 x 2 cups = 48 cups. Since 1 cup = 8 ounces, 48 cups x 8 = 384 ounces. Then 384 ÷ 8 = 48 servings. Setting up a clear plan before computing avoids errors.',
          keyVocabulary: ['multi-step', 'conversion factor', 'unit rate'],
        },
      ],
      practice: [
        { index: 0, question: 'Convert 5 yards to feet.', type: 'short-answer', correctAnswer: '15', hint: '1 yard = 3 feet. Multiply.', explanation: '5 x 3 = 15 feet.', standardCode: '5.MD.1' },
        { index: 1, question: 'How many milliliters are in 3.2 liters?', type: 'short-answer', correctAnswer: '3200', hint: '1 liter = 1,000 milliliters.', explanation: '3.2 x 1,000 = 3,200 mL.', standardCode: '5.MD.1' },
        { index: 2, question: 'A dog weighs 64 ounces. How many pounds is that?', type: 'short-answer', correctAnswer: '4', hint: '1 pound = 16 ounces. Divide.', explanation: '64 ÷ 16 = 4 pounds.', standardCode: '5.MD.1' },
        { index: 3, question: 'Convert 4.5 km to meters.', type: 'multiple-choice', options: ['45', '450', '4,500', '45,000'], correctAnswer: '4,500', hint: '1 km = 1,000 m.', explanation: '4.5 x 1,000 = 4,500 meters.', standardCode: '5.MD.1' },
        { index: 4, question: 'A jug holds 2 gallons. How many cups is that?', type: 'short-answer', correctAnswer: '32', hint: '1 gallon = 4 quarts = 8 pints = 16 cups.', explanation: '2 gallons x 16 cups per gallon = 32 cups.', standardCode: '5.MD.1' },
      ],
      assessment: {
        questions: [
          { question: 'Convert 7 feet to inches.', type: 'short-answer', correctAnswer: '84', standardCode: '5.MD.1' },
          { question: 'How many grams are in 2.75 kilograms?', type: 'short-answer', correctAnswer: '2750', standardCode: '5.MD.1' },
          { question: 'A rope is 10 yards long. How many inches is that?', type: 'multiple-choice', options: ['120', '300', '360', '3,600'], correctAnswer: '360', standardCode: '5.MD.1' },
        ],
      },
    },
  },
  {
    slug: 'grade5-math-numerical-patterns-graphing',
    title: 'Numerical Patterns and Graphing',
    description: 'Generate two numerical patterns using given rules and graph the resulting ordered pairs on a coordinate plane',
    subject: 'math',
    grade: 5,
    gradeBand: 'k5',
    topicCluster: 'Operations & Algebraic Thinking',
    standardCodes: ['5.OA.3'],
    content: {
      intro: {
        title: 'Numerical Patterns and Graphing',
        text: 'Patterns are everywhere — in music, art, and nature. In math, a pattern is a list of numbers that follows a rule. When you create two patterns that start at the same number and follow different rules, you can pair them up and plot the pairs on a coordinate plane. The graph reveals relationships between the patterns that are hard to see in the numbers alone.',
      },
      segments: [
        {
          index: 0,
          title: 'Generating Numerical Patterns',
          text: 'A numerical pattern (or sequence) starts with a number and applies a rule to get the next term. For example, start at 0 and add 3: 0, 3, 6, 9, 12, 15. Start at 0 and add 6: 0, 6, 12, 18, 24, 30. Each list can go on forever. By lining up the terms side by side, you can look for relationships. Notice that each term in the second pattern is exactly twice the corresponding term in the first pattern — because the rule "add 6" is double the rule "add 3."',
          keyVocabulary: ['pattern', 'sequence', 'rule', 'term', 'corresponding'],
          example: 'Rule: add 4 starting at 0 → 0, 4, 8, 12, 16. Rule: add 8 starting at 0 → 0, 8, 16, 24, 32.',
        },
        {
          index: 1,
          title: 'Forming Ordered Pairs',
          text: 'When you have two patterns that start at the same number, you can pair the corresponding terms to form ordered pairs. Using the patterns from the previous segment — add 3: 0, 3, 6, 9, 12 and add 6: 0, 6, 12, 18, 24 — the pairs are (0, 0), (3, 6), (6, 12), (9, 18), (12, 24). The first pattern gives the x-coordinate and the second gives the y-coordinate. These ordered pairs are ready to be plotted.',
          keyVocabulary: ['ordered pair', 'x-coordinate', 'y-coordinate', 'pair'],
        },
        {
          index: 2,
          title: 'Graphing and Identifying Relationships',
          text: 'Plot each ordered pair on a coordinate plane. For the pairs (0, 0), (3, 6), (6, 12), (9, 18), (12, 24), the points form a straight line through the origin. The graph shows that the y-value is always twice the x-value. Different rule combinations create different line patterns. If both rules are the same (add 3 and add 3), the points lie on a line where y always equals x. Graphs make it easy to predict values you have not yet calculated.',
          keyVocabulary: ['graph', 'coordinate plane', 'straight line', 'relationship', 'predict'],
          example: 'Patterns add 2 and add 5: pairs (0,0), (2,5), (4,10), (6,15). The y-value is always 2.5 times the x-value.',
        },
      ],
      practice: [
        { index: 0, question: 'Generate the first 5 terms of a pattern starting at 0 with the rule "add 4."', type: 'short-answer', correctAnswer: '0, 4, 8, 12, 16', hint: 'Start at 0 and keep adding 4.', explanation: '0, 0+4=4, 4+4=8, 8+4=12, 12+4=16.', standardCode: '5.OA.3' },
        { index: 1, question: 'Pattern A: add 2 (0, 2, 4, 6, 8). Pattern B: add 6 (0, 6, 12, 18, 24). What is the third ordered pair?', type: 'short-answer', correctAnswer: '(4, 12)', hint: 'The third term in Pattern A is 4 and in Pattern B is 12.', explanation: 'The third terms are 4 and 12, so the ordered pair is (4, 12).', standardCode: '5.OA.3' },
        { index: 2, question: 'Using the patterns in the previous question, how many times greater is each term in Pattern B than the corresponding term in Pattern A?', type: 'short-answer', correctAnswer: '3', hint: 'Compare: 6 ÷ 2, 12 ÷ 4, 18 ÷ 6.', explanation: 'Each term in B is 3 times the corresponding term in A (6/2=3, 12/4=3, etc.).', standardCode: '5.OA.3' },
        { index: 3, question: 'If both patterns use the rule "add 5" starting at 0, what do the ordered pairs look like?', type: 'multiple-choice', options: ['(0,0), (5,10), (10,15)', '(0,0), (5,5), (10,10), (15,15)', '(5,5), (10,10), (15,20)', '(0,5), (5,10), (10,15)'], correctAnswer: '(0,0), (5,5), (10,10), (15,15)', hint: 'Both patterns produce the same terms.', explanation: 'With the same rule, corresponding terms are equal, so each point has x = y.', standardCode: '5.OA.3' },
        { index: 4, question: 'Points (0,0), (1,3), (2,6), (3,9) are plotted. What is the y-value when x = 5?', type: 'short-answer', correctAnswer: '15', hint: 'The y-value is always 3 times the x-value.', explanation: 'The pattern shows y = 3x. When x = 5, y = 15.', standardCode: '5.OA.3' },
      ],
      assessment: {
        questions: [
          { question: 'Pattern A: add 3 starting at 0. Pattern B: add 9 starting at 0. Write the first four ordered pairs.', type: 'short-answer', correctAnswer: '(0,0), (3,9), (6,18), (9,27)', standardCode: '5.OA.3' },
          { question: 'In the patterns above, each y-value is how many times the x-value?', type: 'short-answer', correctAnswer: '3', standardCode: '5.OA.3' },
          { question: 'Which set of ordered pairs forms a straight line through the origin?', type: 'multiple-choice', options: ['(1,2), (2,5), (3,6)', '(0,0), (2,4), (4,8)', '(1,1), (2,3), (3,4)', '(0,1), (1,2), (2,3)'], correctAnswer: '(0,0), (2,4), (4,8)', standardCode: '5.OA.3' },
        ],
      },
    },
  },
  {
    slug: 'grade5-math-line-plots-with-fractions',
    title: 'Line Plots with Fractions',
    description: 'Make line plots to display data sets measured in fractional units and use them to solve problems',
    subject: 'math',
    grade: 5,
    gradeBand: 'k5',
    topicCluster: 'Measurement & Data',
    standardCodes: ['5.MD.2'],
    content: {
      intro: {
        title: 'Line Plots with Fractions',
        text: 'A line plot is a simple graph that shows how often each value appears in a data set. When the values include fractions — like lengths measured to the nearest quarter inch or amounts measured to the nearest eighth of a cup — the line plot helps you see the shape of the data at a glance. In this module you will create and interpret line plots with fractional data and use them to solve addition and subtraction problems.',
      },
      segments: [
        {
          index: 0,
          title: 'What Is a Line Plot?',
          text: 'A line plot uses a number line with X marks (or dots) above each value to show how many times that value appears. For example, if five students measured the lengths of caterpillars and got 1/4, 1/2, 1/2, 3/4, and 1/2 inch, you draw a number line showing 1/4, 1/2, and 3/4. Place one X above 1/4, three Xs above 1/2, and one X above 3/4. The stack of Xs tells you that 1/2 inch was the most common length. Line plots work best for small data sets with values that repeat.',
          keyVocabulary: ['line plot', 'data set', 'frequency', 'X mark', 'number line'],
          example: 'Data: 1/8, 1/4, 1/4, 3/8, 1/4. The line plot has one X at 1/8, three Xs at 1/4, and one X at 3/8.',
        },
        {
          index: 1,
          title: 'Creating a Line Plot with Fractional Data',
          text: 'To create a line plot, first examine your data and identify the smallest and largest values. Draw a number line that covers this range, marking equal intervals in the fractional unit used (halves, quarters, eighths, etc.). Then place an X above the corresponding value for each data point. Make sure to include all values on the number line even if no data point matches — this shows gaps in the data clearly. Give the line plot a title and label the number line.',
          keyVocabulary: ['interval', 'range', 'label', 'title', 'gap'],
        },
        {
          index: 2,
          title: 'Interpreting Line Plots and Solving Problems',
          text: 'Once the line plot is built, you can answer questions about the data. How many data points are there? Count all the Xs. What is the most common value (mode)? Find the tallest stack. What is the difference between the greatest and least values? Subtract. You can also add up all the data values to find the total. For example, if the Xs show two values at 1/4 and three values at 1/2, the total is 2 x 1/4 + 3 x 1/2 = 1/2 + 3/2 = 4/2 = 2.',
          keyVocabulary: ['mode', 'total', 'difference', 'sum', 'interpret'],
          example: 'Data on a line plot: 1/8, 1/8, 3/8, 3/8, 3/8. Total = 2 x 1/8 + 3 x 3/8 = 2/8 + 9/8 = 11/8 = 1 3/8.',
        },
      ],
      practice: [
        { index: 0, question: 'A line plot shows 2 Xs at 1/4, 4 Xs at 1/2, and 1 X at 3/4. How many data points are there?', type: 'short-answer', correctAnswer: '7', hint: 'Count all the Xs.', explanation: '2 + 4 + 1 = 7 data points.', standardCode: '5.MD.2' },
        { index: 1, question: 'Using the same line plot, what is the most common value?', type: 'short-answer', correctAnswer: '1/2', hint: 'Which value has the most Xs above it?', explanation: '1/2 has 4 Xs, more than any other value.', standardCode: '5.MD.2' },
        { index: 2, question: 'What is the total of all data values on the line plot: 2 at 1/4, 4 at 1/2, 1 at 3/4?', type: 'short-answer', correctAnswer: '3 1/4', hint: 'Multiply each value by its frequency and add: 2 x 1/4 + 4 x 1/2 + 1 x 3/4.', explanation: '2/4 + 4/2 + 3/4 = 2/4 + 8/4 + 3/4 = 13/4 = 3 1/4.', standardCode: '5.MD.2' },
        { index: 3, question: 'Students measured pencil lengths to the nearest 1/8 inch. Which fractional units should the number line show?', type: 'multiple-choice', options: ['Halves', 'Quarters', 'Eighths', 'Sixteenths'], correctAnswer: 'Eighths', hint: 'Match the unit of measurement.', explanation: 'Since measurements are to the nearest 1/8 inch, the number line should be marked in eighths.', standardCode: '5.MD.2' },
        { index: 4, question: 'A line plot shows plant heights: 3 at 3/8 inch and 2 at 5/8 inch. What is the difference between the tallest and shortest plants?', type: 'short-answer', correctAnswer: '1/4', hint: '5/8 − 3/8 = ?', explanation: '5/8 − 3/8 = 2/8 = 1/4 inch.', standardCode: '5.MD.2' },
      ],
      assessment: {
        questions: [
          { question: 'A line plot has 3 Xs at 1/2, 2 Xs at 3/4, and 1 X at 1. What is the total of all data values?', type: 'short-answer', correctAnswer: '4', standardCode: '5.MD.2' },
          { question: 'How many data points does a line plot with 5 Xs at 1/4 and 3 Xs at 3/4 have?', type: 'short-answer', correctAnswer: '8', standardCode: '5.MD.2' },
          { question: 'Which is the best tool for showing how often each fractional measurement occurs in a small data set?', type: 'multiple-choice', options: ['Bar graph', 'Line plot', 'Pie chart', 'Histogram'], correctAnswer: 'Line plot', standardCode: '5.MD.2' },
        ],
      },
    },
  },
]
